import { NextResponse } from "next/server";
import { resolveRequestScope } from "@/lib/request-scope";
import { assertFirmPermission } from "@/lib/authorization";
import { createServerSupabaseClient } from "@/lib/supabase-server";

function dateRange(url:URL){const end=url.searchParams.get('end')||new Date().toISOString().slice(0,10);const start=url.searchParams.get('start')||new Date(new Date(end).getTime()-90*86400000).toISOString().slice(0,10);return{start,end};}
async function build(scope:any,start:string,end:string){const supabase=createServerSupabaseClient();if(!supabase)throw new Error('Supabase server configuration is required.');const lawyers=await supabase.from('lawyers').select('id,full_name,role').eq('firm_id',scope.firmId).order('full_name');if(lawyers.error)throw new Error(lawyers.error.message);const rows=[];for(const lawyer of lawyers.data??[]){const [tasks,time,reviews,events]=await Promise.all([supabase.from('tasks').select('id,status,is_completed,deadline,created_at').eq('assigned_to',lawyer.id).gte('created_at',start).lte('created_at',`${end}T23:59:59Z`),supabase.from('matter_time_entries').select('minutes,billable,created_at').eq('lawyer_id',lawyer.id).gte('created_at',start).lte('created_at',`${end}T23:59:59Z`),supabase.from('document_review_events').select('id,action,created_at').eq('actor_lawyer_id',lawyer.id).gte('created_at',start).lte('created_at',`${end}T23:59:59Z`),supabase.from('matter_events').select('id,event_type,created_at').eq('firm_id',scope.firmId).eq('actor_name',lawyer.full_name).gte('created_at',start).lte('created_at',`${end}T23:59:59Z`)]);for(const r of[tasks,time,reviews,events])if(r.error)throw new Error(r.error.message);const taskRows=tasks.data??[];const completed=taskRows.filter((x:any)=>x.is_completed||String(x.status).toLowerCase()==='done').length;const overdue=taskRows.filter((x:any)=>!x.is_completed&&x.deadline&&new Date(x.deadline)<new Date()).length;const minutes=(time.data??[]).reduce((s:number,x:any)=>s+Number(x.minutes||0),0);const billable=(time.data??[]).filter((x:any)=>x.billable).reduce((s:number,x:any)=>s+Number(x.minutes||0),0);rows.push({lawyer,metrics:{tasksAssigned:taskRows.length,tasksCompleted:completed,openOrOverdue:overdue,completionRate:taskRows.length?Math.round(completed/taskRows.length*100):null,totalMinutes:minutes,billableMinutes:billable,documentReviewActions:(reviews.data??[]).length,matterEvents:(events.data??[]).length}});}return{supabase,rows};}
export async function GET(request:Request){try{const scope=await resolveRequestScope(request);await assertFirmPermission({scope,permission:'manageFirm'});if(!scope.firmId)throw new Error('Authenticated firm context is required.');const url=new URL(request.url);const{start,end}=dateRange(url);const{rows}=await build(scope,start,end);return NextResponse.json({success:true,start,end,people:rows});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:'Unable to load performance.'},{status:403});}}
export async function POST(request:Request){try{const scope=await resolveRequestScope(request);await assertFirmPermission({scope,permission:'manageFirm'});if(!scope.firmId||!scope.actorLawyerId)throw new Error('Governor lawyer context is required.');const body=await request.json();const lawyerId=String(body.lawyerId||'');const start=String(body.start||'');const end=String(body.end||'');if(!lawyerId||!start||!end)return NextResponse.json({success:false,error:'Lawyer and review period are required.'},{status:400});const{rows,supabase}=await build(scope,start,end);const target=rows.find((x:any)=>x.lawyer.id===lawyerId);if(!target)return NextResponse.json({success:false,error:'Lawyer not found.'},{status:404});const saved=await supabase.from('performance_reviews').upsert({firm_id:scope.firmId,lawyer_id:lawyerId,period_start:start,period_end:end,metrics:target.metrics,supervisor_assessment:body.supervisorAssessment||null,development_plan:body.developmentPlan||null,status:String(body.status||'draft'),reviewed_by:scope.actorLawyerId,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'firm_id,lawyer_id,period_start,period_end'}).select('*').single();if(saved.error)throw new Error(saved.error.message);return NextResponse.json({success:true,review:saved.data});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:'Unable to save review.'},{status:403});}}
