export const supportedLocales = ["en","fr","es","pt","ar","sw"] as const;
export type Locale = typeof supportedLocales[number];

export const localeLabels: Record<Locale,string> = {
  en:"English", fr:"Français", es:"Español", pt:"Português", ar:"العربية", sw:"Kiswahili"
};

export const localeMeta: Record<Locale,{htmlLang:string;dir:"ltr"|"rtl";intl:string}> = {
  en:{htmlLang:"en",dir:"ltr",intl:"en-GB"},
  fr:{htmlLang:"fr",dir:"ltr",intl:"fr-FR"},
  es:{htmlLang:"es",dir:"ltr",intl:"es-ES"},
  pt:{htmlLang:"pt",dir:"ltr",intl:"pt-PT"},
  ar:{htmlLang:"ar",dir:"rtl",intl:"ar"},
  sw:{htmlLang:"sw",dir:"ltr",intl:"sw-KE"},
};

type Dict = Record<string,string>;
const en: Dict = {
  "menu.home":"Home","menu.matters":"Matter Work","menu.clients":"Clients","menu.knowledge":"Knowledge & Documents","menu.office":"Office & Finance","menu.firm":"Firm Setup",
  "common.search":"Search","common.communications":"Communications","common.notifications":"Notifications","common.open":"Open","common.close":"Close","common.retry":"Retry",
  "nav.command":"Command","nav.command.desc":"Today, risk and priority","nav.search":"Search","nav.search.desc":"Cases, clients, documents and references","nav.clients":"Clients","nav.clients.desc":"Relationships, KYC and client history","nav.cases":"Cases","nav.cases.desc":"Dossiers, deadlines and legal work","nav.workroom":"Workroom","nav.workroom.desc":"Assignments, follow-up and team work","nav.reports":"Compte Rendu","nav.reports.desc":"Work record, time and billing evidence","nav.intake":"Intake & Due Diligence","nav.intake.desc":"Intake, conflict, KYC and engagement","nav.comms":"Communications","nav.comms.desc":"Email, WhatsApp, calls and client history","nav.interactions":"Interactions","nav.interactions.desc":"Notes, recordings and meetings","nav.whatsapp":"WhatsApp Desk","nav.whatsapp.desc":"Messages, secure forms and triggers","nav.forms":"Forms Bank","nav.forms.desc":"Reusable firm forms and records","nav.documents":"Document Bank","nav.documents.desc":"Precedents and AI-assisted adaptation","nav.law":"Law Bank","nav.law.desc":"Law and verified legal sources","nav.business":"Business & Office","nav.business.desc":"Suppliers, obligations, spending and evidence","nav.finance":"Billing & Finance","nav.finance.desc":"Invoices, payments, cash and collections","nav.digitisation":"Digitisation","nav.digitisation.desc":"Evidence and legacy files","nav.people":"People","nav.people.desc":"Teams and performance","nav.storage":"Storage & Integrations","nav.storage.desc":"File custody and provider health","nav.control":"Firm Control","nav.control.desc":"Ways of working, recommended setup and governance","nav.studio":"Firm Studio","nav.studio.desc":"Identity, forms, workflows, legal parameters and AI policy",
  "workspace.activeFirm":"Active firm","workspace.legalWorkspace":"Legal operating workspace","workspace.activeCases":"Active cases","workspace.urgentWork":"Urgent work","workspace.openIntake":"Open intake","workspace.highRisk":"High risk","workspace.caseCommand":"Case command","workspace.workDue":"Work due","workspace.draftingReview":"Drafting & review","workspace.clientCycle":"Client cycle","workspace.noCases":"No accessible cases.","workspace.noWork":"No open tasks.","workspace.noDocs":"No documents awaiting review.","workspace.noIntake":"No open assessments.","workspace.loading":"Restoring legal workspace","workspace.loadingDetail":"Resolving active firm, role and operating queues…","workspace.unavailable":"Workspace unavailable",
  "role.owner.eyebrow":"Firm command","role.owner.heading":"Run the firm from one accountable legal operating surface.","role.owner.summary":"Matters, client obligations, legal sources, collections and professional controls are visible without turning the system into a wall of cards.",
  "role.partner.eyebrow":"Partner command","role.partner.heading":"See risk and professional judgment before administration.","role.partner.summary":"Approvals, sensitive matters, client commitments and financial exposure stay connected to the underlying file.",
  "role.finance.eyebrow":"Finance desk","role.finance.heading":"Collections stay connected to the matters that created them.","role.finance.summary":"Invoices, payments, expenses and outstanding balances remain traceable to legal work.",
  "role.lawyer.eyebrow":"Lawyer desk","role.lawyer.heading":"Work from the next legal action, not from disconnected tools.","role.lawyer.summary":"Matters, deadlines, drafts, client instructions and source-backed research meet in one workspace.",
  "studio.eyebrow":"Firm Studio","studio.title":"Design how the firm operates","studio.summary":"Shape identity, forms, legal taxonomy, workflow patterns, interaction policy and AI behavior. Firm Control governs adoption and authority; Studio lets the firm evolve the operating system without exposing configuration complexity to everyday staff.",
  "studio.identity":"Identity & Brand","studio.ways":"Ways of Working","studio.legal":"Legal Parameters","studio.workflows":"Recommended Workflows","studio.forms":"Forms & Documents","studio.ai":"Privacy, Interaction & AI","studio.language":"Product language","studio.languageHelp":"Choose the interface language for this device. Firm document language remains independently configurable.",
  "matter.caseStudio":"Case Studio","matter.workroom":"Workroom","matter.economics":"Economics & time","matter.firmWorkspace":"Firm workspace","matter.command":"Matter command","matter.commandTitle":"What matters now and what happens next","matter.commandText":"TSID leads with one live Matter plan and one contextual Room. Strategy, intelligence and evidence are inside that Room rather than competing beside it.","matter.act":"Act","matter.actTitle":"Judgment, instructions and execution","matter.caseStudioTitle":"Case Studio & file","matter.caseStudioDesc":"Structured case facts, digital file twin, firm templates, personalized drafting, documents and collaboration. Strategy and legal intelligence stay in the canonical Matter Room above.",
  "room.canonical":"Canonical matter room","room.control":"Professional control","room.reasoning":"Reasoning & issues","room.evidence":"Evidence & provenance","room.decisions":"Professional decisions","room.client":"Client position","room.execution":"Execution","room.handoffs":"Professional handoffs","room.deep":"Strategy intelligence, sources & institutional memory",
  "studio.case.fields":"Structured case fields","studio.case.fieldsTitle":"Matter facts we can reuse everywhere","studio.case.digital":"Digital case file store","studio.case.digitalTitle":"The digital twin of the physical file","studio.case.templates":"Template library","studio.case.templatesTitle":"Preserve form, change context","studio.case.drafting":"Personalized drafting","studio.case.draftingTitle":"Generate a matter-specific draft from firm form",
  "workroom.title":"Workroom","workroom.back":"Back to Workroom","workroom.responsible":"Responsible","workroom.unassigned":"Unassigned","workroom.teamConversation":"Team conversation","workroom.noComments":"No comments yet.","workroom.post":"Post update","workroom.posting":"Posting…","workroom.execution":"Execution state","workroom.noDeadline":"No deadline assigned.","workroom.status":"Status","workroom.open":"Open","workroom.inProgress":"In progress","workroom.waiting":"Waiting","workroom.review":"Review","workroom.completed":"Completed","workroom.cancelled":"Cancelled","workroom.conversation":"Conversation","workroom.aiReview":"AI review","workroom.share":"External review link","workroom.send":"Send","workroom.start":"Start the conversation."
};

const fr: Dict = {
  "menu.home":"Accueil","menu.matters":"Travail juridique","menu.clients":"Clients","menu.knowledge":"Connaissances & Documents","menu.office":"Cabinet & Finance","menu.firm":"Configuration du cabinet",
  "common.search":"Rechercher","common.communications":"Communications","common.notifications":"Notifications","common.open":"Ouvrir","common.close":"Fermer","common.retry":"Réessayer",
  "nav.command":"Pilotage","nav.command.desc":"Aujourd’hui, risques et priorités","nav.search":"Recherche","nav.search.desc":"Dossiers, clients, documents et références","nav.clients":"Clients","nav.clients.desc":"Relations, KYC et historique client","nav.cases":"Dossiers","nav.cases.desc":"Dossiers, échéances et travail juridique","nav.workroom":"Espace de travail","nav.workroom.desc":"Attributions, suivi et collaboration","nav.reports":"Compte Rendu","nav.reports.desc":"Travail, temps et preuves de facturation","nav.intake":"Admission & Due Diligence","nav.intake.desc":"Admission, conflits, KYC et engagement","nav.comms":"Communications","nav.comms.desc":"E-mail, WhatsApp, appels et historique client","nav.interactions":"Interactions","nav.interactions.desc":"Notes, enregistrements et réunions","nav.whatsapp":"Bureau WhatsApp","nav.whatsapp.desc":"Messages, formulaires sécurisés et déclencheurs","nav.forms":"Banque de formulaires","nav.forms.desc":"Formulaires et registres réutilisables","nav.documents":"Banque documentaire","nav.documents.desc":"Précédents et adaptation assistée par IA","nav.law":"Banque juridique","nav.law.desc":"Droit et sources juridiques vérifiées","nav.business":"Entreprise & Bureau","nav.business.desc":"Fournisseurs, obligations, dépenses et preuves","nav.finance":"Facturation & Finance","nav.finance.desc":"Factures, paiements, trésorerie et recouvrement","nav.digitisation":"Numérisation","nav.digitisation.desc":"Preuves et archives physiques","nav.people":"Équipe","nav.people.desc":"Équipes et performance","nav.storage":"Stockage & Intégrations","nav.storage.desc":"Conservation des fichiers et état des fournisseurs","nav.control":"Contrôle du cabinet","nav.control.desc":"Méthodes de travail, configuration recommandée et gouvernance","nav.studio":"Studio du cabinet","nav.studio.desc":"Identité, formulaires, workflows, paramètres juridiques et politique IA",
  "workspace.activeFirm":"Cabinet actif","workspace.legalWorkspace":"Espace opérationnel juridique","workspace.activeCases":"Dossiers actifs","workspace.urgentWork":"Travail urgent","workspace.openIntake":"Admissions ouvertes","workspace.highRisk":"Risque élevé","workspace.caseCommand":"Pilotage des dossiers","workspace.workDue":"Travail à échéance","workspace.draftingReview":"Rédaction & revue","workspace.clientCycle":"Cycle client","workspace.noCases":"Aucun dossier accessible.","workspace.noWork":"Aucune tâche ouverte.","workspace.noDocs":"Aucun document en attente de revue.","workspace.noIntake":"Aucune évaluation ouverte.","workspace.loading":"Restauration de l’espace juridique","workspace.loadingDetail":"Résolution du cabinet actif, du rôle et des files opérationnelles…","workspace.unavailable":"Espace indisponible",
  "role.owner.eyebrow":"Pilotage du cabinet","role.owner.heading":"Dirigez le cabinet depuis une seule surface juridique responsable.","role.owner.summary":"Dossiers, obligations clients, sources juridiques, recouvrement et contrôles professionnels restent visibles sans transformer le système en mur de cartes.",
  "role.partner.eyebrow":"Pilotage associé","role.partner.heading":"Voyez les risques et le jugement professionnel avant l’administration.","role.partner.summary":"Approbations, dossiers sensibles, engagements clients et exposition financière restent liés au dossier.",
  "role.finance.eyebrow":"Bureau finance","role.finance.heading":"Le recouvrement reste lié aux dossiers qui l’ont généré.","role.finance.summary":"Factures, paiements, dépenses et soldes restent traçables jusqu’au travail juridique.",
  "role.lawyer.eyebrow":"Bureau avocat","role.lawyer.heading":"Travaillez à partir de la prochaine action juridique, pas d’outils dispersés.","role.lawyer.summary":"Dossiers, échéances, projets, instructions clients et recherche sourcée se rencontrent dans un même espace.",
  "studio.eyebrow":"Studio du cabinet","studio.title":"Concevez le fonctionnement du cabinet","studio.summary":"Façonnez l’identité, les formulaires, la taxonomie juridique, les workflows, les politiques d’interaction et le comportement IA. Le Contrôle du cabinet gouverne l’adoption et l’autorité; le Studio permet de faire évoluer le système.",
  "studio.identity":"Identité & Marque","studio.ways":"Méthodes de travail","studio.legal":"Paramètres juridiques","studio.workflows":"Workflows recommandés","studio.forms":"Formulaires & Documents","studio.ai":"Confidentialité, Interaction & IA","studio.language":"Langue du produit","studio.languageHelp":"Choisissez la langue de l’interface sur cet appareil. La langue des documents du cabinet reste configurable séparément.",
  "matter.caseStudio":"Studio du dossier","matter.workroom":"Espace de travail","matter.economics":"Économie & temps","matter.firmWorkspace":"Espace du cabinet","matter.command":"Pilotage du dossier","matter.commandTitle":"Ce qui compte maintenant et la prochaine étape","matter.commandText":"TSID s’appuie sur un seul plan vivant et une Room contextuelle. Stratégie, intelligence et preuve vivent dans cette Room.","matter.act":"Agir","matter.actTitle":"Jugement, instructions et exécution","matter.caseStudioTitle":"Studio & dossier numérique","matter.caseStudioDesc":"Faits structurés, jumeau numérique du dossier, modèles du cabinet, rédaction personnalisée, documents et collaboration.",
  "room.canonical":"Room juridique canonique","room.control":"Contrôle professionnel","room.reasoning":"Raisonnement & questions","room.evidence":"Preuves & provenance","room.decisions":"Décisions professionnelles","room.client":"Position du client","room.execution":"Exécution","room.handoffs":"Passations professionnelles","room.deep":"Stratégie, intelligence, sources & mémoire institutionnelle",
  "studio.case.fields":"Champs structurés du dossier","studio.case.fieldsTitle":"Des faits réutilisables partout","studio.case.digital":"Dossier numérique","studio.case.digitalTitle":"Le jumeau numérique du dossier physique","studio.case.templates":"Bibliothèque de modèles","studio.case.templatesTitle":"Préserver la forme, adapter le contexte","studio.case.drafting":"Rédaction personnalisée","studio.case.draftingTitle":"Générer un projet adapté au dossier à partir d’un modèle du cabinet",
  "workroom.title":"Espace de travail","workroom.back":"Retour à l’espace de travail","workroom.responsible":"Responsable","workroom.unassigned":"Non attribué","workroom.teamConversation":"Conversation d’équipe","workroom.noComments":"Aucun commentaire.","workroom.post":"Publier la mise à jour","workroom.posting":"Publication…","workroom.execution":"État d’exécution","workroom.noDeadline":"Aucune échéance attribuée.","workroom.status":"Statut","workroom.open":"Ouvert","workroom.inProgress":"En cours","workroom.waiting":"En attente","workroom.review":"Revue","workroom.completed":"Terminé","workroom.cancelled":"Annulé","workroom.conversation":"Conversation","workroom.aiReview":"Revue IA","workroom.share":"Lien de revue externe","workroom.send":"Envoyer","workroom.start":"Commencez la conversation."
};

const es: Dict = {
  "menu.home":"Inicio","menu.matters":"Trabajo jurídico","menu.clients":"Clientes","menu.knowledge":"Conocimiento y Documentos","menu.office":"Oficina y Finanzas","menu.firm":"Configuración del despacho",
  "common.search":"Buscar","common.communications":"Comunicaciones","common.notifications":"Notificaciones","common.open":"Abrir","common.close":"Cerrar","common.retry":"Reintentar",
  "nav.command":"Mando","nav.command.desc":"Hoy, riesgo y prioridad","nav.search":"Buscar","nav.search.desc":"Asuntos, clientes, documentos y referencias","nav.clients":"Clientes","nav.cases":"Asuntos","nav.workroom":"Sala de trabajo","nav.reports":"Informe de actividad","nav.intake":"Admisión y Due Diligence","nav.comms":"Comunicaciones","nav.interactions":"Interacciones","nav.whatsapp":"Mesa WhatsApp","nav.forms":"Banco de formularios","nav.documents":"Banco documental","nav.law":"Banco jurídico","nav.business":"Negocio y Oficina","nav.finance":"Facturación y Finanzas","nav.digitisation":"Digitalización","nav.people":"Personas","nav.storage":"Almacenamiento e Integraciones","nav.control":"Control del despacho","nav.studio":"Studio del despacho",
  "workspace.activeFirm":"Despacho activo","workspace.legalWorkspace":"Espacio operativo jurídico","workspace.activeCases":"Asuntos activos","workspace.urgentWork":"Trabajo urgente","workspace.openIntake":"Admisiones abiertas","workspace.highRisk":"Alto riesgo","workspace.caseCommand":"Mando de asuntos","workspace.workDue":"Trabajo pendiente","workspace.draftingReview":"Redacción y revisión","workspace.clientCycle":"Ciclo del cliente","workspace.noCases":"No hay asuntos accesibles.","workspace.noWork":"No hay tareas abiertas.","workspace.noDocs":"No hay documentos pendientes de revisión.","workspace.noIntake":"No hay evaluaciones abiertas.","workspace.loading":"Restaurando espacio jurídico","workspace.loadingDetail":"Resolviendo despacho activo, rol y colas operativas…","workspace.unavailable":"Espacio no disponible",
  "studio.eyebrow":"Studio del despacho","studio.title":"Diseña cómo opera el despacho","studio.summary":"Configura identidad, formularios, taxonomía jurídica, flujos de trabajo, políticas de interacción y comportamiento de IA.","studio.identity":"Identidad y Marca","studio.ways":"Forma de trabajar","studio.legal":"Parámetros jurídicos","studio.workflows":"Flujos recomendados","studio.forms":"Formularios y Documentos","studio.ai":"Privacidad, Interacción e IA","studio.language":"Idioma del producto","studio.languageHelp":"Elige el idioma de la interfaz en este dispositivo.",
  "matter.caseStudio":"Studio del asunto","matter.workroom":"Sala de trabajo","matter.economics":"Economía y tiempo","matter.firmWorkspace":"Espacio del despacho","room.canonical":"Sala jurídica canónica","room.control":"Control profesional","room.reasoning":"Razonamiento y cuestiones","room.evidence":"Prueba y procedencia","room.decisions":"Decisiones profesionales","room.client":"Posición del cliente","room.execution":"Ejecución","room.handoffs":"Relevos profesionales","room.deep":"Estrategia, inteligencia, fuentes y memoria institucional","workroom.title":"Sala de trabajo","workroom.back":"Volver a la sala","workroom.responsible":"Responsable","workroom.unassigned":"Sin asignar","workroom.teamConversation":"Conversación del equipo","workroom.noComments":"Aún no hay comentarios.","workroom.post":"Publicar actualización","workroom.posting":"Publicando…","workroom.execution":"Estado de ejecución","workroom.noDeadline":"Sin fecha límite.","workroom.status":"Estado","workroom.open":"Abierto","workroom.inProgress":"En curso","workroom.waiting":"En espera","workroom.review":"Revisión","workroom.completed":"Completado","workroom.cancelled":"Cancelado","workroom.conversation":"Conversación","workroom.aiReview":"Revisión IA","workroom.share":"Enlace de revisión externa","workroom.send":"Enviar","workroom.start":"Inicia la conversación."
};

const pt: Dict = {
  "menu.home":"Início","menu.matters":"Trabalho jurídico","menu.clients":"Clientes","menu.knowledge":"Conhecimento e Documentos","menu.office":"Escritório e Finanças","menu.firm":"Configuração do escritório",
  "common.search":"Pesquisar","common.communications":"Comunicações","common.notifications":"Notificações","common.open":"Abrir","common.close":"Fechar","common.retry":"Tentar novamente",
  "nav.command":"Comando","nav.search":"Pesquisa","nav.clients":"Clientes","nav.cases":"Processos","nav.workroom":"Sala de trabalho","nav.reports":"Relatório","nav.intake":"Admissão e Due Diligence","nav.comms":"Comunicações","nav.interactions":"Interações","nav.whatsapp":"Mesa WhatsApp","nav.forms":"Banco de formulários","nav.documents":"Banco documental","nav.law":"Banco jurídico","nav.business":"Negócio e Escritório","nav.finance":"Faturação e Finanças","nav.digitisation":"Digitalização","nav.people":"Pessoas","nav.storage":"Armazenamento e Integrações","nav.control":"Controlo do escritório","nav.studio":"Studio do escritório",
  "workspace.activeFirm":"Escritório ativo","workspace.legalWorkspace":"Espaço operacional jurídico","workspace.activeCases":"Processos ativos","workspace.urgentWork":"Trabalho urgente","workspace.openIntake":"Admissões abertas","workspace.highRisk":"Alto risco","workspace.caseCommand":"Comando dos processos","workspace.workDue":"Trabalho pendente","workspace.draftingReview":"Redação e revisão","workspace.clientCycle":"Ciclo do cliente","workspace.noCases":"Nenhum processo acessível.","workspace.noWork":"Nenhuma tarefa aberta.","workspace.noDocs":"Nenhum documento para revisão.","workspace.noIntake":"Nenhuma avaliação aberta.","workspace.loading":"A restaurar o espaço jurídico","workspace.loadingDetail":"A resolver escritório ativo, função e filas operacionais…","workspace.unavailable":"Espaço indisponível",
  "studio.eyebrow":"Studio do escritório","studio.title":"Desenhe como o escritório opera","studio.summary":"Configure identidade, formulários, taxonomia jurídica, workflows, políticas de interação e comportamento da IA.","studio.identity":"Identidade e Marca","studio.ways":"Formas de trabalhar","studio.legal":"Parâmetros jurídicos","studio.workflows":"Workflows recomendados","studio.forms":"Formulários e Documentos","studio.ai":"Privacidade, Interação e IA","studio.language":"Idioma do produto","studio.languageHelp":"Escolha o idioma da interface neste dispositivo.",
  "matter.caseStudio":"Studio do processo","matter.workroom":"Sala de trabalho","matter.economics":"Economia e tempo","matter.firmWorkspace":"Espaço do escritório","room.canonical":"Sala jurídica canónica","room.control":"Controlo profissional","room.reasoning":"Raciocínio e questões","room.evidence":"Prova e proveniência","room.decisions":"Decisões profissionais","room.client":"Posição do cliente","room.execution":"Execução","room.handoffs":"Transições profissionais","room.deep":"Estratégia, inteligência, fontes e memória institucional","workroom.title":"Sala de trabalho","workroom.back":"Voltar à sala","workroom.responsible":"Responsável","workroom.unassigned":"Não atribuído","workroom.teamConversation":"Conversa da equipa","workroom.noComments":"Ainda sem comentários.","workroom.post":"Publicar atualização","workroom.posting":"A publicar…","workroom.execution":"Estado de execução","workroom.noDeadline":"Sem prazo atribuído.","workroom.status":"Estado","workroom.open":"Aberto","workroom.inProgress":"Em curso","workroom.waiting":"Em espera","workroom.review":"Revisão","workroom.completed":"Concluído","workroom.cancelled":"Cancelado","workroom.conversation":"Conversa","workroom.aiReview":"Revisão IA","workroom.share":"Ligação de revisão externa","workroom.send":"Enviar","workroom.start":"Inicie a conversa."
};

const ar: Dict = {
  "menu.home":"الرئيسية","menu.matters":"العمل القانوني","menu.clients":"العملاء","menu.knowledge":"المعرفة والمستندات","menu.office":"المكتب والمالية","menu.firm":"إعداد المكتب",
  "common.search":"بحث","common.communications":"الاتصالات","common.notifications":"الإشعارات","common.open":"فتح","common.close":"إغلاق","common.retry":"إعادة المحاولة",
  "nav.command":"القيادة","nav.search":"البحث","nav.clients":"العملاء","nav.cases":"القضايا","nav.workroom":"غرفة العمل","nav.reports":"تقرير النشاط","nav.intake":"الاستقبال والعناية الواجبة","nav.comms":"الاتصالات","nav.interactions":"التفاعلات","nav.whatsapp":"مكتب واتساب","nav.forms":"بنك النماذج","nav.documents":"بنك المستندات","nav.law":"البنك القانوني","nav.business":"الأعمال والمكتب","nav.finance":"الفوترة والمالية","nav.digitisation":"الرقمنة","nav.people":"الأشخاص","nav.storage":"التخزين والتكاملات","nav.control":"تحكم المكتب","nav.studio":"استوديو المكتب",
  "workspace.activeFirm":"المكتب النشط","workspace.legalWorkspace":"مساحة التشغيل القانونية","workspace.activeCases":"القضايا النشطة","workspace.urgentWork":"العمل العاجل","workspace.openIntake":"طلبات مفتوحة","workspace.highRisk":"مخاطر عالية","workspace.caseCommand":"قيادة القضايا","workspace.workDue":"العمل المستحق","workspace.draftingReview":"الصياغة والمراجعة","workspace.clientCycle":"دورة العميل","workspace.noCases":"لا توجد قضايا متاحة.","workspace.noWork":"لا توجد مهام مفتوحة.","workspace.noDocs":"لا توجد مستندات بانتظار المراجعة.","workspace.noIntake":"لا توجد تقييمات مفتوحة.","workspace.loading":"استعادة مساحة العمل القانونية","workspace.loadingDetail":"جارٍ تحديد المكتب النشط والدور وقوائم العمل…","workspace.unavailable":"مساحة العمل غير متاحة",
  "studio.eyebrow":"استوديو المكتب","studio.title":"صمّم طريقة عمل المكتب","studio.summary":"شكّل الهوية والنماذج والتصنيف القانوني وسير العمل وسياسات التفاعل وسلوك الذكاء الاصطناعي.","studio.identity":"الهوية والعلامة","studio.ways":"طرق العمل","studio.legal":"المعلمات القانونية","studio.workflows":"سير العمل الموصى به","studio.forms":"النماذج والمستندات","studio.ai":"الخصوصية والتفاعل والذكاء الاصطناعي","studio.language":"لغة المنتج","studio.languageHelp":"اختر لغة الواجهة على هذا الجهاز.",
  "matter.caseStudio":"استوديو القضية","matter.workroom":"غرفة العمل","matter.economics":"الاقتصاد والوقت","matter.firmWorkspace":"مساحة المكتب","room.canonical":"الغرفة القانونية الأساسية","room.control":"التحكم المهني","room.reasoning":"التحليل والمسائل","room.evidence":"الأدلة والمصدر","room.decisions":"القرارات المهنية","room.client":"موقف العميل","room.execution":"التنفيذ","room.handoffs":"التسليم المهني","room.deep":"الاستراتيجية والذكاء والمصادر والذاكرة المؤسسية","workroom.title":"غرفة العمل","workroom.back":"العودة إلى غرفة العمل","workroom.responsible":"المسؤول","workroom.unassigned":"غير معين","workroom.teamConversation":"محادثة الفريق","workroom.noComments":"لا توجد تعليقات بعد.","workroom.post":"نشر التحديث","workroom.posting":"جارٍ النشر…","workroom.execution":"حالة التنفيذ","workroom.noDeadline":"لا يوجد موعد نهائي.","workroom.status":"الحالة","workroom.open":"مفتوح","workroom.inProgress":"قيد التنفيذ","workroom.waiting":"في الانتظار","workroom.review":"مراجعة","workroom.completed":"مكتمل","workroom.cancelled":"ملغى","workroom.conversation":"محادثة","workroom.aiReview":"مراجعة الذكاء الاصطناعي","workroom.share":"رابط مراجعة خارجية","workroom.send":"إرسال","workroom.start":"ابدأ المحادثة."
};

const sw: Dict = {
  "menu.home":"Nyumbani","menu.matters":"Kazi za Kisheria","menu.clients":"Wateja","menu.knowledge":"Maarifa na Nyaraka","menu.office":"Ofisi na Fedha","menu.firm":"Mipangilio ya Kampuni",
  "common.search":"Tafuta","common.communications":"Mawasiliano","common.notifications":"Arifa","common.open":"Fungua","common.close":"Funga","common.retry":"Jaribu tena",
  "nav.command":"Uongozi","nav.search":"Utafutaji","nav.clients":"Wateja","nav.cases":"Kesi","nav.workroom":"Chumba cha kazi","nav.reports":"Ripoti ya kazi","nav.intake":"Mapokezi na Due Diligence","nav.comms":"Mawasiliano","nav.interactions":"Mwingiliano","nav.whatsapp":"Dawati la WhatsApp","nav.forms":"Benki ya fomu","nav.documents":"Benki ya nyaraka","nav.law":"Benki ya sheria","nav.business":"Biashara na Ofisi","nav.finance":"Malipo na Fedha","nav.digitisation":"Uwekaji dijitali","nav.people":"Watu","nav.storage":"Hifadhi na Miunganisho","nav.control":"Udhibiti wa kampuni","nav.studio":"Studio ya kampuni",
  "workspace.activeFirm":"Kampuni hai","workspace.legalWorkspace":"Eneo la uendeshaji wa sheria","workspace.activeCases":"Kesi hai","workspace.urgentWork":"Kazi ya dharura","workspace.openIntake":"Mapokezi wazi","workspace.highRisk":"Hatari kubwa","workspace.caseCommand":"Uongozi wa kesi","workspace.workDue":"Kazi inayodaiwa","workspace.draftingReview":"Uandishi na ukaguzi","workspace.clientCycle":"Mzunguko wa mteja","workspace.noCases":"Hakuna kesi zinazopatikana.","workspace.noWork":"Hakuna kazi wazi.","workspace.noDocs":"Hakuna nyaraka zinazosubiri ukaguzi.","workspace.noIntake":"Hakuna tathmini wazi.","workspace.loading":"Inarejesha eneo la sheria","workspace.loadingDetail":"Inatafuta kampuni hai, jukumu na foleni za kazi…","workspace.unavailable":"Eneo halipatikani",
  "studio.eyebrow":"Studio ya kampuni","studio.title":"Buni jinsi kampuni inavyofanya kazi","studio.summary":"Unda utambulisho, fomu, taxonomia ya sheria, mtiririko wa kazi, sera za mwingiliano na tabia ya AI.","studio.identity":"Utambulisho na Chapa","studio.ways":"Njia za kufanya kazi","studio.legal":"Vigezo vya sheria","studio.workflows":"Mtiririko uliopendekezwa","studio.forms":"Fomu na Nyaraka","studio.ai":"Faragha, Mwingiliano na AI","studio.language":"Lugha ya bidhaa","studio.languageHelp":"Chagua lugha ya kiolesura kwenye kifaa hiki.",
  "matter.caseStudio":"Studio ya kesi","matter.workroom":"Chumba cha kazi","matter.economics":"Uchumi na muda","matter.firmWorkspace":"Eneo la kampuni","room.canonical":"Chumba kikuu cha kesi","room.control":"Udhibiti wa kitaalamu","room.reasoning":"Hoja na masuala","room.evidence":"Ushahidi na chanzo","room.decisions":"Maamuzi ya kitaalamu","room.client":"Msimamo wa mteja","room.execution":"Utekelezaji","room.handoffs":"Makabidhiano ya kitaalamu","room.deep":"Mkakati, akili, vyanzo na kumbukumbu ya taasisi","workroom.title":"Chumba cha kazi","workroom.back":"Rudi kwenye chumba cha kazi","workroom.responsible":"Mhusika","workroom.unassigned":"Haijapangiwa","workroom.teamConversation":"Mazungumzo ya timu","workroom.noComments":"Hakuna maoni bado.","workroom.post":"Tuma sasisho","workroom.posting":"Inatuma…","workroom.execution":"Hali ya utekelezaji","workroom.noDeadline":"Hakuna tarehe ya mwisho.","workroom.status":"Hali","workroom.open":"Wazi","workroom.inProgress":"Inaendelea","workroom.waiting":"Inasubiri","workroom.review":"Ukaguzi","workroom.completed":"Imekamilika","workroom.cancelled":"Imeghairiwa","workroom.conversation":"Mazungumzo","workroom.aiReview":"Ukaguzi wa AI","workroom.share":"Kiungo cha ukaguzi wa nje","workroom.send":"Tuma","workroom.start":"Anza mazungumzo."
};

const dictionaries: Record<Locale,Dict> = {en,fr,es,pt,ar,sw};
export function normalizeLocale(value?:string|null):Locale {
  const base=(value||"").toLowerCase().split(/[-_]/)[0] as Locale;
  return supportedLocales.includes(base)?base:"en";
}
export function t(locale:Locale,key:string,fallback?:string){
  return dictionaries[locale][key] ?? dictionaries.en[key] ?? fallback ?? key;
}
export function formatMoney(locale:Locale,value:number,currency="XAF"){
  return new Intl.NumberFormat(localeMeta[locale].intl,{style:"currency",currency,maximumFractionDigits:currency==="XAF"?0:2}).format(value||0);
}
export function formatDate(locale:Locale,value:string|Date,options:Intl.DateTimeFormatOptions={dateStyle:"medium"}){
  const date=value instanceof Date?value:new Date(value);
  return Number.isNaN(date.getTime())?"":new Intl.DateTimeFormat(localeMeta[locale].intl,options).format(date);
}
