"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, FileBadge2, Loader2, Save, ShieldCheck } from "lucide-react";

type Style={id:string;document_kind:string;label:string;header_mode:string;footer_mode:string;show_logo:boolean;show_matter_reference:boolean;show_confidentiality:boolean;signature_mode:string;configuration:Record<string,unknown>};
type Brand={display_name?:string;legal_name?:string;logo_display_url?:string;document_header_html?:string;document_footer_html?:string;email_signature_html?:string;document_identity?:Record<string,unknown>};
type Payload={success?:boolean;brand?:Brand;styles?:Style[];error?:string};

export default function DocumentIdentityPage(){
 const[brand,setBrand]=useState<Brand>({});const[styles,setStyles]=useState<Style[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/firm/document-identity",{cache:"no-store",credentials:"include"});const p=await r.json() as Payload;if(!r.ok||!p.success)throw new Error(p.error||"Unable to load document identity.");setBrand(p.brand??{});setStyles(p.styles??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load document identity.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function saveBrand(){setBusy("brand");setMessage(null);setError(null);try{const r=await fetch("/api/firm/document-identity",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"brand",documentHeaderHtml:brand.document_header_html||"",documentFooterHtml:brand.document_footer_html||"",emailSignatureHtml:brand.email_signature_html||"",documentIdentity:brand.document_identity||{}})});const p=await r.json() as Payload;if(!r.ok||!p.success)throw new Error(p.error||"Unable to save firm document identity.");setMessage("Firm document identity saved.")}catch(e){setError(e instanceof Error?e.message:"Unable to save document identity.")}finally{setBusy(null)}}
 async function saveStyle(style:Style){setBusy(style.document_kind);setMessage(null);setError(null);try{const r=await fetch("/api/firm/document-identity",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentKind:style.document_kind,headerMode:style.header_mode,footerMode:style.footer_mode,showLogo:style.show_logo,showMatterReference:style.show_matter_reference,showConfidentiality:style.show_confidentiality,signatureMode:style.signature_mode,configuration:style.configuration})});const p=await r.json() as Payload;if(!r.ok||!p.success)throw new Error(p.error||"Unable to save document rule.");setMessage(`${style.label} identity saved.`)}catch(e){setError(e instanceof Error?e.message:"Unable to save document rule.")}finally{setBusy(null)}}
 function changeStyle(kind:string,patch:Partial<Style>){setStyles(current=>current.map(item=>item.document_kind===kind?{...item,...patch}:item))}
 return <main className="min-h-screen px-4 py-6 md:px-7 xl:px-10"><div className="mx-auto max-w-7xl space-y-5">
  <Link href="/firm-control" className="inline-flex items-center gap-2 text-xs font-bold text-slate-500"><ArrowLeft className="h-4 w-4"/>Firm Control</Link>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex items-start gap-4"><div className="rounded-2xl bg-[var(--firm-primary)] p-3 text-white"><FileBadge2 className="h-5 w-5"/></div><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-slate-400">Firm document identity</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">One identity, intelligently applied</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">Set the official letterhead, footer and communication signature once. Then decide how strongly that identity appears on court documents, correspondence, reports, invoices, receipts, internal memos, external review and physical case labels.</p></div></div></section>
  {message?<div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}</div>:null}{error?<div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>:null}
  {loading?<div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[var(--firm-primary)]"/></div>:<>
   <section className="grid gap-5 xl:grid-cols-[1fr_.9fr]">
    <div className="rounded-[1.8rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-slate-400">Official identity source</p><h2 className="mt-1 text-xl font-semibold">Header, footer & signatures</h2></div><button onClick={()=>void saveBrand()} disabled={busy!==null} className="inline-flex items-center gap-2 rounded-xl bg-[var(--firm-primary)] px-4 py-2.5 text-xs font-bold text-white"><Save className="h-4 w-4"/>{busy==="brand"?"Saving…":"Save"}</button></div>
     <div className="mt-5 space-y-4"><Field label="Document header / letterhead"><textarea value={brand.document_header_html||""} onChange={e=>setBrand(v=>({...v,document_header_html:e.target.value}))} rows={6} className="input" placeholder="Firm name, offices, contacts, professional details…"/></Field><Field label="Official footer"><textarea value={brand.document_footer_html||""} onChange={e=>setBrand(v=>({...v,document_footer_html:e.target.value}))} rows={5} className="input" placeholder="Legal notice, addresses, registration details, confidentiality wording…"/></Field><Field label="Email / message signature"><textarea value={brand.email_signature_html||""} onChange={e=>setBrand(v=>({...v,email_signature_html:e.target.value}))} rows={5} className="input" placeholder="Lawyer name, title, firm, phone, email, disclaimer…"/></Field></div>
    </div>
    <div className="rounded-[1.8rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.15em] text-slate-400">Preview logic</p><h2 className="mt-1 text-xl font-semibold">Firm identity follows the context</h2><div className="mt-5 rounded-[1.4rem] border border-slate-200 bg-[var(--firm-background)] p-5"><div className="flex items-center gap-3">{brand.logo_display_url?<img src={brand.logo_display_url} alt="Firm logo" className="h-14 w-14 rounded-xl bg-white object-contain p-2 shadow-sm"/>:<div className="grid h-14 w-14 place-items-center rounded-xl bg-white shadow-sm"><ShieldCheck className="h-5 w-5 text-[var(--firm-primary)]"/></div>}<div><p className="text-lg font-semibold">{brand.display_name||brand.legal_name||"Your Firm"}</p><p className="text-xs text-slate-500">Official document identity</p></div></div><div className="mt-5 border-y border-slate-200 py-5 text-sm leading-6 text-slate-600">The body of the legal document remains readable and restrained. Branding frames the work rather than overpowering it.</div><p className="mt-4 text-xs text-slate-400">Footer and confidentiality treatment adapt by document type.</p></div></div>
   </section>
   <section className="rounded-[1.8rem] border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-slate-400">Context rules</p><h2 className="mt-1 text-xl font-semibold">How identity appears by document type</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{styles.map(style=><article key={style.document_kind} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{style.label}</h3><p className="mt-1 text-[10px] uppercase tracking-[.12em] text-slate-400">{style.document_kind.replaceAll("_"," ")}</p></div><button disabled={busy!==null} onClick={()=>void saveStyle(style)} className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-bold">{busy===style.document_kind?"Saving…":"Save rule"}</button></div><div className="mt-4 grid grid-cols-2 gap-3"><Select label="Header" value={style.header_mode} onChange={value=>changeStyle(style.document_kind,{header_mode:value})} options={["full","compact","none"]}/><Select label="Footer" value={style.footer_mode} onChange={value=>changeStyle(style.document_kind,{footer_mode:value})} options={["legal","compact","none"]}/><Select label="Signature" value={style.signature_mode} onChange={value=>changeStyle(style.document_kind,{signature_mode:value})} options={["lawyer","firm","none"]}/><div className="space-y-2 pt-1"><Check label="Logo" checked={style.show_logo} onChange={value=>changeStyle(style.document_kind,{show_logo:value})}/><Check label="Matter ref." checked={style.show_matter_reference} onChange={value=>changeStyle(style.document_kind,{show_matter_reference:value})}/><Check label="Confidentiality" checked={style.show_confidentiality} onChange={value=>changeStyle(style.document_kind,{show_confidentiality:value})}/></div></div></article>)}</div></section>
  </>}
 </div><style jsx>{`.input{margin-top:.5rem;width:100%;border:1px solid #e2e8f0;border-radius:1rem;background:white;padding:.85rem 1rem;font-size:.875rem;outline:none}.input:focus{border-color:var(--firm-primary)}`}</style></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-[9px] font-black uppercase tracking-[.14em] text-slate-500">{label}</span>{children}</label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label><span className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">{options.map(o=><option key={o} value={o}>{o.replaceAll("_"," ")}</option>)}</select></label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
