"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileUp, ShieldCheck, Sparkles } from "lucide-react";

export default function FormImportPage(){
 const[file,setFile]=useState<File|null>(null); const[busy,setBusy]=useState(false); const[message,setMessage]=useState(""); const[result,setResult]=useState<{id:string;name:string;module:string;status:string;schema?:{fields?:unknown[]}}|null>(null); const[warnings,setWarnings]=useState<string[]>([]);
 async function submit(event:FormEvent){event.preventDefault();if(!file)return;setBusy(true);setMessage("");setResult(null);setWarnings([]);try{const body=new FormData();body.append("file",file);const response=await fetch("/api/forms/import",{method:"POST",credentials:"include",body});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.error||"Unable to import form.");setResult(payload.form);setWarnings(payload.warnings||[]);setMessage("Draft form created from the uploaded source. Review and edit it before publishing.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to import form.")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-7"><div className="mx-auto max-w-4xl space-y-5">
  <Link href="/forms" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Forms Bank</Link>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-8"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">Form Bank Import</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Turn an existing office form into an editable TSIDKENU draft.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Upload a PDF, Word document, image or text source. TSIDKENU preserves the original in the secure vault, extracts proposed fields, and creates a draft that must be reviewed before publication.</p></section>
  <form onSubmit={submit} className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
   <div className="flex items-start gap-3"><div className="rounded-xl bg-[#edf4f0] p-3 text-[#0f5b49]"><FileUp className="h-5 w-5"/></div><div><h2 className="text-xl font-semibold">Upload existing form</h2><p className="mt-1 text-sm text-slate-500">Maximum 15 MB. The source is not auto-published or treated as a final legal template.</p></div></div>
   <label className="mt-6 block cursor-pointer rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center transition hover:border-[#7da797]"><FileUp className="mx-auto h-8 w-8 text-slate-400"/><p className="mt-3 text-sm font-bold">{file?file.name:"Choose PDF, DOCX, image or text file"}</p><p className="mt-1 text-xs text-slate-400">{file?Math.round(file.size/1024)+" KB":"Click to browse"}</p><input type="file" className="sr-only" accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
   <div className="mt-5 flex items-center justify-between gap-4"><p className="max-w-xl text-xs leading-5 text-slate-500"><ShieldCheck className="mr-1 inline h-4 w-4 text-[#0f5b49]"/>The original file path and extraction provider/model are stored as provenance. A human must review the extracted structure.</p><button disabled={!file||busy} className="inline-flex items-center gap-2 rounded-xl bg-[#082b22] px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><Sparkles className="h-4 w-4"/>{busy?"Extracting…":"Create draft form"}</button></div>
  </form>
  {message&&<div className={"rounded-2xl border bg-white p-4 text-sm "+(result?"border-emerald-200 text-emerald-800":"border-amber-200 text-amber-800")}>{message}</div>}
  {result&&<section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#0f5b49]">Imported draft</p><h2 className="mt-1 text-2xl font-semibold">{result.name}</h2><p className="mt-2 text-sm text-slate-500">{result.module} · {result.status} · {Array.isArray(result.schema?.fields)?result.schema?.fields.length:0} extracted fields</p>{warnings.length>0&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800"><p className="font-bold">Extraction warnings</p><ul className="mt-2 list-disc space-y-1 pl-5">{warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></div>}<div className="mt-5 flex flex-wrap gap-2"><Link href={"/studio/forms/"+result.id} className="rounded-xl bg-[#0b493b] px-4 py-2.5 text-sm font-bold text-white">Review & edit draft</Link><Link href="/forms" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Back to Forms Bank</Link></div></section>}
 </div></main>
}
