"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Banknote,Clock3,Play,Square,TimerReset,TrendingUp} from "lucide-react";
type Matter={id:string;title:string;client_name:string;case_reference:string;opened_at?:string|null;created_at:string;status:string};
type TimeEntry={id:string;description:string;activity_type:string;minutes:number;billable:boolean;billing_status:string;hourly_rate_xaf?:number|null;started_at?:string|null;ended_at?:string|null;created_at:string};
type Expense={id:string;description:string;amount_xaf:number;recoverable:boolean;status:string;expense_date:string};
type Invoice={id:string;invoice_number?:string|null;amount_xaf:number;paid_xaf:number;status:string;created_at:string};
type Payload={success:boolean;error?:string;matter?:Matter;timeEntries?:TimeEntry[];expenses?:Expense[];invoices?:Invoice[];runningTimer?:TimeEntry|null;metrics?:Record<string,number>};
const money=(n:number)=>new Intl.NumberFormat("fr-CM",{maximumFractionDigits:0}).format(Number(n||0))+" XAF";
export default function CaseAccountingPage({params}:{params:Promise<{matterId:string}>}){
 const[id,setId]=useState("");const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[activity,setActivity]=useState("legal_work");const[description,setDescription]=useState("");const[rate,setRate]=useState("");const[minutes,setMinutes]=useState("");const[billable,setBillable]=useState(true);
 useEffect(()=>{void params.then(x=>setId(x.matterId))},[params]);
 async function load(){if(!id)return;const r=await fetch("/api/matters/"+id+"/accounting",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load case accounting.");setData(p)}
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:"Unable to load case accounting."))},[id]);
 async function action(body:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch("/api/matters/"+id+"/accounting",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Action failed.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Action failed.")}finally{setBusy(false)}}
 async function addManual(e:FormEvent){e.preventDefault();await action({action:"add_time",activityType:activity,description:description||"Legal work",minutes:Number(minutes),hourlyRateXaf:rate?Number(rate):null,billable});setDescription("");setMinutes("")}
 const m=data?.metrics||{};const matter=data?.matter;
 if(!data&&!message)return <main className="min-h-screen bg-[#eef2ef] p-6 text-slate-500">Loading case economics…</main>;
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-7"><div className="mx-auto max-w-[1500px] space-y-5">
  <Link href={id?"/matters/"+id:"#"} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Case room</Link>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-9"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">{matter?.case_reference||"Case"} · economics</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">{matter?.title||"Case economics"}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Case age is automatic. Billable time is deliberate. Expenses and invoices remain separate evidence-backed records, then combine into a defensible commercial view.</p></section>
  {message&&<div className="rounded-xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Case age" value={String(m.ageDays||0)+" days"}/><Metric label="Billable time" value={Math.floor((m.billableMinutes||0)/60)+"h "+((m.billableMinutes||0)%60)+"m"}/><Metric label="Recoverable expenses" value={money(m.recoverableExpensesXaf||0)}/><Metric label="Outstanding" value={money(m.outstandingXaf||0)}/></section>
  <section className="grid gap-5 xl:grid-cols-[1fr_420px]">
   <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Working time</p><h2 className="text-xl font-semibold">Case timer & time register</h2></div><Clock3 className="h-5 w-5 text-[#0f5b49]"/></div>
    {data?.runningTimer?<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-emerald-50 p-4"><div><p className="text-sm font-bold text-emerald-900">Timer running</p><p className="mt-1 text-xs text-emerald-700">{data.runningTimer.description} · started {data.runningTimer.started_at?new Date(data.runningTimer.started_at).toLocaleTimeString():"now"}</p></div><button disabled={busy} onClick={()=>void action({action:"stop_timer",id:data.runningTimer?.id})} className="inline-flex items-center gap-2 rounded-xl bg-emerald-950 px-4 py-2.5 text-sm font-bold text-white"><Square className="h-4 w-4"/>Stop & record</button></div>:<div className="mt-4 flex flex-wrap items-end gap-3 rounded-xl bg-slate-50 p-4"><label className="min-w-44 flex-1"><span className="text-[10px] font-bold uppercase text-slate-400">Activity</span><select value={activity} onChange={e=>setActivity(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="consultation">Consultation</option><option value="research">Research</option><option value="drafting">Drafting</option><option value="hearing">Hearing</option><option value="meeting">Meeting</option><option value="call">Call</option><option value="legal_work">Other legal work</option></select></label><label className="min-w-48 flex-[2]"><span className="text-[10px] font-bold uppercase text-slate-400">Description</span><input value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm" placeholder="What are you working on?"/></label><button disabled={busy} onClick={()=>void action({action:"start_timer",activityType:activity,description:description||"Case work",hourlyRateXaf:rate?Number(rate):null,billable})} className="inline-flex items-center gap-2 rounded-xl bg-[#082b22] px-4 py-2.5 text-sm font-bold text-white"><Play className="h-4 w-4"/>Start timer</button></div>}
    <div className="mt-4 space-y-2">{(data?.timeEntries??[]).slice(0,30).map(x=><div key={x.id} className="grid gap-2 rounded-xl border border-slate-100 p-3 sm:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-semibold">{x.description}</p><p className="mt-1 text-[11px] text-slate-400">{x.activity_type.replaceAll("_"," ")} · {new Date(x.created_at).toLocaleDateString()}</p></div><p className="text-xs font-bold">{x.minutes} min</p><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black uppercase">{x.billing_status.replaceAll("_"," ")}</span></div>)}</div>
   </div>
   <aside className="space-y-5"><div className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><Banknote className="h-5 w-5 text-[#0f5b49]"/><p className="mt-4 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Draft billing basis</p><p className="mt-2 text-3xl font-semibold">{money(m.draftBillBasisXaf||0)}</p><div className="mt-4 space-y-2 text-xs text-slate-500"><p>Unbilled time: {m.unbilledMinutes||0} minutes</p><p>Rated time value: {money(m.unbilledTimeValueXaf||0)}</p><p>Recoverable expenses: {money(m.recoverableExpensesXaf||0)}</p><p>Already billed: {money(m.billedXaf||0)}</p><p>Paid: {money(m.paidXaf||0)}</p></div><Link href="/finance" className="mt-5 block rounded-xl bg-[#082b22] px-4 py-2.5 text-center text-sm font-bold text-white">Open Billing & Finance</Link></div>
    <form onSubmit={addManual} className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><TimerReset className="h-5 w-5 text-[#0f5b49]"/><h3 className="mt-3 font-semibold">Add time manually</h3><div className="mt-3 space-y-2"><input required value={description} onChange={e=>setDescription(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Description"/><div className="grid grid-cols-2 gap-2"><input required inputMode="numeric" value={minutes} onChange={e=>setMinutes(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Minutes"/><input inputMode="numeric" value={rate} onChange={e=>setRate(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Hourly rate XAF"/></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={billable} onChange={e=>setBillable(e.target.checked)}/>Billable</label><button disabled={busy} className="w-full rounded-xl border border-[#0b493b] px-4 py-2.5 text-sm font-bold text-[#0b493b]">Add time</button></div></form>
   </aside>
  </section>
 </div></main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-4 shadow-sm"><TrendingUp className="h-4 w-4 text-[#0f5b49]"/><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-[.13em] text-slate-400">{label}</p></div>}
