"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, GitBranch, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";

type Stage={id:string;stage_key:string;name:string;description?:string|null;sort_order:number;stage_type:string;sla_hours?:number|null;required_roles:string[];is_terminal:boolean};
type Transition={id:string;from_stage_key:string;to_stage_key:string;name:string;allowed_roles:string[];requires_reason:boolean;requires_approval:boolean;approval_roles:string[];active:boolean};
type Workflow={id:string;workflow_key:string;name:string;description?:string|null;status:string;version:number;stages:Stage[];transitions:Transition[]};
type Payload={success:boolean;error?:string;workflows?:Workflow[]};
const field="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";
const roles=["owner","partner","lawyer","paralegal","intern","administrator","finance","clerk","knowledge_manager"];
type Preset={key:string;name:string;description:string;subjectType:string;stages:Array<{key:string;name:string;type:string}>};
const recommendedPresets:Preset[]=[
 {key:"recommended_client_intake",name:"Client Intake & Due Diligence",description:"Enquiry → conflict → KYC → consultation → approval → engagement.",subjectType:"prospect",stages:[{key:"enquiry",name:"Enquiry",type:"work"},{key:"conflict",name:"Conflict check",type:"gate"},{key:"kyc",name:"KYC & due diligence",type:"gate"},{key:"consultation",name:"Consultation",type:"work"},{key:"approval",name:"Acceptance approval",type:"review"},{key:"engagement",name:"Engagement",type:"gate"},{key:"converted",name:"Client / case opened",type:"closure"}]},
 {key:"recommended_litigation",name:"Litigation Case",description:"Instructions → investigation → pre-action → filing → hearing → judgment → enforcement → closure.",subjectType:"matter",stages:[{key:"instructions",name:"Instructions",type:"work"},{key:"investigation",name:"Investigation",type:"work"},{key:"pre_action",name:"Pre-action",type:"review"},{key:"filing",name:"Filing",type:"gate"},{key:"hearing",name:"Hearing",type:"work"},{key:"judgment",name:"Judgment",type:"review"},{key:"enforcement",name:"Enforcement",type:"work"},{key:"closure",name:"Closure",type:"closure"}]},
 {key:"recommended_billing",name:"Billing & Collection",description:"Work captured → draft bill → review → invoice → payment → receipt → reconciliation.",subjectType:"billing",stages:[{key:"work_captured",name:"Work captured",type:"work"},{key:"draft_bill",name:"Draft bill",type:"finance"},{key:"review",name:"Review",type:"review"},{key:"invoice",name:"Invoice sent",type:"finance"},{key:"payment",name:"Payment",type:"finance"},{key:"receipt",name:"Receipt",type:"finance"},{key:"reconciled",name:"Reconciled",type:"closure"}]},
 {key:"recommended_expense",name:"Office Expense & Receipt",description:"Record → receipt check → approval → accounting → complete.",subjectType:"expense",stages:[{key:"recorded",name:"Recorded",type:"work"},{key:"receipt_check",name:"Receipt check",type:"gate"},{key:"approval",name:"Approval",type:"review"},{key:"accounting",name:"Accounting",type:"finance"},{key:"complete",name:"Complete",type:"closure"}]},
 {key:"recommended_document",name:"Document Approval",description:"Draft → internal review → approval → client review → final → filed/signed → archive.",subjectType:"document",stages:[{key:"draft",name:"Draft",type:"work"},{key:"internal_review",name:"Internal review",type:"review"},{key:"approval",name:"Approval",type:"review"},{key:"client_review",name:"Client review",type:"review"},{key:"final",name:"Final",type:"work"},{key:"filed_signed",name:"Filed / signed",type:"gate"},{key:"archived",name:"Archived",type:"closure"}]}
];

export default function WorkflowStudio(){
 const [data,setData]=useState<Payload|null>(null);const [selectedId,setSelectedId]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/firm/workflows",{cache:"no-store"});const d=await r.json();setData(d);if(d.success&&!selectedId&&d.workflows?.length)setSelectedId(d.workflows[0].id);if(!d.success)setMessage(d.error||"Unable to load workflows");},[selectedId]);
 useEffect(()=>{void load();},[load]);
 const workflow=useMemo(()=>data?.workflows?.find(w=>w.id===selectedId)||data?.workflows?.[0]||null,[data,selectedId]);
 async function patch(body:Record<string,unknown>){if(!workflow)return;setBusy(true);setMessage("");try{const r=await fetch(`/api/firm/workflows/${workflow.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"Workflow update failed");setMessage("Workflow structure saved.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Workflow update failed");}finally{setBusy(false);}}
 async function remove(kind:"stage"|"transition",id:string){if(!workflow)return;setBusy(true);try{const r=await fetch(`/api/firm/workflows/${workflow.id}?kind=${kind}&id=${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"Delete failed");await load();}catch(e){setMessage(e instanceof Error?e.message:"Delete failed");}finally{setBusy(false);}}
 async function applyPreset(preset:Preset){
  setBusy(true);setMessage("");
  try{
   const create=await fetch("/api/firm/workflows",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:preset.name,workflowKey:preset.key,subjectType:preset.subjectType,description:preset.description,status:"draft",configuration:{mode:"recommended",preset:preset.key}})});
   const created=await create.json();
   if(!create.ok||!created.success||!created.workflow?.id)throw new Error(created.error||"Unable to create recommended workflow.");
   const id=created.workflow.id as string;
   for(let i=0;i<preset.stages.length;i++){
    const stage=preset.stages[i];
    const response=await fetch(`/api/firm/workflows/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"stage",stageKey:stage.key,name:stage.name,stageType:stage.type,sortOrder:(i+1)*10,isTerminal:i===preset.stages.length-1})});
    const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||"Unable to create workflow stage.");
    if(i>0){
     const previous=preset.stages[i-1];
     const transition=await fetch(`/api/firm/workflows/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"transition",fromStageKey:previous.key,toStageKey:stage.key,name:`${previous.name} → ${stage.name}`,allowedRoles:roles,requiresApproval:stage.type==="review",approvalRoles:stage.type==="review"?["owner","partner"]:[],sortOrder:i*10})});
     const transitionResult=await transition.json();if(!transition.ok||!transitionResult.success)throw new Error(transitionResult.error||"Unable to create workflow transition.");
    }
   }
   const activate=await fetch(`/api/firm/workflows/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"workflow",status:"active",configuration:{mode:"recommended",preset:preset.key}})});
   const activated=await activate.json();if(!activate.ok||!activated.success)throw new Error(activated.error||"Unable to activate recommended workflow.");
   setSelectedId(id);setMessage("Recommended workflow created. You can now customize stages, roles and approvals.");await load();
  }catch(e){setMessage(e instanceof Error?e.message:"Unable to apply recommended workflow.");}finally{setBusy(false);}
 }
 if(!data)return <main className="min-h-screen bg-slate-50 p-6 text-slate-600">Loading workflow studio…</main>;
 return <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc,#eef3f1)] px-4 py-6 md:px-6"><div className="mx-auto max-w-[1500px] space-y-5">
  <header className="rounded-[2rem] bg-[#083126] p-6 text-white"><Link href="/studio" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-white/60"><ArrowLeft className="h-4 w-4"/>Firm Studio</Link><div className="mt-5 flex items-start gap-3"><div className="rounded-2xl bg-white/10 p-3"><GitBranch className="h-6 w-6"/></div><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-white/50">Workflow Studio</p><h1 className="mt-1 text-3xl font-semibold">Design how the firm actually works</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-white/70">Stages, role ownership, gates, approvals and permitted moves are editable here; the matter room runs from this structure rather than hard-coded UI labels.</p></div></div></header>
  <section className="rounded-[1.6rem] border border-emerald-900/10 bg-white p-5 shadow-sm">
   <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-emerald-800">Recommended setup</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">Start simple; customize only what the firm needs.</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">Choose a tested operating pattern below. TSIDKENU creates the stages and transitions as a real workflow; the editors underneath remain the Advanced layer.</p></div><div className="rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-900">Recommended → Customize → Advanced</div></div>
   <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{recommendedPresets.map(preset=><button key={preset.key} disabled={busy} onClick={()=>void applyPreset(preset)} className="rounded-2xl border border-slate-200 bg-[#fbfcfb] p-4 text-left transition hover:border-emerald-400 disabled:opacity-50"><p className="text-sm font-bold text-slate-900">{preset.name}</p><p className="mt-2 text-xs leading-5 text-slate-500">{preset.description}</p><p className="mt-3 text-[9px] font-black uppercase tracking-[0.12em] text-emerald-800">{preset.subjectType} workflow</p></button>)}</div>
  </section>
  {message?<div className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>:null}
  <div className="grid gap-5 xl:grid-cols-[260px_1fr]">
   <aside className="rounded-[1.6rem] border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Workflows</p><div className="mt-3 space-y-2">{(data.workflows||[]).map(w=><button key={w.id} onClick={()=>setSelectedId(w.id)} className={`w-full rounded-xl px-3 py-3 text-left ${workflow?.id===w.id?"bg-emerald-950 text-white":"bg-slate-50 text-slate-700"}`}><p className="text-sm font-bold">{w.name}</p><p className="mt-1 text-[10px] uppercase opacity-60">v{w.version} · {w.status}</p></button>)}</div></aside>
   {workflow?<section className="space-y-5">
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Active structure</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">{workflow.name}</h2><p className="mt-2 text-sm text-slate-600">{workflow.description||"No description."}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase text-emerald-800">{workflow.status}</span></div>
      <div className="mt-5 overflow-x-auto"><div className="flex min-w-[800px] items-start">{workflow.stages.map((s,i)=><div key={s.id} className="flex flex-1 items-center"><div className="min-w-[110px] text-center"><div className="mx-auto grid h-10 w-10 place-items-center rounded-full border border-emerald-800 bg-emerald-50 text-emerald-900"><ShieldCheck className="h-4 w-4"/></div><p className="mt-2 text-[10px] font-black uppercase tracking-[0.12em] text-slate-700">{s.name}</p><p className="mt-1 text-[10px] text-slate-400">{s.stage_type}</p></div>{i<workflow.stages.length-1?<div className="h-px flex-1 bg-slate-200"/>:null}</div>)}</div></div>
    </div>
    <div className="grid gap-5 2xl:grid-cols-2">
      <StageEditor workflow={workflow} busy={busy} save={patch} remove={remove}/>
      <TransitionEditor workflow={workflow} busy={busy} save={patch} remove={remove}/>
    </div>
   </section>:<section className="rounded-[1.6rem] border border-slate-200 bg-white p-6">No workflow configured.</section>}
  </div>
 </div></main>;
}

function StageEditor({workflow,busy,save,remove}:{workflow:Workflow;busy:boolean;save:(body:Record<string,unknown>)=>Promise<void>;remove:(kind:"stage"|"transition",id:string)=>Promise<void>}){
 const [editing,setEditing]=useState<Stage|null>(null);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void save({action:"stage",stageKey:f.get("stageKey"),name:f.get("name"),description:f.get("description"),sortOrder:Number(f.get("sortOrder")),stageType:f.get("stageType"),slaHours:f.get("slaHours"),requiredRoles:f.getAll("roles"),isTerminal:f.get("terminal")==="on"});setEditing(null);e.currentTarget.reset();}
 return <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Stages</p><h3 className="text-xl font-semibold text-slate-950">Operating stages</h3></div><Plus className="h-5 w-5 text-emerald-800"/></div><form onSubmit={submit} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><input name="stageKey" required defaultValue={editing?.stage_key||""} className={field} placeholder="stage_key"/><input name="name" required defaultValue={editing?.name||""} className={field} placeholder="Stage name"/><input name="sortOrder" type="number" defaultValue={editing?.sort_order??workflow.stages.length*10+10} className={field}/><select name="stageType" defaultValue={editing?.stage_type||"work"} className={field}><option value="gate">Gate</option><option value="work">Work</option><option value="review">Review</option><option value="finance">Finance</option><option value="closure">Closure</option></select><input name="slaHours" type="number" defaultValue={editing?.sla_hours??""} className={field} placeholder="SLA hours"/><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm"><input name="terminal" type="checkbox" defaultChecked={editing?.is_terminal}/>Terminal stage</label></div><textarea name="description" defaultValue={editing?.description||""} className={`${field} min-h-20`} placeholder="Stage purpose and operating meaning"/><div className="flex flex-wrap gap-2">{roles.map(r=><label key={r} className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-bold"><input className="mr-1" name="roles" value={r} type="checkbox" defaultChecked={editing?.required_roles?.includes(r)}/>{r}</label>)}</div><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-emerald-950 px-4 py-2.5 text-sm font-bold text-white"><Save className="h-4 w-4"/>{editing?"Update stage":"Add stage"}</button></form><div className="mt-5 space-y-2">{workflow.stages.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><button onClick={()=>setEditing(s)} className="text-left"><p className="text-sm font-bold text-slate-800">{s.name}</p><p className="text-xs text-slate-400">{s.stage_key} · {s.stage_type}</p></button><button disabled={busy} onClick={()=>void remove("stage",s.id)} className="text-red-500"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>;
}

function TransitionEditor({workflow,busy,save,remove}:{workflow:Workflow;busy:boolean;save:(body:Record<string,unknown>)=>Promise<void>;remove:(kind:"stage"|"transition",id:string)=>Promise<void>}){
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void save({action:"transition",fromStageKey:f.get("from"),toStageKey:f.get("to"),name:f.get("name"),allowedRoles:f.getAll("roles"),requiresReason:f.get("reason")==="on",requiresApproval:f.get("approval")==="on",approvalRoles:f.getAll("approvalRoles"),sortOrder:Number(f.get("sortOrder"))});e.currentTarget.reset();}
 return <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Transitions</p><h3 className="text-xl font-semibold text-slate-950">Allowed moves & approvals</h3></div><GitBranch className="h-5 w-5 text-emerald-800"/></div><form onSubmit={submit} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><select name="from" required className={field}><option value="">From stage</option>{workflow.stages.map(s=><option key={s.id} value={s.stage_key}>{s.name}</option>)}</select><select name="to" required className={field}><option value="">To stage</option>{workflow.stages.map(s=><option key={s.id} value={s.stage_key}>{s.name}</option>)}</select><input name="name" required className={field} placeholder="Transition label"/><input name="sortOrder" type="number" defaultValue={workflow.transitions.length*10+10} className={field}/></div><div className="flex gap-4"><label className="text-sm"><input name="reason" type="checkbox" className="mr-2"/>Require reason</label><label className="text-sm"><input name="approval" type="checkbox" className="mr-2"/>Require approval role</label></div><p className="text-[10px] font-black uppercase text-slate-400">Allowed roles</p><div className="flex flex-wrap gap-2">{roles.map(r=><label key={r} className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-bold"><input className="mr-1" name="roles" value={r} type="checkbox"/>{r}</label>)}</div><p className="text-[10px] font-black uppercase text-slate-400">Approval roles</p><div className="flex flex-wrap gap-2">{roles.map(r=><label key={r} className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-bold"><input className="mr-1" name="approvalRoles" value={r} type="checkbox"/>{r}</label>)}</div><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-emerald-950 px-4 py-2.5 text-sm font-bold text-white"><Save className="h-4 w-4"/>Save transition</button></form><div className="mt-5 space-y-2">{workflow.transitions.map(t=><div key={t.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-bold text-slate-800">{t.name}</p><p className="text-xs text-slate-400">{t.from_stage_key} → {t.to_stage_key}{t.requires_approval?" · approval":""}</p></div><button disabled={busy} onClick={()=>void remove("transition",t.id)} className="text-red-500"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>;
}
