import Link from "next/link";
import { ArrowRight, Building2, FileBadge2, GitBranch, Palette, Scale, Settings2, ShieldCheck, UsersRound } from "lucide-react";

const cards=[
 {href:"/studio#identity-brand",title:"Identity & Brand",text:"Logo, palette, naming and client-facing visual identity.",icon:Palette},
 {href:"/firm-control/document-identity",title:"Document Identity",text:"Letterhead, footer, signatures and context-specific document presentation.",icon:FileBadge2},
 {href:"/firm-control/ways-of-working",title:"Ways of Working",text:"Firm profile, recommended setup and adopted operating rules.",icon:Settings2},
 {href:"/firm-control/governance",title:"Governance",text:"Protected approvals, destructive-record decisions and authority controls.",icon:ShieldCheck},
 {href:"/studio/access",title:"People & Authority",text:"Invite members and assign governed firm roles.",icon:UsersRound},
 {href:"/studio/workflows",title:"Workflow Design",text:"Stages, approvals and transition rules when the firm needs deeper control.",icon:GitBranch},
 {href:"/studio/legal-parameters",title:"Legal Parameters",text:"Jurisdictions, courts, matter types, fees, risk and confidentiality.",icon:Scale},
 {href:"/studio",title:"Advanced Firm Control",text:"Forms, subscription modules and advanced configuration.",icon:Building2},
];

export default function FirmControlPage(){return <main className="min-h-screen px-4 py-6 md:px-7 xl:px-10"><div className="mx-auto max-w-7xl space-y-6"><section className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="grid lg:grid-cols-[1fr_360px]"><div className="p-7 md:p-9"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[var(--firm-primary)]">Firm Control</p><h1 className="mt-2 max-w-4xl text-4xl font-semibold tracking-[-.035em] text-slate-950">Make TSIDKENU operate like your firm.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-600">One place for firm identity, authority, document presentation, operating rules and legal configuration. Staff work inside the results; they should not have to think about the machinery behind them.</p></div><aside className="border-t border-slate-200 bg-[var(--firm-background)] p-6 lg:border-l lg:border-t-0"><ShieldCheck className="h-5 w-5 text-[var(--firm-primary)]"/><p className="mt-4 text-sm font-semibold text-slate-900">Governance principle</p><p className="mt-2 text-xs leading-6 text-slate-600">High-impact actions such as case removal are separated from ordinary legal permissions and routed to firm-level authority.</p></aside></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(({href,title,text,icon:Icon})=><Link key={href+title} href={href} className="group rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[var(--firm-primary)]/30 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-[var(--firm-background)] p-2.5 text-[var(--firm-primary)]"><Icon className="h-5 w-5"/></div><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-[var(--firm-primary)]"/></div><h2 className="mt-4 text-base font-semibold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></Link>)}</section></div></main>}
