"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Archive, ArrowLeft, CheckCircle2, FileSearch, Files, FolderUp, ScanLine, ShieldCheck, UploadCloud } from "lucide-react";

type Batch={id:string;title:string;source_type:string;source_location?:string|null;matter_id?:string|null;status:string;total_files:number;classified_files:number;review_required_files:number;approved_files:number;created_at:string;updated_at:string};
type Item={id:string;batch_id:string;matter_id?:string|null;original_name:string;storage_ref:string;mime_type?:string|null;file_size_bytes?:number|null;proposed_document_type?:string|null;proposed_document_date?:string|null;proposed_title?:string|null;classification_confidence?:number|null;duplicate_of_document_id?:string|null;review_status:string;metadata?:Record<string,unknown>};
type Matter={id:string;title:string;client_name?:string|null;status:string};
type Payload={success:boolean;error?:string;batches?:Batch[];items?:Item[];matters?:Matter[]};
const field="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";

export default function DigitisationPage(){
 const [data,setData]=useState<Payload>({success:true,batches:[],items:[],matters:[]});
 const [batchId,setBatchId]=useState(""); const [title,setTitle]=useState("Legacy case archive"); const [sourceType,setSourceType]=useState("legacy_archive"); const [matterId,setMatterId]=useState("");
 const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const [edit,setEdit]=useState<Record<string,{title:string;documentType:string;matterId:string}>>({});
 async function load(selected=batchId){const r=await fetch(`/api/digitisation${selected?`?batchId=${encodeURIComponent(selected)}`:""}`,{cache:"no-store"});const p=await r.json();if(!p.success)throw new Error(p.error);setData(p);}
 useEffect(()=>{load("").catch(e=>setMessage(e.message));},[]);
 useEffect(()=>{if(batchId)load(batchId).catch(e=>setMessage(e.message));},[batchId]);
 const batches=data.batches??[]; const items=data.items??[]; const matters=data.matters??[]; const selectedBatch=useMemo(()=>batches.find(b=>b.id===batchId),[batches,batchId]);
 async function upload(){if(!files.length)return;setBusy(true);setMessage("");try{const form=new FormData();files.forEach(f=>form.append("files",f));if(batchId)form.append("batchId",batchId);else{form.append("title",title);form.append("sourceType",sourceType);if(matterId)form.append("matterId",matterId);}const r=await fetch("/api/digitisation",{method:"POST",body:form});const p=await r.json();if(!p.success)throw new Error(p.error);setFiles([]);setBatchId(p.batch.id);setMessage(`${p.items.length} file(s) imported. Originals preserved; duplicates flagged.`);await load(p.batch.id);}catch(e){setMessage(e instanceof Error?e.message:"Unable to import files.");}finally{setBusy(false)}}
 async function review(item:Item,status:string){setBusy(true);setMessage("");try{const draft=edit[item.id]??{title:item.proposed_title||item.original_name,documentType:item.proposed_document_type||"Digitised document",matterId:item.matter_id||""};const r=await fetch("/api/digitisation",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:item.id,reviewStatus:status,title:draft.title,documentType:draft.documentType,matterId:draft.matterId||null})});const p=await r.json();if(!p.success)throw new Error(p.error);setMessage(status==="accepted"||status==="corrected"?"Document approved into the controlled matter record.":"Review decision recorded.");await load(item.batch_id);}catch(e){setMessage(e instanceof Error?e.message:"Unable to review file.");}finally{setBusy(false)}}
 function draft(item:Item){return edit[item.id]??{title:item.proposed_title||item.original_name,documentType:item.proposed_document_type||"Unclassified",matterId:item.matter_id||""};}
 return <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc_0%,#edf3f1_100%)] p-4 text-slate-800 md:p-6 xl:p-8"><div className="mx-auto max-w-[1700px] space-y-5">
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white shadow-xl md:p-8"><Link href="/workspace" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-white/60"><ArrowLeft className="h-4 w-4"/>Workspace</Link><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-white/50">Digitisation Desk</p><h1 className="mt-2 text-4xl font-semibold">Turn old case files into controlled digital records.</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">Import scanned folders or selected documents. TSIDKENU preserves originals, fingerprints files, flags duplicates and sends uncertain classification to human review before a document becomes part of a matter.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-xs text-white/70"><ShieldCheck className="mr-2 inline h-4 w-4"/>No OCR/AI guess becomes authoritative without confirmation.</div></div></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  <section className="grid gap-5 xl:grid-cols-[0.75fr_1.25fr]">
   <div className="space-y-5">
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><FolderUp className="h-5 w-5 text-emerald-800"/><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Create / continue batch</p><h2 className="text-xl font-semibold text-slate-950">Archive import</h2></div></div><div className="mt-4 space-y-3"><select className={field} value={batchId} onChange={e=>setBatchId(e.target.value)}><option value="">New batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.title} · {b.status}</option>)}</select>{!batchId&&<><input className={field} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Batch title"/><select className={field} value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="legacy_archive">Legacy archive</option><option value="scanner">Scanner</option><option value="folder_import">Folder import</option><option value="phone_scan">Phone scan</option><option value="manual_upload">Manual upload</option><option value="storage_connector">Storage connector</option></select><select className={field} value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">Unmatched / classify later</option>{matters.map(m=><option key={m.id} value={m.id}>{m.title}{m.client_name?` — ${m.client_name}`:""}</option>)}</select></>}</div><label className="mt-4 flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-3xl border-2 border-dashed border-slate-200 bg-slate-50 p-5 text-center"><UploadCloud className="h-7 w-7 text-emerald-800"/><span className="mt-2 text-sm font-semibold">Choose scanned PDFs, Word files or images</span><span className="mt-1 text-xs text-slate-500">Multiple files can enter one review batch.</span><input multiple type="file" className="hidden" onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label>{files.length>0&&<div className="mt-3 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-900">{files.length} file(s) selected · {Math.round(files.reduce((n,f)=>n+f.size,0)/1024)} KB</div>}<button onClick={upload} disabled={!files.length||busy} className="mt-3 w-full rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?"Processing…":"Import originals"}</button></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Archive className="h-5 w-5 text-emerald-800"/><h2 className="text-lg font-semibold text-slate-950">Batches</h2></div><div className="mt-4 space-y-2">{batches.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No archive imports yet.</p>:batches.map(b=><button key={b.id} onClick={()=>setBatchId(b.id)} className={`w-full rounded-2xl border p-4 text-left ${batchId===b.id?"border-emerald-700 bg-emerald-50":"border-slate-100"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">{b.title}</p><p className="mt-1 text-xs text-slate-500">{b.total_files} files · {b.review_required_files} need review · {b.approved_files} approved</p></div><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold uppercase text-slate-500">{b.status.replaceAll("_"," ")}</span></div></button>)}</div></div>
   </div>
   <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-4">{[["Files",selectedBatch?.total_files??0,Files],["Need review",selectedBatch?.review_required_files??0,FileSearch],["Approved",selectedBatch?.approved_files??0,CheckCircle2],["Classified",selectedBatch?.classified_files??0,ScanLine]].map(([label,value,Icon]:any)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4"><Icon className="h-5 w-5 text-emerald-800"/><p className="mt-3 text-2xl font-bold">{value}</p><p className="text-xs uppercase tracking-[0.12em] text-slate-400">{label}</p></div>)}</div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Human review queue</p><h2 className="text-xl font-semibold text-slate-950">Confirm before matter import</h2></div><div className="mt-4 space-y-3">{!batchId?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Choose a batch to review its files.</p>:items.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">This batch has no files yet.</p>:items.map(item=>{const d=draft(item);const duplicate=item.review_status==="duplicate"||Boolean(item.duplicate_of_document_id);return <div key={item.id} className="rounded-3xl border border-slate-100 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{item.original_name}</p><p className="mt-1 text-xs text-slate-500">{item.mime_type||"file"} · {Math.round(Number(item.file_size_bytes||0)/1024)} KB</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${duplicate?"bg-amber-100 text-amber-900":item.review_status==="accepted"||item.review_status==="corrected"?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-500"}`}>{duplicate?"Duplicate flagged":item.review_status}</span></div>{!duplicate&&<div className="mt-4 grid gap-3 lg:grid-cols-[1fr_220px_1fr]"><input className={field} value={d.title} onChange={e=>setEdit(v=>({...v,[item.id]:{...d,title:e.target.value}}))} placeholder="Document title"/><input className={field} value={d.documentType} onChange={e=>setEdit(v=>({...v,[item.id]:{...d,documentType:e.target.value}}))} placeholder="Document type"/><select className={field} value={d.matterId} onChange={e=>setEdit(v=>({...v,[item.id]:{...d,matterId:e.target.value}}))}><option value="">Choose matter before approval</option>{matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div>}<div className="mt-3 flex flex-wrap gap-2">{!duplicate&&<button disabled={busy||!d.matterId} onClick={()=>review(item,item.review_status==="pending"?"accepted":"corrected")} className="rounded-xl bg-emerald-950 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">Approve into matter</button>}<button disabled={busy} onClick={()=>review(item,duplicate?"duplicate":"rejected")} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold text-slate-600">{duplicate?"Keep duplicate flag":"Reject"}</button></div></div>})}</div></div>
   </div>
  </section>
 </div></main>
}
