"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ClipboardCheck, FileText, Search, ShieldCheck } from "lucide-react";

type FormDef={id:string;form_key:string;name:string;description?:string|null;module:string;version:number;status:string;access_roles?:string[];schema?:{fields?:unknown[]}};
type Payload={success:boolean;error?:string;forms?:FormDef[]};

export default function FormsHub(){
 const[data,setData]=useState<Payload>({success:true,forms:[]});const[loading,setLoading]=useState(true);const[q,setQ]=useState("");const[module,setModule]=useState("");
 useEffect(()=>{fetch("/api/forms",{cache:"no-store",credentials:"include"}).then(r=>r.json()).then(p=>setData(p)).catch(e=>setData({success:false,error:e.message})).finally(()=>setLoading(false))},[]);
 const forms=data.forms??[];const modules=useMemo(()=>Array.from(new Set(forms.map(f=>f.module))).sort(),[forms]);const visible=forms.filter(f=>{const text=[f.name,f.description,f.module].filter(Boolean).join(" ").toLowerCase();return(!q.trim()||text.includes(q.trim().toLowerCase()))&&(!module||f.module===module)});
 return <main className="min-h-screen bg-[#eef2ef] p-3 text-slate-900 sm:p-5 lg:p-7"><div className="mx-auto max-w-[1700px] space-y-5">
  <Link href="/workspace" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Workspace</Link>
  <section className="overflow-hidden rounded-[2rem] bg-[#082b22] p-6 text-white shadow-[0_28px_80px_rgba(8,43,34,.15)] md:p-8 xl:p-10"><div className="grid gap-6 xl:grid-cols-[1fr_360px] xl:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#d8bb79]">Firm-controlled records</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Forms that actually open and work.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Published firm forms become usable operating records here. Choose a form, complete its governed fields, and save the result into TSIDKENU.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-4 text-xs leading-5 text-white/65"><ShieldCheck className="mr-2 inline h-4 w-4 text-[#d8bb79]"/>Access follows active firm role. Form definitions remain controlled in Firm Studio.</div></div></section>
  <section className="rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_260px]"><label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3"><Search className="h-4 w-4 text-slate-400"/><input className="w-full py-3 text-sm outline-none" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search controlled forms"/></label><select className="rounded-xl border border-slate-200 px-3 text-sm" value={module} onChange={e=>setModule(e.target.value)}><option value="">All modules</option>{modules.map(x=><option key={x}>{x}</option>)}</select></div></section>
  {loading?<div className="rounded-3xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-500">Loading controlled forms…</div>:!data.success?<div className="rounded-2xl border border-red-200 bg-white p-5 text-sm text-red-700">{data.error||"Unable to load forms."}</div>:<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(form=><Link key={form.id} href={`/forms/${form.id}`} className="group rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#88aa9e]"><div className="flex items-start justify-between gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf4f0] text-[#0f5b49]"><ClipboardCheck className="h-5 w-5"/></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-[.1em] ${form.status==="published"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{form.status}</span></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">{form.module} · v{form.version}</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{form.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{form.description||"Firm-controlled structured record."}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs text-slate-400">{Array.isArray(form.schema?.fields)?form.schema?.fields.length:0} field(s)</span><span className="inline-flex items-center gap-1.5 text-xs font-bold text-[#0f5b49]">Open form <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5"/></span></div></Link>)}{visible.length===0&&<div className="md:col-span-2 xl:col-span-3 rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><FileText className="mx-auto h-7 w-7 text-slate-400"/><h2 className="mt-3 text-lg font-semibold">No forms in this view</h2><p className="mt-2 text-sm text-slate-500">Publish or configure forms in Firm Studio, or change the filter.</p></div>}</section>}
 </div></main>
}
