"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Mail, MessageSquareText, Phone, Settings2, Send, ShieldCheck } from "lucide-react";

type Party={id:string;display_name:string;phone?:string|null;email?:string|null;client_status:string};
type Matter={id:string;title:string;client_name:string;status:string;case_reference?:string|null};
type Interaction={id:string;matter_id?:string|null;primary_party_id?:string|null;interaction_type:string;direction:string;occurred_at:string;subject?:string|null;raw_note?:string|null;verification_status?:string|null};
type Payload={success:boolean;error?:string;parties?:Party[];matters?:Matter[];interactions?:Interaction[];providers?:{email?:{configured:boolean;status:string;displayName?:string|null};whatsapp?:{configured:boolean;status:string;displayName?:string|null}}};
const field="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none";

export default function CommunicationsPage(){
 const[data,setData]=useState<Payload>({success:true,parties:[],matters:[],interactions:[]});
 const[loading,setLoading]=useState(true); const[message,setMessage]=useState(""); const[busy,setBusy]=useState(false); const[tab,setTab]=useState<"inbox"|"email"|"call"|"settings">("inbox");
 const[email,setEmail]=useState({partyId:"",matterId:"",to:"",subject:"",text:""});
 const[call,setCall]=useState({partyId:"",matterId:"",direction:"outbound",subject:"Phone call",note:"",durationMinutes:""});
 const[config,setConfig]=useState({displayName:"Firm email",host:"",port:"587",username:"",password:"",from:"",secure:false,starttls:true});

 async function load(){setLoading(true);try{const r=await fetch("/api/communications",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load communications.");setData(p)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load communications.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const partyMap=useMemo(()=>new Map((data.parties??[]).map(x=>[x.id,x])),[data.parties]);
 const matterMap=useMemo(()=>new Map((data.matters??[]).map(x=>[x.id,x])),[data.matters]);

 function chooseParty(id:string){
  const party=partyMap.get(id);
  setEmail(current=>({...current,partyId:id,to:party?.email||current.to}));
  setCall(current=>({...current,partyId:id}));
 }
 async function sendEmail(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/communications",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"send_email",...email})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Email failed.");setEmail({partyId:"",matterId:"",to:"",subject:"",text:""});await load();setMessage("Email sent and recorded in the client/case history.")}catch(e){setMessage(e instanceof Error?e.message:"Email failed.")}finally{setBusy(false)}}
 async function logCall(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/communications",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"log_call",...call,durationMinutes:Number(call.durationMinutes||0)})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Call log failed.");setCall({partyId:"",matterId:"",direction:"outbound",subject:"Phone call",note:"",durationMinutes:""});await load();setMessage("Call recorded in communications history.")}catch(e){setMessage(e instanceof Error?e.message:"Call log failed.")}finally{setBusy(false)}}
 async function saveEmailConfig(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/communications",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"configure_email",...config})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Email configuration failed.");setConfig(current=>({...current,password:""}));await load();setMessage("Firm email configuration saved. It becomes verified after a successful delivery test.")}catch(e){setMessage(e instanceof Error?e.message:"Email configuration failed.")}finally{setBusy(false)}}

 return <main className="min-h-screen bg-[#eef2ef] p-3 text-slate-900 sm:p-5 lg:p-7"><div className="mx-auto max-w-[1760px] space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/workspace" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Workspace</Link><div className="flex gap-2"><Provider icon={Mail} label="Email" state={data.providers?.email?.status||"not configured"}/><Provider icon={MessageSquareText} label="WhatsApp" state={data.providers?.whatsapp?.status||"not configured"}/></div></div>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-8 xl:p-10"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">Communications Hub</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Email, WhatsApp and calls stay attached to the client and case.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">External communication becomes part of the governed legal record instead of disappearing into separate phones and inboxes.</p></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  <div className="flex flex-wrap gap-2">{[["inbox","History"],["email","Send email"],["call","Log call"],["settings","Email setup"]].map(([key,label])=><button key={key} onClick={()=>setTab(key as typeof tab)} className={"rounded-xl px-4 py-2.5 text-sm font-bold "+(tab===key?"bg-[#0b493b] text-white":"border border-slate-200 bg-white text-slate-600")}>{label}</button>)}</div>

  {tab==="inbox"&&<section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm">{loading?<p className="py-12 text-center text-sm text-slate-500">Loading communication history…</p>:<div className="space-y-2">{(data.interactions??[]).map(item=><article key={item.id} className="grid gap-3 rounded-xl border border-slate-100 bg-[#fbfcfb] p-4 md:grid-cols-[150px_1fr_auto]"><div><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#0f5b49]">{item.interaction_type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-400">{new Date(item.occurred_at).toLocaleString()}</p></div><div><p className="text-sm font-semibold">{item.subject||"Communication"}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{item.raw_note||"No note."}</p><p className="mt-1 text-[11px] text-slate-400">{item.primary_party_id?partyMap.get(item.primary_party_id)?.display_name:"Unlinked contact"}{item.matter_id?" · "+(matterMap.get(item.matter_id)?.case_reference||matterMap.get(item.matter_id)?.title||"Case"):""}</p></div><span className="h-fit rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-black uppercase">{item.direction}</span></article>)}{!(data.interactions??[]).length&&<p className="py-12 text-center text-sm text-slate-500">No communication history yet.</p>}</div>}</section>}

  {tab==="email"&&<form onSubmit={sendEmail} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex items-center gap-3"><Mail className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-2xl font-semibold">Send governed email</h2></div><div className="mt-5 grid gap-3 md:grid-cols-2"><select className={field} value={email.partyId} onChange={e=>chooseParty(e.target.value)}><option value="">Select client / contact</option>{(data.parties??[]).map(x=><option key={x.id} value={x.id}>{x.display_name}{x.email?" — "+x.email:""}</option>)}</select><select className={field} value={email.matterId} onChange={e=>setEmail({...email,matterId:e.target.value})}><option value="">No case link</option>{(data.matters??[]).map(x=><option key={x.id} value={x.id}>{x.case_reference||"CASE"} — {x.client_name} — {x.title}</option>)}</select><input required type="email" className={field} value={email.to} onChange={e=>setEmail({...email,to:e.target.value})} placeholder="Recipient email"/><input required className={field} value={email.subject} onChange={e=>setEmail({...email,subject:e.target.value})} placeholder="Subject"/><textarea required className={field+" md:col-span-2 min-h-40"} value={email.text} onChange={e=>setEmail({...email,text:e.target.value})} placeholder="Message"/></div><div className="mt-4 flex items-center justify-between gap-4"><p className="text-xs text-slate-500">Substantive legal content remains lawyer-controlled. The sent message is logged against the selected client/case.</p><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-[#082b22] px-5 py-3 text-sm font-bold text-white"><Send className="h-4 w-4"/>{busy?"Sending…":"Send email"}</button></div></form>}

  {tab==="call"&&<form onSubmit={logCall} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex items-center gap-3"><Phone className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-2xl font-semibold">Log phone / WhatsApp call</h2></div><div className="mt-5 grid gap-3 md:grid-cols-2"><select className={field} value={call.partyId} onChange={e=>setCall({...call,partyId:e.target.value})}><option value="">Select client / contact</option>{(data.parties??[]).map(x=><option key={x.id} value={x.id}>{x.display_name}{x.phone?" — "+x.phone:""}</option>)}</select><select className={field} value={call.matterId} onChange={e=>setCall({...call,matterId:e.target.value})}><option value="">No case link</option>{(data.matters??[]).map(x=><option key={x.id} value={x.id}>{x.case_reference||"CASE"} — {x.title}</option>)}</select><select className={field} value={call.direction} onChange={e=>setCall({...call,direction:e.target.value})}><option value="outbound">Outbound</option><option value="inbound">Inbound</option></select><input className={field} inputMode="numeric" value={call.durationMinutes} onChange={e=>setCall({...call,durationMinutes:e.target.value})} placeholder="Duration minutes"/><input className={field+" md:col-span-2"} value={call.subject} onChange={e=>setCall({...call,subject:e.target.value})} placeholder="Call subject"/><textarea required className={field+" md:col-span-2 min-h-32"} value={call.note} onChange={e=>setCall({...call,note:e.target.value})} placeholder="What was discussed, outcome and next action"/></div><div className="mt-4 flex justify-end"><button disabled={busy} className="rounded-xl bg-[#082b22] px-5 py-3 text-sm font-bold text-white">{busy?"Saving…":"Save call record"}</button></div></form>}

  {tab==="settings"&&<form onSubmit={saveEmailConfig} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex items-center gap-3"><Settings2 className="h-5 w-5 text-[#0f5b49]"/><div><h2 className="text-2xl font-semibold">Firm email connection</h2><p className="mt-1 text-sm text-slate-500">Credentials are encrypted in the existing tenant credential vault.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><input className={field} value={config.displayName} onChange={e=>setConfig({...config,displayName:e.target.value})} placeholder="Mailbox label"/><input required className={field} value={config.from} onChange={e=>setConfig({...config,from:e.target.value})} placeholder="From email"/><input required className={field} value={config.host} onChange={e=>setConfig({...config,host:e.target.value})} placeholder="SMTP host"/><input required className={field} value={config.port} onChange={e=>setConfig({...config,port:e.target.value})} placeholder="Port"/><input required className={field} value={config.username} onChange={e=>setConfig({...config,username:e.target.value})} placeholder="SMTP username"/><input required type="password" className={field} value={config.password} onChange={e=>setConfig({...config,password:e.target.value})} placeholder="SMTP password / app password"/><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"><input type="checkbox" checked={config.secure} onChange={e=>setConfig({...config,secure:e.target.checked})}/>Implicit TLS (usually port 465)</label><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"><input type="checkbox" checked={config.starttls} onChange={e=>setConfig({...config,starttls:e.target.checked})}/>STARTTLS</label></div><div className="mt-4 flex items-center justify-between gap-4"><p className="text-xs text-slate-500"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>Inbound mailbox synchronization is not activated by SMTP alone; outbound becomes verified only after a real successful send.</p><button disabled={busy} className="rounded-xl bg-[#082b22] px-5 py-3 text-sm font-bold text-white">{busy?"Saving…":"Save email connection"}</button></div></form>}
 </div></main>
}
function Provider({icon:Icon,label,state}:{icon:typeof Mail;label:string;state:string}){return <div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs"><Icon className="h-4 w-4 text-[#0f5b49]"/><span className="font-bold">{label}</span><span className="text-slate-400">{state}</span></div>}
