"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import { Archive,ArrowRight,Bell,BookOpenCheck,BriefcaseBusiness,Building2,ChevronRight,CircleUserRound,Clock3,FileCheck2,FileText,FolderOpen,Gauge,Landmark,LibraryBig,Menu,MessageSquareText,Receipt,ShieldCheck,Users,X } from "lucide-react";
import TsidkenuLogo from "@/components/TsidkenuLogo";

type QueueItem=Record<string,unknown>;
type Payload={success:boolean;error?:string;identity?:{actorName?:string|null;actorRole?:string|null;title?:string|null;firmId?:string|null;firmName?:string|null;firmCountry?:string|null};capabilities?:Record<string,boolean>;metrics?:Record<string,number>;queues?:Record<string,QueueItem[]>};
type Nav={href:string;label:string;description:string;icon:LucideIcon;finance?:boolean};
type Row={id:string;title:string;subtitle:string;badge:string;href?:string};

const nav:Nav[]=[
 {href:"/workspace",label:"Command",description:"Today, risk and priority",icon:Gauge},
 {href:"/matters",label:"Matters",description:"Matter lifecycle",icon:BriefcaseBusiness},
 {href:"/intake",label:"Client cycle",description:"Intake to matter opening",icon:Users},
 {href:"/interactions",label:"Interactions",description:"Notes, audio and meetings",icon:MessageSquareText},
 {href:"/whatsapp",label:"WhatsApp Desk",description:"Messages, secure forms and triggers",icon:MessageSquareText},
 {href:"/forms",label:"Controlled forms",description:"Structured firm records",icon:FolderOpen},
 {href:"/document-bank",label:"Document Bank",description:"Precedents and AI-assisted adaptation",icon:FileText},
 {href:"/law-bank",label:"Law Bank",description:"Law and verified legal sources",icon:LibraryBig},
 {href:"/finance",label:"Finance",description:"Billing, cash and collections",icon:Receipt,finance:true},
 {href:"/digitisation",label:"Digitisation",description:"Evidence and legacy files",icon:Archive},
 {href:"/people",label:"People",description:"Teams and performance",icon:CircleUserRound},
 {href:"/storage",label:"Storage & Integrations",description:"File custody and provider health",icon:Archive},
 {href:"/studio",label:"Firm Studio",description:"Govern the firm",icon:Building2},
];
const roleExperience:Record<string,{eyebrow:string;heading:string;summary:string}>={
 owner:{eyebrow:"Firm command",heading:"Run the firm from one accountable legal operating surface.",summary:"Matters, client obligations, legal sources, collections and professional controls are visible without turning the system into a wall of cards."},
 partner:{eyebrow:"Partner command",heading:"See risk and professional judgment before administration.",summary:"Approvals, sensitive matters, client commitments and financial exposure stay connected to the underlying file."},
 finance:{eyebrow:"Finance desk",heading:"Collections stay connected to the matters that created them.",summary:"Invoices, payments, expenses and outstanding balances remain traceable to legal work."},
 lawyer:{eyebrow:"Lawyer desk",heading:"Work from the next legal action, not from disconnected tools.",summary:"Matters, deadlines, drafts, client instructions and source-backed research meet in one workspace."},
};
const s=(v:unknown)=>typeof v==="string"?v:"";
const money=(v:number)=>`${new Intl.NumberFormat("fr-CM",{maximumFractionDigits:0}).format(v||0)} XAF`;
function roleKey(role:string){const x=role.toLowerCase();if(x.includes("owner")||x.includes("founder"))return"owner";if(x.includes("partner"))return"partner";if(x.includes("finance")||x.includes("account"))return"finance";return"lawyer"}

export default function WorkspacePage(){
 const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[mobile,setMobile]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/workspace",{cache:"no-store",credentials:"include"});if(r.status===401){window.location.replace("/auth?redirectTo=%2Fworkspace");return}if(r.status===409){window.location.replace("/onboarding");return}const p=await r.json() as Payload;if(!r.ok||!p.success)throw new Error(p.error||"Unable to load workspace.");setData(p)}catch(e){setError(e instanceof Error?e.message:"Unable to load workspace.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 if(loading)return <State title="Restoring legal workspace" detail="Resolving active firm, role and operating queues…"/>;
 if(error||!data?.success)return <State title="Workspace unavailable" detail={error||data?.error||"Unable to load workspace."} action={<button onClick={()=>void load()} className="rounded-xl bg-[#082b22] px-4 py-2.5 text-sm font-bold text-white">Retry</button>}/>;
 const role=data.identity?.actorRole||"lawyer", experience=roleExperience[roleKey(role)]||roleExperience.lawyer, metrics=data.metrics||{}, queues=data.queues||{};
 const firm=data.identity?.firmName||"Active firm", country=data.identity?.firmCountry||"";
 const rows=(key:string,titleKey:string,subtitle:(i:QueueItem)=>string,href:(i:QueueItem)=>string|undefined):Row[]=>(queues[key]||[]).map(i=>({id:s(i.id),title:s(i[titleKey])||"Untitled",subtitle:subtitle(i),badge:s(i.status)||s(i.review_status)||"open",href:href(i)}));
 const matters=rows("matters","title",i=>[s(i.client_name),s(i.matter_type),s(i.procedural_stage)].filter(Boolean).join(" • "),i=>s(i.id)?`/matters/${s(i.id)}`:undefined);
 const tasks=rows("tasks","title",i=>s(i.deadline)?`Due ${new Date(s(i.deadline)).toLocaleDateString()}`:"No deadline recorded",i=>s(i.matter_id)?`/matters/${s(i.matter_id)}`:undefined);
 const docs=rows("documents","title",i=>[s(i.document_type),s(i.version_label)].filter(Boolean).join(" • "),i=>s(i.matter_id)?`/matters/${s(i.matter_id)}`:undefined);
 const intake=rows("intake","prospect_name",i=>`Conflict ${s(i.conflict_status)||"pending"} • Engagement ${s(i.engagement_status)||"pending"}`,()=>"/intake");
 const visibleNav=nav.filter(item=>!item.finance||data.capabilities?.finance);
 return <main className="min-h-screen bg-[#eef2ef] text-slate-900">
  <div className="min-h-screen lg:grid lg:grid-cols-[272px_minmax(0,1fr)] 2xl:grid-cols-[292px_minmax(0,1fr)]">
   <aside className="hidden h-screen flex-col border-r border-white/10 bg-[#062f27] text-white lg:sticky lg:top-0 lg:flex"><div className="px-5 pb-5 pt-6"><TsidkenuLogo surface="dark"/><div className="mt-6 rounded-2xl border border-white/10 bg-white/[.055] p-4"><p className="text-[9px] font-black uppercase tracking-[.2em] text-white/35">Active firm</p><p className="mt-2 truncate text-sm font-bold">{firm}</p><p className="mt-1 truncate text-[10px] text-white/40">{[country,role].filter(Boolean).join(" • ")}</p></div></div><nav className="flex-1 overflow-y-auto px-3 pb-5">{visibleNav.map(item=><NavLink key={item.href} item={item}/>)}</nav><div className="border-t border-white/10 p-4"><div className="rounded-xl bg-black/10 p-3"><p className="truncate text-xs font-bold">{data.identity?.actorName||"Firm member"}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[.14em] text-white/35">{role}</p></div></div></aside>
   {mobile&&<div className="fixed inset-0 z-50 bg-[#041d18]/50 backdrop-blur-sm lg:hidden" onClick={()=>setMobile(false)}><aside className="h-full w-[88%] max-w-sm bg-[#062f27] p-5 text-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><TsidkenuLogo surface="dark"/><button onClick={()=>setMobile(false)} className="rounded-xl border border-white/10 p-2"><X className="h-5 w-5"/></button></div><p className="mt-6 text-xs font-bold text-white/50">{firm}</p><nav className="mt-4 space-y-1">{visibleNav.map(item=><NavLink key={item.href} item={item}/>)}</nav></aside></div>}
   <section className="min-w-0"><header className="sticky top-0 z-30 border-b border-slate-200/80 bg-[#f8faf8]/92 backdrop-blur-xl"><div className="flex h-16 items-center gap-3 px-4 sm:px-6 xl:px-8 2xl:px-10"><button onClick={()=>setMobile(true)} className="rounded-xl border border-slate-200 bg-white p-2.5 lg:hidden"><Menu className="h-5 w-5"/></button><div className="min-w-0 flex-1"><p className="truncate text-xs font-black uppercase tracking-[.13em] text-slate-400">{firm}</p><p className="truncate text-sm font-semibold text-slate-800">Legal operating workspace</p></div><Link href="/interactions" className="hidden rounded-xl bg-[#083b30] px-4 py-2.5 text-sm font-bold text-white sm:inline-flex">Capture interaction</Link><button className="rounded-xl border border-slate-200 bg-white p-2.5" aria-label="Notifications"><Bell className="h-5 w-5"/></button></div></header>
    <div className="space-y-5 px-4 py-5 sm:px-6 sm:py-6 xl:px-8 xl:py-8 2xl:px-10">
     <section className="overflow-hidden rounded-[2rem] bg-[#07372d] text-white shadow-[0_24px_70px_rgba(7,55,45,.16)]"><div className="grid xl:grid-cols-[minmax(0,1fr)_380px]"><div className="p-6 sm:p-8 xl:p-10 2xl:p-12"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d6b66f]">{experience.eyebrow}</p><h1 className="mt-3 max-w-5xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl xl:text-5xl 2xl:text-[3.6rem] 2xl:leading-[1.02]">{experience.heading}</h1><p className="mt-4 max-w-4xl text-sm leading-7 text-white/65 sm:text-base">{experience.summary}</p></div><div className="grid grid-cols-2 gap-px border-t border-white/10 bg-white/10 xl:border-l xl:border-t-0"><Hero label="Active matters" value={String(metrics.activeMatters||0)} icon={BriefcaseBusiness}/><Hero label="Urgent work" value={String(metrics.urgentTasks||0)} icon={Clock3}/><Hero label="Open intake" value={String(metrics.openIntake||0)} icon={Users}/><Hero label="High risk" value={String(metrics.highRiskMatters||0)} icon={ShieldCheck}/></div></div></section>
     <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Action href="/intake" icon={Users} title="Master intake" text="Conflict, KYC, consultation and engagement"/><Action href="/whatsapp" icon={MessageSquareText} title="WhatsApp desk" text="Messages, intake triggers and secure forms"/><Action href="/document-bank" icon={FileText} title="Document Bank" text="Precedents and governed AI adaptation"/><Action href={data.capabilities?.finance?"/finance":"/forms"} icon={data.capabilities?.finance?Receipt:FileCheck2} title={data.capabilities?.finance?"Finance":"Controlled forms"} text={data.capabilities?.finance?"Invoices, payments, expenses and collections":"Open a firm-controlled record"}/></section>
     <section className="grid gap-5 xl:grid-cols-2 2xl:grid-cols-[1.15fr_1fr_1fr]"><Queue title="Matter command" icon={BriefcaseBusiness} rows={matters} empty="No accessible matters."/><Queue title="Work due" icon={Clock3} rows={tasks} empty="No open tasks."/><Queue title="Drafting & review" icon={FileText} rows={docs} empty="No documents awaiting review."/></section>
     <section className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,.6fr)]"><Queue title="Client cycle" icon={Users} rows={intake} empty="No open assessments."/>{data.capabilities?.finance?<Link href="/finance" className="group rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className="rounded-xl bg-amber-50 p-2.5 text-amber-700"><Receipt className="h-5 w-5"/></div><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5"/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Outstanding fees</p><p className="mt-1 text-3xl font-semibold">{money(Number(metrics.outstandingXaf||0))}</p><p className="mt-2 text-sm text-slate-500">{Number(metrics.outstandingInvoices||0)} invoice(s) need collection or reconciliation.</p></Link>:<div className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><Landmark className="h-5 w-5 text-[#0f5b49]"/><h2 className="mt-4 text-lg font-semibold">Role-native workspace</h2><p className="mt-2 text-sm leading-6 text-slate-500">The active membership determines what appears here; the interface does not grant itself authority.</p></div>}</section>
    </div>
   </section>
  </div>
 </main>
}

function NavLink({item}:{item:Nav}){const Icon=item.icon;return <Link href={item.href} className="group flex items-center gap-3 rounded-xl px-3 py-2.5 text-white/62 transition hover:bg-white/[.07] hover:text-white"><Icon className="h-4 w-4 shrink-0 text-white/40 group-hover:text-[#e0c17d]"/><div className="min-w-0"><p className="text-xs font-bold">{item.label}</p><p className="mt-0.5 truncate text-[9px] text-white/27">{item.description}</p></div></Link>}
function Hero({label,value,icon:Icon}:{label:string;value:string;icon:LucideIcon}){return <div className="bg-white/[.045] p-5 sm:p-6"><Icon className="h-4 w-4 text-[#d8bb79]"/><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[.15em] text-white/38">{label}</p></div>}
function Action({href,icon:Icon,title,text}:{href:string;icon:LucideIcon;title:string;text:string}){return <Link href={href} className="group flex min-h-28 items-center gap-4 rounded-[1.45rem] border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-[#8eafa4]"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#edf4f0] text-[#0f5b49]"><Icon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-950">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div><ArrowRight className="h-4 w-4 shrink-0 text-slate-300 transition group-hover:translate-x-0.5"/></Link>}
function Queue({title,icon:Icon,rows,empty}:{title:string;icon:LucideIcon;rows:Row[];empty:string}){return <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#edf4f0] p-2.5 text-[#0f5b49]"><Icon className="h-4 w-4"/></div><h2 className="text-base font-bold">{title}</h2><span className="ml-auto rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-500">{rows.length}</span></div><div className="mt-4 space-y-1">{rows.slice(0,6).map(row=>{const body=<div className="group flex items-center gap-3 rounded-xl px-3 py-3 hover:bg-[#f4f8f6]"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{row.title}</p><p className="mt-1 truncate text-[11px] text-slate-500">{row.subtitle||"Open record"}</p></div><span className="max-w-24 truncate rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black uppercase text-slate-500">{row.badge}</span><ChevronRight className="h-4 w-4 text-slate-300"/></div>;return row.href?<Link key={row.id||row.title} href={row.href}>{body}</Link>:<div key={row.id||row.title}>{body}</div>})}{!rows.length&&<div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">{empty}</div>}</div></div>}
function State({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <main className="grid min-h-screen place-items-center bg-[#eef2ef] p-6"><div className="w-full max-w-md rounded-[1.7rem] border border-slate-200 bg-white p-7 shadow-xl"><TsidkenuLogo surface="light"/><h1 className="mt-6 text-xl font-semibold">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{detail}</p>{action&&<div className="mt-5">{action}</div>}</div></main>}
