"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertTriangle, Archive, BriefcaseBusiness, Building2, CheckCircle2, Clock3, FileCheck2, FileText, Landmark, MessageSquareText, Receipt, ShieldCheck, Sparkles, Users, LibraryBig } from "lucide-react";

type WorkspacePayload = { success:boolean; error?:string; identity?:{actorName?:string|null;actorRole?:string|null;title?:string|null;firmId?:string|null}; capabilities?:Record<string,boolean>; metrics?:Record<string,number>; queues?:Record<string,any[]> };
type SessionPayload = { authenticated:boolean; needsOnboarding?:boolean; firmId?:string|null; activeFirmId?:string|null; actorRole?:string|null; memberships?:unknown[] };
type GateState = "resolving-session" | "resolving-context" | "ready" | "unauthenticated" | "unauthorized" | "error";

const money=(value:number)=>new Intl.NumberFormat("fr-CM",{maximumFractionDigits:0}).format(value||0)+" XAF";

export default function WorkspacePage(){
 const router=useRouter(); const [data,setData]=useState<WorkspacePayload|null>(null); const [gate,setGate]=useState<GateState>("resolving-session"); const [gateError,setGateError]=useState<string|null>(null);
 const load=useCallback(async()=>{setGate("resolving-session");setGateError(null);try{const sessionResponse=await fetch("/api/session",{cache:"no-store",credentials:"include"});if(sessionResponse.status===401){setGate("unauthenticated");router.replace(`/auth?redirectTo=${encodeURIComponent("/workspace")}`);return;}if(!sessionResponse.ok)throw new Error("Unable to restore your secure session.");const session=await sessionResponse.json() as SessionPayload;if(!session.authenticated){setGate("unauthenticated");router.replace(`/auth?redirectTo=${encodeURIComponent("/workspace")}`);return;}if(session.needsOnboarding){router.replace("/onboarding");return;}setGate("resolving-context");const contextReady=Boolean(session.activeFirmId&&session.firmId&&session.actorRole&&(session.memberships?.length??0)>0);if(!contextReady){setGate("unauthorized");setGateError("Your sign-in is valid, but no active firm membership and role context could be resolved.");return;}const response=await fetch("/api/workspace",{cache:"no-store",credentials:"include"});if(response.status===401){setGate("unauthorized");setGateError("Your session is valid, but this firm workspace is not authorized for the resolved role.");return;}const payload=await response.json() as WorkspacePayload;if(!response.ok||!payload.success)throw new Error(payload.error||"Unable to load workspace.");setData(payload);setGate("ready");}catch(error){setGate("error");setGateError(error instanceof Error?error.message:"Unable to load workspace.");}},[router]);
 useEffect(()=>{void load();},[load]);
 if(gate==="resolving-session"||gate==="resolving-context")return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6 text-slate-700"><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><p className="text-sm font-semibold">{gate==="resolving-session"?"Restoring secure Supabase session…":"Resolving active firm, membership and role…"}</p></div></main>;
 if(gate!=="ready"||!data?.success)return <main className="min-h-screen bg-slate-50 p-6 text-slate-700"><div className="mx-auto max-w-3xl rounded-3xl border border-amber-200 bg-white p-8"><AlertTriangle className="h-6 w-6 text-amber-600"/><h1 className="mt-4 text-2xl font-semibold">{gate==="unauthorized"?"Workspace access not established":"Workspace unavailable"}</h1><p className="mt-2 text-sm text-slate-600">{gateError||data?.error||"The workspace could not be resolved."}</p><div className="mt-5 flex gap-3"><button onClick={()=>void load()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Retry workspace</button>{gate==="unauthenticated"?<Link href="/auth?redirectTo=%2Fworkspace" className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Open access</Link>:null}</div></div></main>;
 const q=data.queues??{};const m=data.metrics??{};const role=data.identity?.actorRole??"lawyer";const cards=[["Active matters",m.activeMatters??0,BriefcaseBusiness],["Urgent tasks",m.urgentTasks??0,Clock3],["Review queue",m.reviewQueue??0,FileCheck2],["Open intake",m.openIntake??0,Users],["Client updates",m.pendingClientUpdates??0,Landmark],["High-risk matters",m.highRiskMatters??0,ShieldCheck]] as const;
 return <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc_0%,#eef3f2_100%)] p-4 text-slate-800 md:p-6 xl:p-8"><div className="mx-auto max-w-[1700px] space-y-6">
 <section className="rounded-[2rem] border border-white/70 bg-[#082b22] p-6 text-white shadow-[0_24px_60px_rgba(0,43,34,0.18)] md:p-8"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/8 px-3 py-1 text-[10px] font-black uppercase tracking-[0.24em] text-white/70"><Sparkles className="h-3.5 w-3.5"/>Role-native command workspace</div><h1 className="mt-4 text-4xl font-semibold tracking-tight md:text-5xl">{data.identity?.title||role}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/70">What needs attention, who is waiting, what is due, and what changed—without forcing staff to understand the machinery underneath.</p></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><Link href="/interactions" className="rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-[#082b22]">+ Visit / Contact</Link><Link href="/intake" className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-semibold text-white">Client cycle</Link><Link href="/digitisation" className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-semibold text-white">Digitisation</Link><Link href="/law-bank" className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-semibold text-white">Law Bank</Link><Link href="/people" className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-semibold text-white">People</Link><Link href="/studio" className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-semibold text-white">Firm Studio</Link><Link href="/" className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-semibold text-white">Firm cockpit</Link></div></div></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label,value,Icon])=><div key={label} className="rounded-[1.4rem] border border-slate-200 bg-white p-4 shadow-sm"><Icon className="h-5 w-5 text-[#0f5b49]"/><p className="mt-4 text-2xl font-bold text-slate-950">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">{label}</p></div>)}</section>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Nav href="/interactions" icon={MessageSquareText} title="Interactions" text="Walk-ins, calls, meetings, WhatsApp, email and referrals enter one governed activity stream."/><Nav href="/intake" icon={Users} title="Client cycle" text="Search the person first, assess progressively, then open the matter only after professional gates."/><Nav href="/digitisation" icon={Archive} title="Digitisation Desk" text="Import old files in batches, preserve originals, flag duplicates and approve records into matters."/><Nav href="/law-bank" icon={LibraryBig} title="Law Bank" text="Source-governed legislation, OHADA/CEMAC/OAPI material, jurisprudence and internal precedent."/><Nav href="/people" icon={Users} title="People & performance" text="Supervision and professional development based on real work, timeliness and quality—not AI usage."/></section>
 <section className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]"><div className="space-y-5"><Queue title="Matter command" icon={BriefcaseBusiness} empty="No accessible matters yet." rows={(q.matters??[]).map((i:any)=>({id:i.id,title:i.title,subtitle:[i.client_name,i.matter_type,i.procedural_stage].filter(Boolean).join(" • "),badge:i.status,href:`/matters/${i.id}`}))}/><Queue title="Work queue" icon={Clock3} empty="No open tasks." rows={(q.tasks??[]).map((i:any)=>({id:i.id,title:i.title,subtitle:i.deadline?`Due ${new Date(i.deadline).toLocaleString()}`:"No deadline",badge:i.status||"open",href:i.matter_id?`/matters/${i.matter_id}`:undefined}))}/><Queue title="Drafting & review" icon={FileText} empty="No documents awaiting review." rows={(q.documents??[]).map((i:any)=>({id:i.id,title:i.title,subtitle:[i.document_type,i.version_label].filter(Boolean).join(" • "),badge:i.review_status||i.status,href:i.matter_id?`/matters/${i.matter_id}`:undefined}))}/></div><div className="space-y-5"><Queue title="Intake & conflict" icon={Users} empty="No open intake." rows={(q.intake??[]).map((i:any)=>({id:i.id,title:i.prospect_name,subtitle:`Conflict: ${i.conflict_status||"pending"} • Engagement: ${i.engagement_status||"pending"}`,badge:i.risk_level||i.status,href:"/intake"}))}/><Queue title="Client service" icon={Landmark} empty="No client updates pending." rows={(q.clientUpdates??[]).map((i:any)=>({id:i.id,title:i.title,subtitle:i.instruction_required?`Instruction: ${i.instruction_status||"pending"}`:"No instruction required",badge:i.delivery_status||i.status,href:i.matter_id?`/matters/${i.matter_id}`:undefined}))}/>{data.capabilities?.finance?<div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><Receipt className="h-5 w-5 text-[#0f5b49]"/><h2 className="mt-3 text-xl font-semibold text-slate-950">Outstanding {money(m.outstandingXaf??0)}</h2><p className="mt-3 text-sm text-slate-600">{m.outstandingInvoices??0} invoice(s) require collection, reconciliation or closure review.</p></div>:null}<Queue title="Closure & memory" icon={CheckCircle2} empty="No matters in closure review." rows={(q.closures??[]).map((i:any)=>({id:i.id,title:i.approved_at?"Closure approved":"Closure review",badge:i.approved_at?"approved":"review",href:i.matter_id?`/matters/${i.matter_id}`:undefined}))}/></div></section>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Capability enabled={Boolean(data.capabilities?.ethicalWalls)} title="Ethical walls" text="Governors can control screened access and restricted matters."/><Capability enabled={Boolean(data.capabilities?.approvals)} title="Partner approvals" text="Filing, AI-work and governance approval surfaces follow role authority."/><Capability enabled={Boolean(data.capabilities?.clientAccess)} title="Client access" text="Matter updates, instructions and portal grants follow matter authorization."/><Capability enabled={Boolean(data.capabilities?.studio)} title="Firm Studio" text="Brand, legal parameters, workflows, privacy and forms are firm-specific."/></section>
 </div></main>;
}
function Nav({href,icon:Icon,title,text}:{href:string;icon:any;title:string;text:string}){return <Link href={href} className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:border-emerald-300"><Icon className="h-5 w-5 text-[#0f5b49]"/><h2 className="mt-4 text-lg font-semibold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></Link>}
function Queue({title,icon:Icon,rows,empty}:{title:string;icon:any;rows:{id:string;title:string;subtitle?:string;badge?:string;href?:string}[];empty:string}){return <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2.5 text-[#0f5b49]"><Icon className="h-5 w-5"/></div><h2 className="text-xl font-semibold text-slate-950">{title}</h2></div><div className="mt-4 space-y-2">{rows.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">{empty}</p>:rows.map(row=>{const body=<div className="flex items-center justify-between gap-4 rounded-xl border border-slate-100 px-4 py-3 transition hover:border-emerald-200"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{row.title}</p><p className="mt-1 truncate text-xs text-slate-500">{row.subtitle}</p></div><span className="shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.12em] text-slate-500">{row.badge||"open"}</span></div>;return row.href?<Link key={row.id} href={row.href}>{body}</Link>:<div key={row.id}>{body}</div>})}</div></div>}
function Capability({enabled,title,text}:{enabled:boolean;title:string;text:string}){return <div className="rounded-[1.35rem] border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Building2 className="h-4 w-4 text-[#0f5b49]"/><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.12em] ${enabled?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-400"}`}>{enabled?"Enabled":"Role limited"}</span></div><h3 className="mt-4 font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
