import { NextResponse } from "next/server";
import { createServerSupabaseClient } from "@/lib/supabase-server";

type Context={params:Promise<{token:string}>};
type Field={key?:string;required?:boolean;type?:string};
function validate(fields:Field[],values:Record<string,unknown>){const errors:string[]=[];for(const f of fields){const k=String(f.key??"");if(!k)continue;const v=values[k];const empty=v===undefined||v===null||v===""||(Array.isArray(v)&&!v.length);if(f.required&&empty)errors.push(`${k} is required.`);if(!empty&&f.type==="email"&&typeof v==="string"&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v))errors.push(`${k} must be a valid email.`);}return errors;}
async function load(token:string){const supabase=createServerSupabaseClient();if(!supabase)throw new Error("Form service unavailable.");const link=await supabase.from("form_share_links").select("id,firm_id,form_definition_id,prospect_id,matter_id,recipient_name,status,expires_at,completed_at").eq("token",token).maybeSingle();if(link.error)throw new Error(link.error.message);if(!link.data)throw new Error("Form link not found.");if(link.data.status!=="active")throw new Error("This form link is no longer active.");if(link.data.expires_at&&new Date(link.data.expires_at).getTime()<Date.now())throw new Error("This form link has expired.");const form=await supabase.from("firm_form_definitions").select("id,name,description,module,status,schema,ui_schema").eq("id",link.data.form_definition_id).eq("firm_id",link.data.firm_id).maybeSingle();if(form.error)throw new Error(form.error.message);if(!form.data||form.data.status!=="published")throw new Error("This form is unavailable.");return{supabase,link:link.data,form:form.data};}
export async function GET(_:Request,ctx:Context){try{const{token}=await ctx.params;const{link,form}=await load(token);return NextResponse.json({success:true,recipientName:link.recipient_name,form:{id:form.id,name:form.name,description:form.description,module:form.module,schema:form.schema,uiSchema:form.ui_schema}});}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:"Unable to load form."},{status:404});}}
export async function POST(request:Request,ctx:Context){try{const{token}=await ctx.params;const{supabase,link,form}=await load(token);const body=await request.json();const values=body.data&&typeof body.data==="object"&&!Array.isArray(body.data)?body.data as Record<string,unknown>:{};const fields=Array.isArray(form.schema?.fields)?form.schema.fields as Field[]:[];const errors=validate(fields,values);if(errors.length)return NextResponse.json({success:false,error:"Form validation failed.",validationErrors:errors},{status:400});const submission=await supabase.from("firm_form_submissions").insert({firm_id:link.firm_id,form_definition_id:form.id,matter_id:link.matter_id,prospect_id:link.prospect_id,submitted_by:null,status:"submitted",data:values}).select("id,created_at").single();if(submission.error)throw new Error(submission.error.message);await supabase.from("form_share_links").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",link.id);return NextResponse.json({success:true,submission:submission.data});}catch(e){return NextResponse.json({success:false,error:e instanceof Error?e.message:"Unable to submit form."},{status:400});}}
