"use client";
import {FormEvent,useEffect,useState} from "react";
import {Bot,Clock3,MessageSquareText,ShieldCheck} from "lucide-react";
type Payload={success:boolean;error?:string;review?:{title?:string;reviewerLabel?:string;allowComment?:boolean;allowAiReview?:boolean;expiresAt?:string};thread?:{title:string;description?:string|null;thread_type:string};messages?:Array<{id:string;body:string;message_type:string;created_at:string}>;events?:Array<{id:string;event_type:string;author_label?:string|null;body?:string|null;created_at:string}>};
export default function ExternalReviewPage({params}:{params:Promise<{token:string}>}){
 const[token,setToken]=useState("");const[data,setData]=useState<Payload>({success:true});const[comment,setComment]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{void params.then(x=>setToken(x.token))},[params]);
 async function load(){if(!token)return;const r=await fetch("/api/external-review/"+encodeURIComponent(token),{cache:"no-store"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Review link unavailable.");setData(p)}
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:"Review link unavailable."))},[token]);
 async function post(action:string,body:Record<string,unknown>={}){setBusy(true);setMessage("");try{const r=await fetch("/api/external-review/"+encodeURIComponent(token),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Action failed.");await load();setMessage(p.message||"Saved.")}catch(e){setMessage(e instanceof Error?e.message:"Action failed.")}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();if(!comment.trim())return;await post("comment",{body:comment});setComment("")}
 if(data.error||(!data.thread&&message))return <main className="grid min-h-screen place-items-center bg-[#eef2ef] p-6"><div className="max-w-lg rounded-[1.7rem] bg-white p-7 shadow-xl"><ShieldCheck className="h-7 w-7 text-[#0f5b49]"/><h1 className="mt-4 text-xl font-semibold">External review unavailable</h1><p className="mt-2 text-sm text-slate-500">{data.error||message}</p></div></main>;
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-5xl space-y-5">
  <section className="rounded-[2rem] bg-[#082b22] p-7 text-white"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#d8bb79]">TSIDKENU secure external review</p><h1 className="mt-3 text-3xl font-semibold">{data.review?.title||data.thread?.title||"Review"}</h1><p className="mt-3 text-sm text-white/60">{data.thread?.description||"Only material explicitly shared by the firm is visible here."}</p><div className="mt-5 flex flex-wrap gap-3 text-xs text-white/55"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>Expires {data.review?.expiresAt?new Date(data.review.expiresAt).toLocaleString():"—"}</span><span className="inline-flex items-center gap-1"><ShieldCheck className="h-3.5 w-3.5"/>No access to the rest of the firm workspace</span></div></section>
  {message&&<div className="rounded-xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
  <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><MessageSquareText className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-lg font-semibold">Shared material</h2></div><div className="mt-4 space-y-3">{(data.messages??[]).map(m=><article key={m.id} className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">{m.message_type.replaceAll("_"," ")} · {new Date(m.created_at).toLocaleString()}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{m.body}</p></article>)}{!(data.messages??[]).length&&<p className="text-sm text-slate-500">No shared messages.</p>}</div></section>
  {(data.events??[]).filter(e=>e.event_type==="comment").length>0&&<section className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><h2 className="font-semibold">External comments</h2><div className="mt-3 space-y-2">{(data.events??[]).filter(e=>e.event_type==="comment").map(e=><div key={e.id} className="rounded-xl border border-slate-100 p-3"><p className="text-xs font-bold">{e.author_label||"Reviewer"}</p><p className="mt-1 text-sm text-slate-600">{e.body}</p></div>)}</div></section>}
  <div className="grid gap-4 md:grid-cols-2">{data.review?.allowComment&&<form onSubmit={submit} className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><h2 className="font-semibold">Add review comment</h2><textarea value={comment} onChange={e=>setComment(e.target.value)} className="mt-3 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none" placeholder="Comment only on the material shared with you…"/><button disabled={busy||!comment.trim()} className="mt-3 rounded-xl bg-[#082b22] px-4 py-2.5 text-sm font-bold text-white">Submit comment</button></form>}{data.review?.allowAiReview&&<div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><Bot className="h-5 w-5 text-[#0f5b49]"/><h2 className="mt-3 font-semibold">Request AI review</h2><p className="mt-2 text-sm leading-6 text-slate-500">You can request a review, but an authorized firm user must run it. External users cannot directly execute the firm's AI or turn AI output into approved legal work.</p><button disabled={busy} onClick={()=>void post("request_ai_review")} className="mt-4 rounded-xl border border-[#0b493b] px-4 py-2.5 text-sm font-bold text-[#0b493b]">Request AI review</button></div>}</div>
 </div></main>
}
