"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Banknote, CirclePlus, FileText, Landmark, Receipt, TrendingDown, TrendingUp, WalletCards } from "lucide-react";

type Invoice={id:string;matter_id:string;invoice_number?:string|null;description?:string|null;amount_xaf:number;paid_xaf?:number;status:string;due_date?:string|null;issued_at?:string|null};
type Ledger={id:string;matter_id?:string|null;invoice_id?:string|null;entry_type:string;amount_xaf:number;direction:string;payment_method?:string|null;reference?:string|null;description?:string|null;occurred_at:string};
type Matter={id:string;title:string;client_name:string};
type Payload={success:boolean;error?:string;writable?:boolean;metrics?:{billed:number;paidOnInvoices:number;cashIn:number;cashOut:number;outstanding:number;overdueCount:number};invoices?:Invoice[];ledger?:Ledger[];matters?:Matter[]};
const field="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-[#7da797]";
const money=(n:number)=>`${new Intl.NumberFormat("fr-CM",{maximumFractionDigits:0}).format(Number(n||0))} XAF`;

export default function FinancePage(){
 const[data,setData]=useState<Payload>({success:true,invoices:[],ledger:[],matters:[]});const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[tab,setTab]=useState<"overview"|"invoice"|"entry">("overview");
 const[matterId,setMatterId]=useState("");const[amount,setAmount]=useState("");const[description,setDescription]=useState("");const[dueDate,setDueDate]=useState("");const[entryType,setEntryType]=useState("payment");const[invoiceId,setInvoiceId]=useState("");const[paymentMethod,setPaymentMethod]=useState("");const[reference,setReference]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/finance",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load finance.");setData(p)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load finance.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const matterMap=useMemo(()=>new Map((data.matters??[]).map(m=>[m.id,m])),[data.matters]);
 async function createInvoice(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/finance",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createInvoice",matterId,amountXaf:Number(amount),description,dueDate:dueDate||null})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to create invoice.");setAmount("");setDescription("");setDueDate("");setTab("overview");await load();setMessage("Invoice created and linked to the matter.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to create invoice.")}finally{setBusy(false)}}
 async function recordEntry(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/finance",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"recordEntry",entryType,amountXaf:Number(amount),matterId:matterId||null,invoiceId:invoiceId||null,paymentMethod,reference,description})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to record finance entry.");setAmount("");setDescription("");setReference("");setPaymentMethod("");setTab("overview");await load();setMessage("Finance entry recorded in the governed ledger.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to record finance entry.")}finally{setBusy(false)}}
 const m=data.metrics??{billed:0,paidOnInvoices:0,cashIn:0,cashOut:0,outstanding:0,overdueCount:0};
 return <main className="min-h-screen bg-[#eef2ef] p-3 text-slate-900 sm:p-5 lg:p-7"><div className="mx-auto max-w-[1760px] space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/workspace" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Workspace</Link>{data.writable&&<div className="flex gap-2"><button onClick={()=>setTab("invoice")} className="rounded-xl bg-[#0b493b] px-4 py-2.5 text-sm font-bold text-white">New invoice</button><button onClick={()=>setTab("entry")} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">Record payment/expense</button></div>}</div>
  <section className="overflow-hidden rounded-[2rem] bg-[#082b22] text-white shadow-[0_28px_80px_rgba(8,43,34,.16)]"><div className="grid gap-0 xl:grid-cols-[1fr_440px]"><div className="p-6 md:p-8 xl:p-10"><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#d8bb79]">Finance operating system</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Money stays attached to legal work.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Invoices, payments, expenses, disbursements and collections are linked to the matter that created them, with a separate auditable ledger.</p></div><div className="grid grid-cols-2 gap-px bg-white/10"><Hero label="Outstanding" value={money(m.outstanding)}/><Hero label="Cash in" value={money(m.cashIn)}/><Hero label="Cash out" value={money(m.cashOut)}/><Hero label="Overdue" value={String(m.overdueCount)}/></div></div></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  {loading?<div className="rounded-3xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-500">Loading finance…</div>:<>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={FileText} label="Billed" value={money(m.billed)}/><Metric icon={TrendingUp} label="Invoice payments" value={money(m.paidOnInvoices)}/><Metric icon={WalletCards} label="Ledger receipts" value={money(m.cashIn)}/><Metric icon={TrendingDown} label="Ledger outflow" value={money(m.cashOut)}/></section>
  {tab!=="overview"&&<section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#0f5b49]">{tab==="invoice"?"Billing":"Ledger"}</p><h2 className="mt-1 text-2xl font-semibold">{tab==="invoice"?"Create matter invoice":"Record payment, expense or disbursement"}</h2></div><button onClick={()=>setTab("overview")} className="text-sm font-bold text-slate-500">Close</button></div>{tab==="invoice"?<form onSubmit={createInvoice} className="mt-5 grid gap-3 md:grid-cols-2"><select required className={field} value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">Select matter</option>{(data.matters??[]).map(x=><option key={x.id} value={x.id}>{x.client_name} — {x.title}</option>)}</select><input required className={field} inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount XAF"/><input className={field} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description / fee stage"/><input className={field} type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/><button disabled={busy} className="md:col-span-2 rounded-xl bg-[#082b22] px-4 py-3 text-sm font-bold text-white">{busy?"Saving…":"Create invoice"}</button></form>:<form onSubmit={recordEntry} className="mt-5 grid gap-3 md:grid-cols-2"><select className={field} value={entryType} onChange={e=>setEntryType(e.target.value)}><option value="payment">Payment</option><option value="receipt">Receipt</option><option value="expense">Expense</option><option value="disbursement">Disbursement</option><option value="adjustment">Adjustment</option></select><input required className={field} inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount XAF"/><select className={field} value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">No matter selected</option>{(data.matters??[]).map(x=><option key={x.id} value={x.id}>{x.client_name} — {x.title}</option>)}</select><select className={field} value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option value="">No invoice selected</option>{(data.invoices??[]).map(x=><option key={x.id} value={x.id}>{x.invoice_number||x.id} — {money(x.amount_xaf)}</option>)}</select><input className={field} value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} placeholder="Method: cash / bank / MoMo / Wave"/><input className={field} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Reference / receipt no."/><textarea className={`${field} md:col-span-2 min-h-24`} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description"/><button disabled={busy} className="md:col-span-2 rounded-xl bg-[#082b22] px-4 py-3 text-sm font-bold text-white">{busy?"Saving…":"Record ledger entry"}</button></form>}</section>}
  <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Invoices</h2><span className="text-xs font-bold text-slate-400">{data.invoices?.length||0}</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-[10px] uppercase tracking-[.14em] text-slate-400"><tr><th className="pb-3">Invoice</th><th className="pb-3">Matter</th><th className="pb-3">Billed</th><th className="pb-3">Paid</th><th className="pb-3">Status</th><th className="pb-3">Due</th></tr></thead><tbody className="divide-y divide-slate-100">{(data.invoices??[]).map(x=><tr key={x.id}><td className="py-3 font-semibold">{x.invoice_number||"—"}</td><td className="py-3 text-slate-500">{matterMap.get(x.matter_id)?.title||"Matter"}</td><td className="py-3">{money(x.amount_xaf)}</td><td className="py-3">{money(Number(x.paid_xaf||0))}</td><td className="py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase">{x.status}</span></td><td className="py-3 text-slate-500">{x.due_date?new Date(x.due_date).toLocaleDateString():"—"}</td></tr>)}</tbody></table>{!(data.invoices??[]).length&&<p className="py-8 text-sm text-slate-500">No invoices yet.</p>}</div></div><div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Recent ledger</h2><Receipt className="h-5 w-5 text-[#0f5b49]"/></div><div className="mt-4 space-y-2">{(data.ledger??[]).slice(0,10).map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className={`grid h-9 w-9 place-items-center rounded-xl ${x.direction==="in"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{x.direction==="in"?<Banknote className="h-4 w-4"/>:<Landmark className="h-4 w-4"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{x.description||x.entry_type}</p><p className="mt-0.5 text-[11px] text-slate-500">{x.reference||x.payment_method||new Date(x.occurred_at).toLocaleDateString()}</p></div><p className="text-sm font-bold">{x.direction==="out"?"−":"+"}{money(x.amount_xaf)}</p></div>)}{!(data.ledger??[]).length&&<p className="py-8 text-sm text-slate-500">No ledger entries yet.</p>}</div></div></section></>}
 </div></main>;
}
function Hero({label,value}:{label:string;value:string}){return <div className="bg-white/[.045] p-5"><p className="text-[9px] font-black uppercase tracking-[.16em] text-white/40">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
function Metric({icon:Icon,label,value}:{icon:typeof CirclePlus;label:string;value:string}){return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-4 shadow-sm"><div className="rounded-xl bg-[#edf4f0] p-2.5 text-[#0f5b49] w-fit"><Icon className="h-4 w-4"/></div><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-[.15em] text-slate-400">{label}</p></div>}
