"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,AtSign,CheckCircle2,MessageSquareText,UserRound} from "lucide-react";
import { useLocale } from "@/components/LocaleProvider";
import { formatDate } from "@/lib/i18n";

type Item={id:string;matter_id?:string|null;work_scope:string;title:string;description?:string|null;status:string;priority:string;assigned_to?:string|null;due_at?:string|null};
type Matter={id:string;title:string;client_name:string;case_reference?:string|null};
type Lawyer={id:string;full_name:string;role?:string|null};
type Comment={id:string;work_item_id:string;author_id?:string|null;body:string;mentions?:string[];created_at:string};
type Payload={success:boolean;error?:string;items?:Item[];matters?:Matter[];lawyers?:Lawyer[];comments?:Comment[]};

export default function WorkItemPage({params}:{params:Promise<{workItemId:string}>}){
 const{locale,t}=useLocale();
 const[id,setId]=useState("");const[data,setData]=useState<Payload>({success:true});const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[comment,setComment]=useState("");const[mentions,setMentions]=useState<string[]>([]);const[busy,setBusy]=useState(false);
 useEffect(()=>{void params.then(x=>setId(x.workItemId))},[params]);
 async function load(){if(!id)return;setLoading(true);try{const r=await fetch("/api/workroom",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load work item.");setData(p)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load work item.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[id]);
 const item=(data.items??[]).find(x=>x.id===id);const matter=(data.matters??[]).find(x=>x.id===item?.matter_id);const lawyerMap=useMemo(()=>new Map((data.lawyers??[]).map(x=>[x.id,x])),[data.lawyers]);const comments=(data.comments??[]).filter(x=>x.work_item_id===id);
 async function postComment(e:FormEvent){e.preventDefault();if(!comment.trim())return;setBusy(true);try{const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"comment",workItemId:id,body:comment,mentions})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to post comment.");setComment("");setMentions([]);await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to post comment.")}finally{setBusy(false)}}
 async function assign(value:string){setBusy(true);try{const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"assign",id,assignedTo:value||null})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Assignment failed.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Assignment failed.")}finally{setBusy(false)}}
 async function updateStatus(status:string){setBusy(true);setMessage("");try{const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"status",id,status})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Status update failed.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Status update failed.")}finally{setBusy(false)}}
 if(loading)return <main className="min-h-screen bg-[#eef2ef] p-6 text-slate-600">Loading work item…</main>;
 if(!item)return <main className="min-h-screen bg-[#eef2ef] p-6"><Link href="/workroom">{t("workroom.back","Back to Workroom")}</Link><p className="mt-4">{message||"Work item not found."}</p></main>;
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-7"><div className="mx-auto max-w-6xl space-y-5">
  <Link href="/workroom" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>{t("workroom.title","Workroom")}</Link>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#d8bb79]">{item.work_scope} work · {item.priority}</p><h1 className="mt-2 text-3xl font-semibold md:text-4xl">{item.title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/65">{item.description||"No additional instructions."}</p>{matter&&<Link href={"/matters/"+matter.id} className="mt-4 inline-block text-xs font-bold text-[#d8bb79]">{matter.case_reference||"Case"} · {matter.client_name} · {matter.title}</Link>}</div><div className="min-w-56"><p className="text-[9px] font-black uppercase tracking-[.15em] text-white/40">{t("workroom.responsible","Responsible")}</p><select disabled={busy} value={item.assigned_to||""} onChange={e=>void assign(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/10 px-3 py-2.5 text-sm text-white"><option value="" className="text-slate-900">{t("workroom.unassigned","Unassigned")}</option>{(data.lawyers??[]).map(x=><option className="text-slate-900" key={x.id} value={x.id}>{x.full_name} · {x.role||"member"}</option>)}</select></div></div></section>
  {message&&<div className="rounded-xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
  <div className="grid gap-5 lg:grid-cols-[1fr_320px]">
   <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><MessageSquareText className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-xl font-semibold">{t("workroom.teamConversation","Team conversation")}</h2></div><div className="mt-5 space-y-3">{comments.map(x=><article key={x.id} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-2"><UserRound className="h-4 w-4 text-slate-400"/><p className="text-xs font-bold">{x.author_id?lawyerMap.get(x.author_id)?.full_name||"Firm member":"Firm member"}</p><p className="text-[10px] text-slate-400">{formatDate(locale,x.created_at,{dateStyle:"medium",timeStyle:"short"})}</p></div><p className="mt-2 text-sm leading-6 text-slate-700">{x.body}</p>{(x.mentions??[]).length>0&&<p className="mt-2 text-[10px] font-bold text-[#0f5b49]">Mentioned: {(x.mentions??[]).map(m=>lawyerMap.get(m)?.full_name||m).join(", ")}</p>}</article>)}{!comments.length&&<p className="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-400">{t("workroom.noComments","No comments yet.")}</p>}</div><form onSubmit={postComment} className="mt-5 border-t border-slate-100 pt-5"><textarea required value={comment} onChange={e=>setComment(e.target.value)} className="min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none" placeholder="Update, question, hand-off or review note…"/><div className="mt-3 flex flex-wrap gap-2">{(data.lawyers??[]).map(x=><label key={x.id} className={"cursor-pointer rounded-full border px-2.5 py-1 text-[10px] font-bold "+(mentions.includes(x.id)?"border-[#0f5b49] bg-[#edf4f0] text-[#0f5b49]":"border-slate-200 text-slate-500")}><input type="checkbox" className="sr-only" checked={mentions.includes(x.id)} onChange={e=>setMentions(current=>e.target.checked?[...current,x.id]:current.filter(y=>y!==x.id))}/>@{x.full_name}</label>)}</div><div className="mt-4 flex justify-end"><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-[#082b22] px-4 py-2.5 text-sm font-bold text-white"><AtSign className="h-4 w-4"/>{busy?t("workroom.posting","Posting…"):t("workroom.post","Post update")}</button></div></form></section>
   <aside className="space-y-4"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">{t("workroom.execution","Execution state")}</p><label className="mt-3 block text-[9px] font-black uppercase tracking-[.14em] text-slate-400">{t("workroom.status","Status")}<select disabled={busy} value={item.status} onChange={e=>void updateStatus(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-800"><option value="open">{t("workroom.open","Open")}</option><option value="in_progress">{t("workroom.inProgress","In progress")}</option><option value="waiting">{t("workroom.waiting","Waiting")}</option><option value="review">{t("workroom.review","Review")}</option><option value="completed">{t("workroom.completed","Completed")}</option><option value="cancelled">{t("workroom.cancelled","Cancelled")}</option></select></label><p className="mt-3 text-xs text-slate-500">{item.due_at?"Due "+formatDate(locale,item.due_at,{dateStyle:"medium",timeStyle:"short"}):t("workroom.noDeadline","No deadline assigned.")}</p></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><CheckCircle2 className="h-5 w-5 text-[#0f5b49]"/><p className="mt-3 text-sm font-semibold">Accountability is attached to the work item</p><p className="mt-2 text-xs leading-5 text-slate-500">Assignments, comments and mentions remain part of the firm record rather than disappearing into a separate chat.</p></div></aside>
  </div>
 </div></main>
}
