"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, CirclePlus, Clock3, MessageSquareText, Search, ShieldCheck, Sparkles, Users2 } from "lucide-react";

type Matter={id:string;title:string;client_name:string;case_reference?:string|null};
type Lawyer={id:string;full_name:string;role?:string|null};
type Work={id:string;matter_id?:string|null;work_scope:string;title:string;description?:string|null;status:string;priority:string;assigned_to?:string|null;due_at?:string|null};
type Thread={id:string;matter_id?:string|null;title:string;description?:string|null;thread_type:string;status:string;is_pinned:boolean;updated_at:string};
type Message={id:string;thread_id:string;body:string;created_by?:string|null;created_at:string};
type Decision={id:string;matter_id?:string|null;thread_id?:string|null;title:string;description?:string|null;decision_type:string;status:string;assigned_to?:string|null;due_at?:string|null;resolution?:string|null};
type Payload={success:boolean;error?:string;items?:Work[];matters?:Matter[];lawyers?:Lawyer[];threads?:Thread[];messages?:Message[];decisions?:Decision[]};

const field="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-[#7da797]";

export default function WorkroomV2(){
 const[data,setData]=useState<Payload>({success:true}); const[tab,setTab]=useState<"pulse"|"conversations"|"work"|"decisions">("pulse"); const[query,setQuery]=useState(""); const[message,setMessage]=useState(""); const[busy,setBusy]=useState(false);
 const[openThread,setOpenThread]=useState(false); const[openWork,setOpenWork]=useState(false); const[openDecision,setOpenDecision]=useState(false);
 const[threadForm,setThreadForm]=useState({title:"",description:"",threadType:"discussion",matterId:""});
 const[workForm,setWorkForm]=useState({title:"",description:"",workScope:"case",matterId:"",priority:"normal",dueAt:""});
 const[decisionForm,setDecisionForm]=useState({title:"",description:"",decisionType:"decision",matterId:"",assignedTo:"",dueAt:""});
 async function load(){try{const r=await fetch("/api/workroom",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load Workroom.");setData(p)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load Workroom.")}}
 useEffect(()=>{void load()},[]);
 const lawyerMap=useMemo(()=>new Map((data.lawyers??[]).map(x=>[x.id,x])),[data.lawyers]);
 const matterMap=useMemo(()=>new Map((data.matters??[]).map(x=>[x.id,x])),[data.matters]);
 const threads=(data.threads??[]).filter(x=>!query||[x.title,x.description,x.thread_type].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase()));
 const work=(data.items??[]).filter(x=>!query||[x.title,x.description,x.work_scope,x.priority].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase()));
 const decisions=(data.decisions??[]).filter(x=>!query||[x.title,x.description,x.decision_type,x.status].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase()));
 const openDecisions=decisions.filter(x=>x.status==="open"); const overdue=work.filter(x=>x.due_at&&new Date(x.due_at)<new Date()&&x.status!=="completed"); const active=work.filter(x=>["open","in_progress","review","waiting"].includes(x.status));

 async function post(action:string,payload:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Workroom action failed.");await load();return true}catch(e){setMessage(e instanceof Error?e.message:"Workroom action failed.");return false}finally{setBusy(false)}}
 async function createThread(e:FormEvent){e.preventDefault();if(await post("create_thread",{...threadForm,matterId:threadForm.matterId||null})){setOpenThread(false);setThreadForm({title:"",description:"",threadType:"discussion",matterId:""})}}
 async function createWork(e:FormEvent){e.preventDefault();if(await post("create",{...workForm,matterId:workForm.matterId||null,dueAt:workForm.dueAt||null})){setOpenWork(false);setWorkForm({title:"",description:"",workScope:"case",matterId:"",priority:"normal",dueAt:""})}}
 async function createDecision(e:FormEvent){e.preventDefault();if(await post("create_decision",{...decisionForm,matterId:decisionForm.matterId||null,assignedTo:decisionForm.assignedTo||null,dueAt:decisionForm.dueAt||null})){setOpenDecision(false);setDecisionForm({title:"",description:"",decisionType:"decision",matterId:"",assignedTo:"",dueAt:""})}}

 return <main className="min-h-screen bg-[#eef2ef] p-3 text-slate-900 sm:p-5 lg:p-7"><div className="mx-auto max-w-[1850px] space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/workspace" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Workspace</Link><div className="flex flex-wrap gap-2"><button onClick={()=>setOpenThread(true)} className="rounded-xl border border-[#0b493b] bg-white px-4 py-2.5 text-sm font-bold text-[#0b493b]">New conversation</button><button onClick={()=>setOpenWork(true)} className="rounded-xl border border-[#0b493b] bg-white px-4 py-2.5 text-sm font-bold text-[#0b493b]">Assign work</button><button onClick={()=>setOpenDecision(true)} className="rounded-xl bg-[#0b493b] px-4 py-2.5 text-sm font-bold text-white">Request decision</button></div></div>

  <section className="overflow-hidden rounded-[2rem] bg-[#082b22] text-white"><div className="grid xl:grid-cols-[1fr_470px]"><div className="p-6 md:p-8 xl:p-10"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">TSIDKENU Workroom</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Conversation, execution and decisions — in the same legal context.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Instead of copying Slack, Workroom keeps team discussion tied to cases, work, approvals and accountability.</p></div><div className="grid grid-cols-2 gap-px bg-white/10"><Metric label="Active work" value={active.length}/><Metric label="Open decisions" value={openDecisions.length}/><Metric label="Overdue" value={overdue.length}/><Metric label="Conversations" value={data.threads?.length||0}/></div></div></section>

  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  <div className="grid gap-4 xl:grid-cols-[260px_1fr]">
   <aside className="rounded-[1.5rem] border border-slate-200 bg-white p-3 shadow-sm"><p className="px-3 py-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Workroom views</p>{[["pulse","Pulse"],["conversations","Conversations"],["work","Work"],["decisions","Decisions & approvals"]].map(([key,label])=><button key={key} onClick={()=>setTab(key as typeof tab)} className={"mb-1 flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-sm font-bold "+(tab===key?"bg-[#edf4f0] text-[#0f5b49]":"text-slate-600 hover:bg-slate-50")}><span>{label}</span>{key==="decisions"&&openDecisions.length>0?<span className="rounded-full bg-[#0f5b49] px-2 py-0.5 text-[10px] text-white">{openDecisions.length}</span>:null}</button>)}</aside>
   <div className="space-y-4">
    <label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4"><Search className="h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full py-3 text-sm outline-none" placeholder="Search conversations, work, cases or decisions…"/></label>

    {tab==="pulse"&&<div className="grid gap-4 lg:grid-cols-2"><Panel title="Needs attention" icon={ShieldCheck}>{openDecisions.slice(0,6).map(x=><DecisionCard key={x.id} item={x} matterMap={matterMap} lawyerMap={lawyerMap}/>)}{!openDecisions.length&&<Empty text="No unresolved decisions."/ >}</Panel><Panel title="Active execution" icon={Clock3}>{active.slice(0,8).map(x=><WorkCard key={x.id} item={x} matterMap={matterMap}/>)}</Panel><Panel title="Latest conversations" icon={MessageSquareText}>{threads.slice(0,7).map(x=><ThreadCard key={x.id} item={x} matterMap={matterMap} messages={data.messages??[]}/>)}</Panel><Panel title="Overdue work" icon={CheckCircle2}>{overdue.slice(0,7).map(x=><WorkCard key={x.id} item={x} matterMap={matterMap}/>)}{!overdue.length&&<Empty text="Nothing overdue."/ >}</Panel></div>}

    {tab==="conversations"&&<div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{threads.map(x=><ThreadCard key={x.id} item={x} matterMap={matterMap} messages={data.messages??[]}/>)}</div>}
    {tab==="work"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{work.map(x=><WorkCard key={x.id} item={x} matterMap={matterMap}/>)}</div>}
    {tab==="decisions"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{decisions.map(x=><DecisionCard key={x.id} item={x} matterMap={matterMap} lawyerMap={lawyerMap}/>)}</div>}
   </div>
  </div>
 </div>

 {openThread&&<Modal title="Start conversation" onClose={()=>setOpenThread(false)}><form onSubmit={createThread} className="grid gap-3"><input required className={field} value={threadForm.title} onChange={e=>setThreadForm({...threadForm,title:e.target.value})} placeholder="Conversation title"/><textarea className={field+" min-h-24"} value={threadForm.description} onChange={e=>setThreadForm({...threadForm,description:e.target.value})} placeholder="Purpose / context"/><select className={field} value={threadForm.threadType} onChange={e=>setThreadForm({...threadForm,threadType:e.target.value})}><option value="discussion">Discussion</option><option value="case_room">Case room</option><option value="office">Office</option><option value="finance">Finance</option><option value="announcement">Announcement</option></select><MatterSelect value={threadForm.matterId} onChange={value=>setThreadForm({...threadForm,matterId:value})} matters={data.matters??[]}/><button disabled={busy} className="rounded-xl bg-[#082b22] px-4 py-3 text-sm font-bold text-white">Create conversation</button></form></Modal>}
 {openWork&&<Modal title="Assign work" onClose={()=>setOpenWork(false)}><form onSubmit={createWork} className="grid gap-3"><input required className={field} value={workForm.title} onChange={e=>setWorkForm({...workForm,title:e.target.value})} placeholder="Work title"/><textarea className={field+" min-h-24"} value={workForm.description} onChange={e=>setWorkForm({...workForm,description:e.target.value})} placeholder="Expected result"/><MatterSelect value={workForm.matterId} onChange={value=>setWorkForm({...workForm,matterId:value})} matters={data.matters??[]}/><select className={field} value={workForm.priority} onChange={e=>setWorkForm({...workForm,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><input className={field} type="datetime-local" value={workForm.dueAt} onChange={e=>setWorkForm({...workForm,dueAt:e.target.value})}/><button disabled={busy} className="rounded-xl bg-[#082b22] px-4 py-3 text-sm font-bold text-white">Create work</button></form></Modal>}
 {openDecision&&<Modal title="Request decision / approval" onClose={()=>setOpenDecision(false)}><form onSubmit={createDecision} className="grid gap-3"><input required className={field} value={decisionForm.title} onChange={e=>setDecisionForm({...decisionForm,title:e.target.value})} placeholder="What needs to be decided?"/><textarea className={field+" min-h-24"} value={decisionForm.description} onChange={e=>setDecisionForm({...decisionForm,description:e.target.value})} placeholder="Context, options or requested outcome"/><select className={field} value={decisionForm.decisionType} onChange={e=>setDecisionForm({...decisionForm,decisionType:e.target.value})}><option value="decision">Decision</option><option value="approval">Approval</option><option value="review">Review</option><option value="handoff">Handoff</option></select><MatterSelect value={decisionForm.matterId} onChange={value=>setDecisionForm({...decisionForm,matterId:value})} matters={data.matters??[]}/><select className={field} value={decisionForm.assignedTo} onChange={e=>setDecisionForm({...decisionForm,assignedTo:e.target.value})}><option value="">Any responsible reviewer</option>{(data.lawyers??[]).map(x=><option key={x.id} value={x.id}>{x.full_name} · {x.role||"member"}</option>)}</select><input className={field} type="datetime-local" value={decisionForm.dueAt} onChange={e=>setDecisionForm({...decisionForm,dueAt:e.target.value})}/><button disabled={busy} className="rounded-xl bg-[#082b22] px-4 py-3 text-sm font-bold text-white">Request decision</button></form></Modal>}
 </main>
}

function Metric({label,value}:{label:string;value:number}){return <div className="bg-white/[.045] p-5"><p className="text-[9px] font-black uppercase tracking-[.16em] text-white/40">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>}
function Panel({title,icon:Icon,children}:{title:string;icon:typeof Sparkles;children:React.ReactNode}){return <section className="rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-[#0f5b49]"/><h2 className="font-semibold">{title}</h2></div><div className="mt-3 space-y-2">{children}</div></section>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-xs text-slate-400">{text}</p>}
function MatterSelect({value,onChange,matters}:{value:string;onChange:(value:string)=>void;matters:Matter[]}){return <select className={field} value={value} onChange={e=>onChange(e.target.value)}><option value="">No case link</option>{matters.map(x=><option key={x.id} value={x.id}>{x.case_reference||"CASE"} — {x.client_name} — {x.title}</option>)}</select>}
function ThreadCard({item,matterMap,messages}:{item:Thread;matterMap:Map<string,Matter>;messages:Message[]}){const count=messages.filter(x=>x.thread_id===item.id).length;return <Link href={"/workroom/thread/"+item.id} className="block rounded-xl border border-slate-100 bg-[#fbfcfb] p-4 hover:border-[#7da797]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#0f5b49]">{item.thread_type.replaceAll("_"," ")}</p><p className="mt-1 font-semibold">{item.title}</p></div>{item.is_pinned&&<span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-black text-amber-700">PINNED</span>}</div>{item.description&&<p className="mt-2 text-xs leading-5 text-slate-500">{item.description}</p>}<p className="mt-3 text-[11px] text-slate-400">{item.matter_id?matterMap.get(item.matter_id)?.case_reference+" · ":""}{count} message{count===1?"":"s"}</p></Link>}
function WorkCard({item,matterMap}:{item:Work;matterMap:Map<string,Matter>}){return <Link href={"/workroom/"+item.id} className="block rounded-xl border border-slate-100 bg-[#fbfcfb] p-4 hover:border-[#7da797]"><div className="flex items-start justify-between gap-2"><p className="font-semibold">{item.title}</p><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black uppercase">{item.priority}</span></div><p className="mt-2 text-xs text-slate-500">{item.status.replaceAll("_"," ")}{item.matter_id?" · "+(matterMap.get(item.matter_id)?.case_reference||"Case"):""}</p></Link>}
function DecisionCard({item,matterMap,lawyerMap}:{item:Decision;matterMap:Map<string,Matter>;lawyerMap:Map<string,Lawyer>}){return <article className="rounded-xl border border-slate-100 bg-[#fbfcfb] p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#0f5b49]">{item.decision_type}</p><p className="mt-1 font-semibold">{item.title}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black uppercase">{item.status}</span></div><p className="mt-2 text-xs text-slate-500">{item.matter_id?(matterMap.get(item.matter_id)?.case_reference||"Case")+" · ":""}{item.assigned_to?lawyerMap.get(item.assigned_to)?.full_name||"Assigned reviewer":"Open reviewer"}</p></article>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl rounded-[1.7rem] bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-semibold">{title}</h2><button onClick={onClose} className="rounded-lg px-3 py-2 text-sm text-slate-500">Close</button></div>{children}</div></div>}
