"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, CirclePlus, Columns3, Search, Users2 } from "lucide-react";

type Item={id:string;matter_id?:string|null;work_scope:string;title:string;description?:string|null;status:string;priority:string;due_at?:string|null};
type Matter={id:string;title:string;client_name:string};
type Payload={success:boolean;error?:string;items?:Item[];matters?:Matter[]};
const statuses=["open","in_progress","waiting","review","completed"];
const field="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none";

export default function WorkroomPage(){
 const[data,setData]=useState<Payload>({success:true,items:[],matters:[]}); const[loading,setLoading]=useState(true); const[query,setQuery]=useState(""); const[open,setOpen]=useState(false); const[message,setMessage]=useState(""); const[busy,setBusy]=useState(false);
 const[form,setForm]=useState({title:"",description:"",workScope:"case",matterId:"",priority:"normal",dueAt:""});
 async function load(){setLoading(true);try{const r=await fetch("/api/workroom",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load workroom.");setData(p)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load workroom.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const matterMap=useMemo(()=>new Map((data.matters??[]).map(x=>[x.id,x])),[data.matters]);
 const visible=(data.items??[]).filter(x=>!query.trim()||[x.title,x.description,x.work_scope,x.priority].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase()));
 async function create(event:FormEvent){event.preventDefault();setBusy(true);try{const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",...form,matterId:form.matterId||null,dueAt:form.dueAt||null})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to create work item.");setOpen(false);setForm({title:"",description:"",workScope:"case",matterId:"",priority:"normal",dueAt:""});await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to create work item.")}finally{setBusy(false)}}
 async function updateStatus(id:string,status:string){const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"status",id,status})});const p=await r.json();if(!r.ok||!p.success){setMessage(p.error||"Unable to update work.");return}await load()}
 return <main className="min-h-screen bg-[#eef2ef] p-3 text-slate-900 sm:p-5 lg:p-7"><div className="mx-auto max-w-[1800px] space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/workspace" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Workspace</Link><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#0b493b] px-4 py-2.5 text-sm font-bold text-white"><CirclePlus className="h-4 w-4"/>Assign work</button></div>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-8 xl:p-10"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">Firm Workroom</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Case work, office work and follow-up in one queue.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Assignments and status follow-up stay linked to the case, client or office operation that created them.</p></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  <section className="rounded-[1.5rem] border border-slate-200 bg-white p-4"><label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3"><Search className="h-4 w-4 text-slate-400"/><input className="w-full py-3 text-sm outline-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search work, case, priority or scope…"/></label></section>
  {loading?<div className="rounded-3xl bg-white p-12 text-center text-sm text-slate-500">Loading firm work…</div>:<section className="grid gap-4 xl:grid-cols-5">{statuses.map(status=>{const rows=visible.filter(x=>x.status===status);return <div key={status} className="rounded-[1.4rem] border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-center justify-between px-1 py-2"><div className="flex items-center gap-2">{status==="completed"?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<Columns3 className="h-4 w-4 text-slate-400"/>}<h2 className="text-sm font-bold capitalize">{status.replaceAll("_"," ")}</h2></div><span className="text-xs font-bold text-slate-400">{rows.length}</span></div><div className="mt-2 space-y-2">{rows.map(item=><article key={item.id} className="rounded-xl border border-slate-100 bg-[#fbfcfb] p-3"><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold">{item.title}</p><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[9px] font-black uppercase">{item.priority}</span></div>{item.description&&<p className="mt-1.5 line-clamp-3 text-xs leading-5 text-slate-500">{item.description}</p>}<div className="mt-3 space-y-1 text-[11px] text-slate-400">{item.matter_id&&<p>{matterMap.get(item.matter_id)?.client_name} · {matterMap.get(item.matter_id)?.title}</p>}<p className="capitalize">{item.work_scope} work{item.due_at?" · due "+new Date(item.due_at).toLocaleDateString():""}</p></div><select value={item.status} onChange={e=>void updateStatus(item.id,e.target.value)} className="mt-3 w-full rounded-lg border border-slate-200 bg-white px-2 py-2 text-xs font-semibold">{statuses.concat("cancelled").map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></article>)}{!rows.length&&<p className="py-6 text-center text-xs text-slate-400">No items.</p>}</div></div>})}</section>}
 </div>
 {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" onClick={()=>!busy&&setOpen(false)}><form onSubmit={create} onClick={e=>e.stopPropagation()} className="w-full max-w-2xl rounded-[1.8rem] bg-white p-5 shadow-2xl"><div className="flex items-center gap-3"><Users2 className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-2xl font-semibold">Assign work</h2></div><div className="mt-5 grid gap-3 md:grid-cols-2"><input required className={field} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Work title"/><select className={field} value={form.workScope} onChange={e=>setForm({...form,workScope:e.target.value})}><option value="case">Case</option><option value="client">Client</option><option value="office">Office</option><option value="finance">Finance</option><option value="compliance">Compliance</option></select><select className={field} value={form.matterId} onChange={e=>setForm({...form,matterId:e.target.value})}><option value="">No case link</option>{(data.matters??[]).map(m=><option key={m.id} value={m.id}>{m.client_name} — {m.title}</option>)}</select><select className={field} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><input className={field} type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/><textarea className={field+" md:col-span-2 min-h-24"} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Instructions / expected result"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">Cancel</button><button disabled={busy} className="rounded-xl bg-[#082b22] px-4 py-2.5 text-sm font-bold text-white">{busy?"Saving…":"Create work item"}</button></div></form></div>}
 </main>
}