"use client";
import { useEffect, useState } from "react";

type Kind="decision"|"instruction"|"evidence"|"handoff";
type Decision={id:string;title:string;decision?:string|null;status:string};
type Instruction={id:string;instruction:string;confirmation_status:string};
type Evidence={id:string;title:string;verification_status:string};
type Handoff={id:string;purpose:string;status:string;external_professional?:string|null;scope_note?:string|null;authority_note?:string|null};
type AdaptiveData={decisions:Decision[];instructions:Instruction[];evidence:Evidence[];handoffs:Handoff[]};
const configs:{kind:Kind;title:string;placeholder:string}[]=[
 {kind:"decision",title:"Record decision",placeholder:"Decision or recommended course"},
 {kind:"instruction",title:"Record client instruction",placeholder:"Instruction received from the client"},
 {kind:"evidence",title:"Register evidence",placeholder:"Evidence or proposition to verify"},
 {kind:"handoff",title:"Prepare handoff",placeholder:"Purpose of the professional handoff"},
];

export default function AdaptiveMatterActions({matterId}:{matterId:string}){
 const[open,setOpen]=useState<Kind|null>(null);const[text,setText]=useState("");const[handoffProfessional,setHandoffProfessional]=useState("");const[handoffScope,setHandoffScope]=useState("");const[handoffAuthority,setHandoffAuthority]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState<string|null>(null);const[data,setData]=useState<AdaptiveData>({decisions:[],instructions:[],evidence:[],handoffs:[]});
 async function load(){try{const res=await fetch(`/api/matters/${matterId}/adaptive`,{cache:"no-store"});const json=await res.json();if(res.ok&&json.success)setData({decisions:json.decisions??[],instructions:json.instructions??[],evidence:json.evidence??[],handoffs:json.handoffs??[]});}catch{/* server-rendered summary remains available */}}
 useEffect(()=>{void load();},[matterId]);
 async function act(payload:Record<string,unknown>,successMessage:string){setBusy(true);setNotice(null);try{const res=await fetch(`/api/matters/${matterId}/adaptive`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const json=await res.json();if(!res.ok||!json.success)throw new Error(json.error||"Unable to update matter record.");setNotice(successMessage);await load();}catch(error){setNotice(error instanceof Error?error.message:"Unable to update matter record.");}finally{setBusy(false);}}
 async function submit(kind:Kind){if(!text.trim())return;const value=text.trim();const payload=kind==="decision"?{action:"record_decision",title:value.slice(0,100),decision:value}:kind==="instruction"?{action:"record_instruction",instruction:value,channel:"recorded"}:kind==="evidence"?{action:"record_evidence",title:value.slice(0,100),sourceKind:"matter_record",assertion:value}:{action:"create_handoff",purpose:value,externalProfessional:handoffProfessional.trim()||null,scopeNote:handoffScope.trim()||value,authorityNote:handoffAuthority.trim()||null};await act(payload,"Recorded in the governed matter record.");setText("");setHandoffProfessional("");setHandoffScope("");setHandoffAuthority("");setOpen(null);}
 return <div className="space-y-4 rounded-[1.5rem] border border-slate-200 bg-white p-5">
  <div className="flex flex-wrap gap-2">{configs.map(c=><button key={c.kind} onClick={()=>{setOpen(c.kind);setText("");setHandoffProfessional("");setHandoffScope("");setHandoffAuthority("");setNotice(null)}} className="rounded-xl border border-[#0b493b]/20 bg-[#f4f8f6] px-3 py-2 text-xs font-bold text-[#0b493b]">{c.title}</button>)}</div>
  {open?<div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-700">{configs.find(c=>c.kind===open)?.title}</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={configs.find(c=>c.kind===open)?.placeholder} className="mt-3 min-h-24 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-[#0b493b]"/>{open==="handoff"?<div className="mt-3 grid gap-3 md:grid-cols-2"><input value={handoffProfessional} onChange={e=>setHandoffProfessional(e.target.value)} placeholder="Receiving professional / firm / expert" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#0b493b]"/><input value={handoffAuthority} onChange={e=>setHandoffAuthority(e.target.value)} placeholder="Authority / approval boundary" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#0b493b]"/><textarea value={handoffScope} onChange={e=>setHandoffScope(e.target.value)} placeholder="Precise scope, deliverables, deadline or information boundary" className="min-h-20 rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-[#0b493b] md:col-span-2"/></div>:null}<div className="mt-3 flex gap-2"><button disabled={busy||!text.trim()} onClick={()=>void submit(open)} className="rounded-xl bg-[#0b493b] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{busy?"Saving…":"Save to matter record"}</button><button onClick={()=>setOpen(null)} className="px-3 py-2 text-xs font-bold text-slate-500">Cancel</button></div></div>:null}
  <div className="grid gap-3 lg:grid-cols-2">
   <RecordGroup title="Decisions">{data.decisions.slice(0,4).map(item=><RecordRow key={item.id} title={item.title} status={item.status}>{item.status==="proposed"?<><SmallButton disabled={busy} onClick={()=>void act({action:"decide",id:item.id,status:"approved"},"Decision approved.")}>Approve</SmallButton><SmallButton disabled={busy} onClick={()=>void act({action:"decide",id:item.id,status:"rejected"},"Decision rejected.")}>Reject</SmallButton></>:null}</RecordRow>)}</RecordGroup>
   <RecordGroup title="Client instructions">{data.instructions.slice(0,4).map(item=><RecordRow key={item.id} title={item.instruction} status={item.confirmation_status}>{item.confirmation_status==="recorded"?<><SmallButton disabled={busy} onClick={()=>void act({action:"confirm_instruction",id:item.id,status:"confirmation_requested"},"Client confirmation requested.")}>Request confirmation</SmallButton><SmallButton disabled={busy} onClick={()=>void act({action:"confirm_instruction",id:item.id,status:"confirmed"},"Instruction confirmed.")}>Confirm</SmallButton></>:null}{item.confirmation_status==="confirmation_requested"?<><SmallButton disabled={busy} onClick={()=>void act({action:"confirm_instruction",id:item.id,status:"confirmed"},"Instruction confirmed.")}>Confirm</SmallButton><SmallButton disabled={busy} onClick={()=>void act({action:"confirm_instruction",id:item.id,status:"disputed"},"Instruction marked disputed.")}>Dispute</SmallButton></>:null}</RecordRow>)}</RecordGroup>
   <RecordGroup title="Evidence & provenance">{data.evidence.slice(0,4).map(item=><RecordRow key={item.id} title={item.title} status={item.verification_status}>{item.verification_status==="unverified"?<><SmallButton disabled={busy} onClick={()=>void act({action:"verify_evidence",id:item.id,status:"corroborated"},"Evidence corroborated.")}>Corroborate</SmallButton><SmallButton disabled={busy} onClick={()=>void act({action:"verify_evidence",id:item.id,status:"verified"},"Evidence verified.")}>Verify</SmallButton><SmallButton disabled={busy} onClick={()=>void act({action:"verify_evidence",id:item.id,status:"disputed"},"Evidence disputed.")}>Dispute</SmallButton></>:null}</RecordRow>)}</RecordGroup>
   <RecordGroup title="Professional handoffs">{data.handoffs.slice(0,4).map(item=><RecordRow key={item.id} title={item.purpose} status={item.status} detail={[item.external_professional,item.scope_note,item.authority_note].filter(Boolean).join(" · ")}>{item.status==="prepared"?<><SmallButton disabled={busy} onClick={()=>void act({action:"advance_handoff",id:item.id,status:"accepted"},"Handoff accepted.")}>Accept</SmallButton><SmallButton disabled={busy} onClick={()=>void act({action:"advance_handoff",id:item.id,status:"cancelled"},"Handoff cancelled.")}>Cancel</SmallButton></>:null}{item.status==="accepted"?<SmallButton disabled={busy} onClick={()=>void act({action:"advance_handoff",id:item.id,status:"in_progress"},"Handoff started.")}>Start</SmallButton>:null}{item.status==="in_progress"?<><SmallButton disabled={busy} onClick={()=>void act({action:"advance_handoff",id:item.id,status:"completed"},"Handoff completed.")}>Complete</SmallButton><SmallButton disabled={busy} onClick={()=>void act({action:"advance_handoff",id:item.id,status:"returned"},"Handoff returned for further work.")}>Return</SmallButton></>:null}{item.status==="returned"?<SmallButton disabled={busy} onClick={()=>void act({action:"advance_handoff",id:item.id,status:"in_progress"},"Handoff resumed.")}>Resume</SmallButton>:null}</RecordRow>)}</RecordGroup>
  </div>
  {notice?<p className="text-xs font-semibold text-slate-600">{notice}</p>:null}
 </div>
}
function RecordGroup({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 p-4"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#0f5b49]">{title}</p><div className="mt-3 space-y-2">{children||<p className="text-xs text-slate-400">No records yet.</p>}</div></div>}
function RecordRow({title,status,detail,children}:{title:string;status:string;detail?:string;children?:React.ReactNode}){return <div className="rounded-xl bg-slate-50 p-3"><div className="flex items-start justify-between gap-3"><p className="text-xs font-semibold leading-5 text-slate-700">{title}</p><span className="rounded-lg bg-white px-2 py-1 text-[9px] font-black uppercase tracking-[.08em] text-slate-500">{status.replaceAll("_"," ")}</span></div>{detail?<p className="mt-1 text-[11px] leading-5 text-slate-500">{detail}</p>:null}{children?<div className="mt-2 flex flex-wrap gap-2">{children}</div>:null}</div>}
function SmallButton({children,onClick,disabled}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className="rounded-lg border border-[#0b493b]/20 bg-white px-2.5 py-1.5 text-[10px] font-bold text-[#0b493b] disabled:opacity-40">{children}</button>}
