"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CheckCircle2, CircleDashed, Search, ShieldCheck, UserRoundCheck } from "lucide-react";

type Contact={id:string;display_name:string;phone?:string|null;email?:string|null;client_status:string};
type Lawyer={id:string;full_name:string;role?:string|null};
type Parameter={id:string;parameter_type:string;label_en:string};
type Conflict={status:string;matches?:Array<{name:string;detail:string}>};
type Engagement={status:string;scope_of_work?:string|null;fee_arrangement?:string|null};
type Checklist={responsible_lawyer_assigned:boolean;responsible_lawyer_id?:string|null;initial_deadline_reviewed:boolean;initial_deadline_note?:string|null;document_structure_created:boolean};
type KycReview={id:string;status:string;risk_rating:string;created_at:string};
type Prospect={id:string;name:string;email?:string|null;phone?:string|null;matter_type?:string|null;jurisdiction?:string|null;summary?:string|null;status:string;primary_party_id?:string|null;matter_id?:string|null;conflict_checks?:Conflict[];engagements?:Engagement[];matter_opening_checklists?:Checklist[];kyc_reviews?:KycReview[]};
type Payload={success:boolean;error?:string;prospects?:Prospect[];lawyers?:Lawyer[];contacts?:Contact[];parameters?:Parameter[]};
const field="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";

function newestKyc(rows:KycReview[]|undefined){return [...(rows??[])].sort((a,b)=>b.created_at.localeCompare(a.created_at))[0]}

export default function ClientIntakeCore(){
 const [data,setData]=useState<Payload>({success:true,prospects:[],lawyers:[],contacts:[],parameters:[]});
 const [selectedId,setSelectedId]=useState("");const [search,setSearch]=useState("");const [primaryPartyId,setPrimaryPartyId]=useState("");
 const [name,setName]=useState("");const [phone,setPhone]=useState("");const [email,setEmail]=useState("");const [matterType,setMatterType]=useState("General legal matter");const [jurisdiction,setJurisdiction]=useState("Cameroon");const [summary,setSummary]=useState("");const [opponent,setOpponent]=useState("");
 const [scopeOfWork,setScopeOfWork]=useState("");const [feeArrangement,setFeeArrangement]=useState("");const [leadLawyerId,setLeadLawyerId]=useState("");const [deadlineNote,setDeadlineNote]=useState("");const [documentsReady,setDocumentsReady]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function load(preferId?:string){const r=await fetch("/api/intake",{cache:"no-store"});const p:Payload=await r.json();if(!p.success)throw new Error(p.error||"Unable to load client cycle.");setData(p);if(preferId)setSelectedId(preferId)}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Unable to load."));},[]);
 const prospects=data.prospects??[];const contacts=data.contacts??[];const lawyers=data.lawyers??[];const parameters=data.parameters??[];const selected=prospects.find(p=>p.id===selectedId)??null;
 const q=search.trim().toLowerCase();const matchedContacts=contacts.filter(c=>!q||[c.display_name,c.phone,c.email].some(v=>v?.toLowerCase().includes(q))).slice(0,8);
 const matterTypes=parameters.filter(p=>p.parameter_type==="matter_type");const jurisdictions=parameters.filter(p=>p.parameter_type==="jurisdiction");const feeModels=parameters.filter(p=>p.parameter_type==="fee_model");
 const conflict=selected?.conflict_checks?.[0];const engagement=selected?.engagements?.[0];const checklist=selected?.matter_opening_checklists?.[0];const kyc=newestKyc(selected?.kyc_reviews);
 const conflictOk=conflict?.status==="Cleared"||conflict?.status==="Waived";const kycOk=kyc?.status==="cleared";const engagementOk=engagement?.status==="Approved";const openingOk=Boolean(checklist?.responsible_lawyer_assigned&&checklist?.responsible_lawyer_id&&checklist?.initial_deadline_reviewed&&checklist?.document_structure_created);const canOpen=Boolean(selected&&!selected.matter_id&&conflictOk&&kycOk&&engagementOk&&openingOk);
 async function call(action:string,payload:Record<string,unknown>={}){setBusy(true);setMessage("");try{const r=await fetch("/api/intake",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const p=await r.json();if(!p.success)throw new Error(p.error||"Action failed.");return p}catch(e){setMessage(e instanceof Error?e.message:"Action failed.");return null}finally{setBusy(false)}}
 function chooseContact(c:Contact){setPrimaryPartyId(c.id);setSearch(c.display_name);setName(c.display_name);setPhone(c.phone??"");setEmail(c.email??"")}
 function chooseAssessment(p:Prospect){setSelectedId(p.id);setPrimaryPartyId(p.primary_party_id??"");setSearch(p.name);setName(p.name);setPhone(p.phone??"");setEmail(p.email??"");setMatterType(p.matter_type??"General legal matter");setJurisdiction(p.jurisdiction??"Cameroon");setSummary(p.summary??"");setScopeOfWork(p.engagements?.[0]?.scope_of_work??"");setFeeArrangement(p.engagements?.[0]?.fee_arrangement??"");setLeadLawyerId(p.matter_opening_checklists?.[0]?.responsible_lawyer_id??"");setDeadlineNote(p.matter_opening_checklists?.[0]?.initial_deadline_note??"");setDocumentsReady(Boolean(p.matter_opening_checklists?.[0]?.document_structure_created))}
 async function startAssessment(){const p=await call("createProspect",{primaryPartyId:primaryPartyId||null,name,phone,email,matterType,jurisdiction,summary,parties:opponent?[{name:opponent,partyRole:"Opposing party"}]:[]});if(!p?.prospect?.id)return;await call("runConflictCheck",{prospectId:p.prospect.id});await load(p.prospect.id);setMessage("Assessment created from the same contact record.")}
 async function conflictDecision(status:"Cleared"|"Waived"){if(!selected)return;const p=await call("decideConflict",{prospectId:selected.id,status,decisionNote:status==="Cleared"?"Conflict review completed.":"Authorised conflict waiver recorded."});if(p)await load(selected.id)}
 async function approveEngagement(){if(!selected)return;const p=await call("saveEngagement",{prospectId:selected.id,scopeOfWork:scopeOfWork||selected.summary||"",feeArrangement,approve:true,decisionNote:"Engagement approved for opening review."});if(p)await load(selected.id)}
 async function saveOpening(){if(!selected)return;const p=await call("updateChecklist",{prospectId:selected.id,kycComplete:kycOk,responsibleLawyerAssigned:Boolean(leadLawyerId),responsibleLawyerId:leadLawyerId||null,initialDeadlineReviewed:Boolean(deadlineNote.trim()),initialDeadlineNote:deadlineNote,documentStructureCreated:documentsReady,documentStructureNote:documentsReady?"Opening document structure ready.":""});if(p)await load(selected.id)}
 async function openMatter(){if(!selected)return;const p=await call("openMatter",{prospectId:selected.id});if(p?.matterId){await load(selected.id);setMessage("Matter opened after all required gates were satisfied.")}}
 return <main className="mx-auto max-w-[1600px] px-4 py-8 md:px-8">
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white shadow-xl md:p-8"><p className="text-[10px] font-black uppercase tracking-[0.24em] text-white/50">Client cycle</p><h1 className="mt-2 text-4xl font-semibold">Find the person first. Open the matter only when ready.</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">Walk-ins, referrals, calls and existing clients follow one progressive record. Conflict, KYC and engagement are professional gates—not repeated intake forms.</p></section>
  {message&&<div className="mt-5 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  <div className="mt-5 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
   <section className="space-y-5">
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Search className="h-5 w-5 text-emerald-800"/><h2 className="text-xl font-semibold text-slate-950">Search existing client/contact first</h2></div><input className={`${field} mt-4`} value={search} onChange={e=>{setSearch(e.target.value);if(primaryPartyId)setPrimaryPartyId("")}} placeholder="Name, phone or email"/><div className="mt-3 space-y-2">{matchedContacts.map(c=><button key={c.id} onClick={()=>chooseContact(c)} className={`w-full rounded-2xl border p-3 text-left ${primaryPartyId===c.id?"border-emerald-700 bg-emerald-50":"border-slate-100"}`}><p className="text-sm font-semibold">{c.display_name}</p><p className="text-xs text-slate-500">{[c.phone,c.email].filter(Boolean).join(" · ")||"No contact detail"} · {c.client_status.replaceAll("_"," ")}</p></button>)}</div></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">New legal request</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input className={field} value={name} onChange={e=>setName(e.target.value)} placeholder="Person / organisation"/><input className={field} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone"/><input className={field} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><select className={field} value={matterType} onChange={e=>setMatterType(e.target.value)}>{matterTypes.length?matterTypes.map(p=><option key={p.id}>{p.label_en}</option>):<><option>General legal matter</option><option>Litigation</option><option>Labour matter</option><option>Debt recovery / OHADA</option></>}</select><select className={field} value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}>{jurisdictions.length?jurisdictions.map(p=><option key={p.id}>{p.label_en}</option>):<><option>Cameroon</option><option>OHADA</option><option>CEMAC</option><option>OAPI</option></>}</select><input className={field} value={opponent} onChange={e=>setOpponent(e.target.value)} placeholder="Opposing / connected party"/></div><textarea className={`${field} mt-3 min-h-28`} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="What legal help is requested?"/><button onClick={startAssessment} disabled={busy||!name.trim()||!summary.trim()} className="mt-3 rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Start assessment</button><p className="mt-2 text-xs text-slate-500">No matter is opened yet.</p></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Saved assessments</p><div className="mt-3 max-h-80 space-y-2 overflow-auto">{prospects.map(p=><button key={p.id} onClick={()=>chooseAssessment(p)} className={`w-full rounded-2xl border p-3 text-left ${selectedId===p.id?"border-emerald-700 bg-emerald-50":"border-slate-100"}`}><div className="flex justify-between gap-3"><div><p className="font-semibold">{p.name}</p><p className="text-xs text-slate-500">{p.matter_type||"Legal matter"} · {p.status}</p></div>{p.matter_id&&<span className="h-fit rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold uppercase text-emerald-800">Matter open</span>}</div></button>)}</div></div>
   </section>
   <section className="space-y-5">{!selected?<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><UserRoundCheck className="mx-auto h-8 w-8 text-emerald-800"/><h2 className="mt-3 text-xl font-semibold">Select or start an assessment</h2><p className="mt-2 text-sm text-slate-500">Only relevant professional controls will appear.</p></div>:<>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><h2 className="text-2xl font-semibold text-slate-950">{selected.name}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Gate label="Conflict" done={conflictOk} detail={conflict?.status||"Not checked"}/><Gate label="KYC / compliance" done={kycOk} detail={kyc?.status?.replaceAll("_"," ")||"Not started"}/><Gate label="Engagement" done={engagementOk} detail={engagement?.status||"Not approved"}/><Gate label="Opening controls" done={openingOk} detail={openingOk?"Ready":"Incomplete"}/></div></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">1 · Can we act?</p><h3 className="text-lg font-semibold">Conflict & KYC</h3></div><ShieldCheck className="h-5 w-5 text-emerald-800"/></div>{!conflictOk&&<div className="mt-4 flex gap-2"><button onClick={()=>conflictDecision("Cleared")} disabled={busy} className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Clear after review</button><button onClick={()=>conflictDecision("Waived")} disabled={busy} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold">Authorised waiver</button></div>}<Link href={`/intake/${selected.id}/kyc`} className="mt-4 inline-flex rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-xs font-bold text-emerald-900">{kycOk?"Review KYC":"Complete KYC / compliance"}</Link></div>
    {conflictOk&&<div className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">2 · Will we act?</p><textarea className={`${field} mt-4 min-h-24`} value={scopeOfWork} onChange={e=>setScopeOfWork(e.target.value)} placeholder="Scope of work"/><select className={`${field} mt-3`} value={feeArrangement} onChange={e=>setFeeArrangement(e.target.value)}><option value="">Fee model / arrangement</option>{feeModels.length?feeModels.map(p=><option key={p.id}>{p.label_en}</option>):<><option>Fixed fee</option><option>Hourly</option><option>Retainer</option><option>Stage-based</option></>}</select><button onClick={approveEngagement} disabled={busy||!scopeOfWork.trim()||!feeArrangement.trim()} className="mt-3 rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Approve engagement</button></div>}
    {engagementOk&&<div className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">3 · Opening controls</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select className={field} value={leadLawyerId} onChange={e=>setLeadLawyerId(e.target.value)}><option value="">Responsible lawyer</option>{lawyers.map(l=><option key={l.id} value={l.id}>{l.full_name}{l.role?` · ${l.role}`:""}</option>)}</select><input className={field} value={deadlineNote} onChange={e=>setDeadlineNote(e.target.value)} placeholder="Initial deadline/timing review"/></div><label className="mt-3 flex items-center gap-3 rounded-2xl border border-slate-100 p-4 text-sm"><input type="checkbox" checked={documentsReady} onChange={e=>setDocumentsReady(e.target.checked)}/><span>Opening file/document structure ready</span></label><button onClick={saveOpening} disabled={busy||!kycOk} className="mt-3 rounded-2xl border border-emerald-900 px-5 py-3 text-sm font-semibold disabled:opacity-40">Save opening controls</button></div>}
    <div className={`rounded-[1.6rem] border p-5 ${selected.matter_id||canOpen?"border-emerald-200 bg-emerald-50":"border-slate-200 bg-slate-50"}`}><h3 className="text-xl font-semibold">{selected.matter_id?"Matter already opened":canOpen?"Ready to open":"Required gates remain"}</h3>{selected.matter_id?<Link href={`/matters/${selected.matter_id}`} className="mt-4 inline-flex rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white">Open matter room</Link>:<button onClick={openMatter} disabled={busy||!canOpen} className="mt-4 rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-35">Open governed matter</button>}</div>
   </>}</section>
  </div>
 </main>
}
function Gate({label,done,detail}:{label:string;done:boolean;detail:string}){return <div className={`rounded-2xl border p-3 ${done?"border-emerald-200 bg-emerald-50":"border-slate-100 bg-slate-50"}`}><div className="flex items-center gap-2">{done?<CheckCircle2 className="h-4 w-4 text-emerald-700"/>:<CircleDashed className="h-4 w-4 text-slate-400"/>}<span className="text-xs font-bold uppercase tracking-[0.12em] text-slate-600">{label}</span></div><p className="mt-2 text-xs text-slate-500">{detail}</p></div>}
