"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleDashed, Search, ShieldCheck, UserRoundCheck } from "lucide-react";

type Contact={id:string;display_name:string;phone?:string|null;email?:string|null;client_status:string;preferred_language:string};
type Lawyer={id:string;full_name:string;role?:string|null};
type Parameter={id:string;parameter_type:string;parameter_key:string;label_en:string;label_fr?:string|null;active:boolean};
type Prospect={
 id:string;name:string;email?:string|null;phone?:string|null;source?:string|null;matter_type?:string|null;jurisdiction?:string|null;summary?:string|null;status:string;risk_level?:string|null;responsible_lawyer_id?:string|null;primary_party_id?:string|null;matter_id?:string|null;created_at:string;
 conflict_checks?:Array<{status:string;matches?:Array<{name:string;detail:string}>;decision_note?:string|null}>;
 engagements?:Array<{status:string;scope_of_work?:string|null;fee_arrangement?:string|null}>;
 matter_opening_checklists?:Array<{kyc_complete:boolean;conflict_cleared:boolean;engagement_approved:boolean;responsible_lawyer_assigned:boolean;responsible_lawyer_id?:string|null;initial_deadline_reviewed:boolean;initial_deadline_note?:string|null;document_structure_created:boolean;document_structure_note?:string|null;opening_notes?:string|null}>;
 prospect_parties?:Array<{name:string;party_role:string}>;
 kyc_reviews?:Array<{id:string;status:string;risk_rating:string;reviewed_at?:string|null;created_at:string}>;
};
type LoadPayload={success:boolean;error?:string;prospects?:Prospect[];lawyers?:Lawyer[];contacts?:Contact[];parameters?:Parameter[]};
const field="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";

function latest<T extends {created_at:string}>(rows?:T[]){return [...(rows??[])].sort((a,b)=>b.created_at.localeCompare(a.created_at))[0]}

export default function ClientIntakeV2(){
 const [data,setData]=useState<LoadPayload>({success:true,prospects:[],lawyers:[],contacts:[],parameters:[]});
 const [selectedId,setSelectedId]=useState("");
 const [contactSearch,setContactSearch]=useState(""); const [primaryPartyId,setPrimaryPartyId]=useState("");
 const [form,setForm]=useState({name:"",email:"",phone:"",matterType:"General legal matter",jurisdiction:"Cameroon",summary:"",opposingParty:"",scopeOfWork:"",feeArrangement:""});
 const [leadLawyerId,setLeadLawyerId]=useState("");const [deadlineNote,setDeadlineNote]=useState("");const [documentsReady,setDocumentsReady]=useState(false);
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function load(preferId?:string){const r=await fetch("/api/intake",{cache:"no-store"});const p=await r.json();if(!p.success)throw new Error(p.error);setData(p);if(preferId)setSelectedId(preferId)}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 const contacts=data.contacts??[];const prospects=data.prospects??[];const lawyers=data.lawyers??[];const params=data.parameters??[];
 const selected=prospects.find(p=>p.id===selectedId)??null;
 const matchedContacts=useMemo(()=>{const q=contactSearch.trim().toLowerCase();if(!q)return contacts.slice(0,8);return contacts.filter(c=>[c.display_name,c.phone,c.email].some(v=>v?.toLowerCase().includes(q))).slice(0,10)},[contacts,contactSearch]);
 const matterTypes=params.filter(p=>p.parameter_type==="matter_type");const jurisdictions=params.filter(p=>p.parameter_type==="jurisdiction");const feeModels=params.filter(p=>p.parameter_type==="fee_model");
 const conflict=selected?.conflict_checks?.[0];const engagement=selected?.engagements?.[0];const checklist=selected?.matter_opening_checklists?.[0];const kyc=latest(selected?.kyc_reviews);
 const conflictCleared=conflict?.status==="Cleared"||conflict?.status==="Waived";const kycCleared=kyc?.status==="cleared";const engagementApproved=engagement?.status==="Approved";
 const responsible=Boolean(checklist?.responsible_lawyer_assigned&&checklist?.responsible_lawyer_id);const deadline=Boolean(checklist?.initial_deadline_reviewed);const docs=Boolean(checklist?.document_structure_created);
 const canOpen=Boolean(selected&&!selected.matter_id&&conflictCleared&&kycCleared&&engagementApproved&&responsible&&deadline&&docs);
 function useContact(c:Contact){setPrimaryPartyId(c.id);setContactSearch(c.display_name);setForm(v=>({...v,name:c.display_name,email:c.email??"",phone:c.phone??""}))}
 function clearContact(){setPrimaryPartyId("");setContactSearch("");setForm(v=>({...v,name:"",email:"",phone:""}))}
 async function call(action:string,payload:Record<string,unknown>={}){setBusy(true);setMessage("");try{const r=await fetch("/api/intake",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const p=await r.json();if(!p.success)throw new Error(p.error);return p}catch(e){setMessage(e instanceof Error?e.message:"Action failed.");return null}finally{setBusy(false)}}
 async function create(){const p=await call("createProspect",{primaryPartyId:primaryPartyId||null,name:form.name,email:form.email,phone:form.phone,matterType:form.matterType,jurisdiction:form.jurisdiction,summary:form.summary,parties:form.opposingParty?[{name:form.opposingParty,partyRole:"Opposing party"}]:[]});if(!p?.prospect?.id)return;await call("runConflictCheck",{prospectId:p.prospect.id});await load(p.prospect.id);setMessage("Assessment created. The same person/contact record will continue through the client cycle.")}
 async function decide(status:"Cleared"|"Waived"){if(!selected)return;const p=await call("decideConflict",{prospectId:selected.id,status,decisionNote:status==="Cleared"?"Conflict review completed by authorised lawyer.":"Conflict waiver decision recorded by authorised lawyer."});if(p)await load(selected.id)}
 async function approveEngagement(){if(!selected)return;const p=await call("saveEngagement",{prospectId:selected.id,scopeOfWork:form.scopeOfWork||selected.summary||"",feeArrangement:form.feeArrangement||"To define",approve:true,decisionNote:"Engagement approved for matter opening."});if(p)await load(selected.id)}
 async function saveOpening(){if(!selected)return;const p=await call("updateChecklist",{prospectId:selected.id,kycComplete:kycCleared,responsibleLawyerAssigned:Boolean(leadLawyerId),responsibleLawyerId:leadLawyerId||null,initialDeadlineReviewed:Boolean(deadlineNote.trim()),initialDeadlineNote:deadlineNote,documentStructureCreated:documentsReady,documentStructureNote:documentsReady?"Opening matter vault/document structure confirmed ready.":""});if(p){await load(selected.id);setMessage("Opening controls saved.")}}
 async function openMatter(){if(!selected)return;const p=await call("openMatter",{prospectId:selected.id});if(p?.matterId){await load(selected.id);setMessage("Matter opened from the same client record after all gates were satisfied.")}}
 function selectProspect(p:Prospect){setSelectedId(p.id);setPrimaryPartyId(p.primary_party_id??"");setContactSearch(p.name);setForm(v=>({...v,name:p.name,email:p.email??"",phone:p.phone??"",matterType:p.matter_type??v.matterType,jurisdiction:p.jurisdiction??v.jurisdiction,summary:p.summary??"",opposingParty:p.prospect_parties?.find(x=>x.party_role!=="Prospective client")?.name??"",scopeOfWork:p.engagements?.[0]?.scope_of_work??"",feeArrangement:p.engagements?.[0]?.fee_arrangement??""}));setLeadLawyerId(p.matter_opening_checklists?.[0]?.responsible_lawyer_id??"");setDeadlineNote(p.matter_opening_checklists?.[0]?.initial_deadline_note??"");setDocumentsReady(Boolean(p.matter_opening_checklists?.[0]?.document_structure_created))}
 return <main className="mx-auto max-w-[1600px] px-4 py-8 md:px-8">
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white shadow-xl md:p-8"><p className="text-[10px] font-black uppercase tracking-[0.24em] text-white/50">Client cycle</p><h1 className="mt-2 text-4xl font-semibold">Find the person first. Open the legal matter only when ready.</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">A walk-in, referral, call or existing client follows the same simple path. Known people are reused; new people need minimum capture. Conflict, KYC and engagement remain professional gates—not duplicate intake records.</p></section>
  {message&&<div className="mt-5 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  <div className="mt-5 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
   <section className="space-y-5">
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Search className="h-5 w-5 text-emerald-800"/><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Search first</p><h2 className="text-xl font-semibold text-slate-950">Existing client or contact?</h2></div></div><input className={`${field} mt-4`} value={contactSearch} onChange={e=>{setContactSearch(e.target.value);if(primaryPartyId)setPrimaryPartyId("")}} placeholder="Name, phone or email"/><div className="mt-3 space-y-2">{matchedContacts.map(c=><button key={c.id} onClick={()=>useContact(c)} className={`w-full rounded-2xl border p-3 text-left ${primaryPartyId===c.id?"border-emerald-700 bg-emerald-50":"border-slate-100"}`}><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">{c.display_name}</p><p className="text-xs text-slate-500">{[c.phone,c.email].filter(Boolean).join(" · ")||"No contact details"}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-500">{c.client_status.replaceAll("_"," ")}</span></div></button>)}</div>{primaryPartyId&&<button onClick={clearContact} className="mt-3 text-xs font-semibold text-slate-500 underline">This is a different/new person</button>}</div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">New legal request</p><h2 className="text-xl font-semibold text-slate-950">Minimum capture, then progressive assessment</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className={field} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Person / organisation name"/><input className={field} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone (optional)"/><input className={field} value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email (optional)"/><select className={field} value={form.matterType} onChange={e=>setForm({...form,matterType:e.target.value})}>{matterTypes.length?<>{matterTypes.map(p=><option key={p.id} value={p.label_en}>{p.label_en}</option>)}</>:<><option>General legal matter</option><option>Litigation</option><option>Labour matter</option><option>Corporate transaction</option><option>Debt recovery / OHADA</option></>}</select><select className={field} value={form.jurisdiction} onChange={e=>setForm({...form,jurisdiction:e.target.value})}>{jurisdictions.length?<>{jurisdictions.map(p=><option key={p.id} value={p.label_en}>{p.label_en}</option>)}</>:<><option>Cameroon</option><option>OHADA</option><option>CEMAC</option><option>OAPI</option></>}</select><input className={field} value={form.opposingParty} onChange={e=>setForm({...form,opposingParty:e.target.value})} placeholder="Opposing / connected party"/></div><textarea className={`${field} mt-3 min-h-28`} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} placeholder="What legal help is being requested?"/><button onClick={create} disabled={busy||!form.name.trim()||!form.summary.trim()} className="mt-3 rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Start assessment</button><p className="mt-2 text-xs text-slate-500">No matter is opened yet.</p></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Saved assessments</p><h2 className="text-lg font-semibold text-slate-950">Resume without re-registering the client</h2></div><div className="mt-4 max-h-96 space-y-2 overflow-auto">{prospects.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No assessments yet.</p>:prospects.map(p=><button key={p.id} onClick={()=>selectProspect(p)} className={`w-full rounded-2xl border p-4 text-left ${selectedId===p.id?"border-emerald-700 bg-emerald-50":"border-slate-100"}`}><div className="flex justify-between gap-3"><div><p className="font-semibold text-slate-900">{p.name}</p><p className="mt-1 text-xs text-slate-500">{p.matter_type||"Legal matter"} · {p.status}</p></div>{p.matter_id&&<span className="h-fit rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold uppercase text-emerald-800">Matter open</span>}</div></button>)}</div></div>
   </section>
   <section className="space-y-5">
    {!selected?<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><UserRoundCheck className="mx-auto h-8 w-8 text-emerald-800"/><h2 className="mt-3 text-xl font-semibold">Select or start an assessment</h2><p className="mt-2 text-sm text-slate-500">Professional gates appear only when they become relevant.</p></div>:<>
     <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Opening gate</p><h2 className="text-2xl font-semibold text-slate-950">{selected.name}</h2><p className="mt-1 text-sm text-slate-500">{selected.matter_type} · {selected.jurisdiction}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase text-slate-600">{selected.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Gate label="Conflict" done={conflictCleared} detail={conflict?.status||"Not checked"}/><Gate label="KYC / compliance" done={kycCleared} detail={kyc?.status?.replaceAll("_"," ")||"Not started"}/><Gate label="Engagement" done={engagementApproved} detail={engagement?.status||"Not approved"}/><Gate label="Opening controls" done={responsible&&deadline&&docs} detail={responsible&&deadline&&docs?"Ready":"Incomplete"}/></div></div>
     <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">1 · Can we act?</p><h3 className="text-lg font-semibold">Conflict & KYC</h3></div><ShieldCheck className="h-5 w-5 text-emerald-800"/></div>{(conflict?.matches??[]).length>0&&<div className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Potential matches</p>{conflict?.matches?.map((m,i)=><p key={i} className="mt-1 text-xs">{m.name} — {m.detail}</p>)}</div>}<div className="mt-4 flex flex-wrap gap-2">{!conflictCleared&&<><button disabled={busy} onClick={()=>decide("Cleared")} className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Clear after review</button><button disabled={busy} onClick={()=>decide("Waived")} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold">Record authorised waiver</button></>}<Link href={`/intake/${selected.id}/kyc`} className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-xs font-bold text-emerald-900">{kycCleared?"Review KYC record":"Complete KYC / compliance"}</Link></div></div>
     {conflictCleared&&<div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">2 · Will we act?</p><h3 className="text-lg font-semibold">Scope, fees & engagement</h3></div><textarea className={`${field} mt-4 min-h-24`} value={form.scopeOfWork} onChange={e=>setForm({...form,scopeOfWork:e.target.value})} placeholder="Scope of work"/><div className="mt-3 grid gap-3 md:grid-cols-[1fr_auto]"><select className={field} value={form.feeArrangement} onChange={e=>setForm({...form,feeArrangement:e.target.value})}><option value="">Select fee model / arrangement</option>{feeModels.length?feeModels.map(p=><option key={p.id} value={p.label_en}>{p.label_en}</option>):<><option>Fixed fee</option><option>Hourly</option><option>Retainer</option><option>Stage-based</option><option>To define</option></>}</select><button onClick={approveEngagement} disabled={busy||!form.scopeOfWork.trim()||!form.feeArrangement.trim()} className="rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Approve engagement</button></div></div>}
     {engagementApproved&&<div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">3 · Opening controls</p><h3 className="text-lg font-semibold">One final operational check</h3></div><div className="mt-4 grid gap-3 md:grid-cols-2"><select className={field} value={leadLawyerId||checklist?.responsible_lawyer_id||""} onChange={e=>setLeadLawyerId(e.target.value)}><option value="">Responsible lawyer</option>{lawyers.map(l=><option key={l.id} value={l.id}>{l.full_name}{l.role?` · ${l.role}`:""}</option>)}</select><input className={field} value={deadlineNote||checklist?.initial_deadline_note||""} onChange={e=>setDeadlineNote(e.target.value)} placeholder="Initial deadline / timing review"/></div><label className="mt-4 flex items-center gap-3 rounded-2xl border border-slate-100 p-4 text-sm"><input type="checkbox" checked={documentsReady||Boolean(checklist?.document_structure_created)} onChange={e=>setDocumentsReady(e.target.checked)}/><span><strong>Opening file structure ready</strong><span className="block text-xs text-slate-500">Digital/physical document control can now begin.</span></span></label><button onClick={saveOpening} disabled={busy||!kycCleared} className="mt-3 rounded-2xl border border-emerald-900 px-5 py-3 text-sm font-semibold text-emerald-950 disabled:opacity-40">Save opening controls</button>{!kycCleared&&<p className="mt-2 text-xs text-amber-700">KYC must be cleared before the opening controls can be certified.</p>}</div>}
     <div className={`rounded-[1.6rem] border p-5 ${selected.matter_id?"border-emerald-200 bg-emerald-50":canOpen?"border-emerald-300 bg-white":"border-slate-200 bg-slate-50"}`}><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Matter opening</p><h3 className="mt-1 text-xl font-semibold">{selected.matter_id?"Matter already opened":canOpen?"Ready to open":"Blocked until required gates are complete"}</h3></div>{selected.matter_id?<CheckCircle2 className="h-7 w-7 text-emerald-700"/>:<CircleDashed className="h-7 w-7 text-slate-400"/>}</div>{selected.matter_id?<Link href={`/matters/${selected.matter_id}`} className="mt-4 inline-flex rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white">Open matter room</Link>:<button onClick={openMatter} disabled={busy||!canOpen} className="mt-4 rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-35">Open governed matter</button>}</div>
    </>}
   </section>
  </div>
 </main>
}
function Gate({label,done,detail}:{label:string;done:boolean;detail:string}){return <div className={`rounded-2xl border p-3 ${done?"border-emerald-200 bg-emerald-50":"border-slate-100 bg-slate-50"}`}><div className="flex items-center gap-2">{done?<CheckCircle2 className="h-4 w-4 text-emerald-700"/>:<CircleDashed className="h-4 w-4 text-slate-400"/>}<span className="text-xs font-bold uppercase tracking-[0.12em] text-slate-600">{label}</span></div><p className="mt-2 text-xs text-slate-500">{detail}</p></div>}
