"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { AlertTriangle, ArrowRight, Banknote, Clock3, Gavel, ShieldAlert } from "lucide-react";

type Attention={matterId:string;matterTitle:string;clientName:string;severity:"critical"|"high"|"medium";kind:string;label:string;detail:string};
type Pulse={summary:{activeMatters:number;attentionMatters:number;criticalItems:number;highItems:number;pendingApprovals:number;outstandingXaf:number;unbilledMinutes:number;unbilledValueXaf:number;recoverableExpensesXaf:number;communicationReview:number;unresolvedClaims:number;executionBlocks:number};attention:Attention[]};

export default function FirmPulse(){
 const[pulse,setPulse]=useState<Pulse|null>(null);const[loading,setLoading]=useState(true);const[hidden,setHidden]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{try{const res=await fetch("/api/firm/pulse",{cache:"no-store"});if(res.status===401||res.status===403){if(!cancelled)setHidden(true);return;}const data=await res.json();if(res.ok&&data.success&&!cancelled)setPulse(data.pulse);}catch{/* Keep ordinary workspace usable if pulse is unavailable. */}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true}},[]);
 if(hidden)return null;
 if(loading)return <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="h-20 animate-pulse rounded-2xl bg-slate-100"/></section>;
 if(!pulse)return null;
 const s=pulse.summary;
 return <section className="rounded-[1.8rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#0f5b49]">Firm Head pulse</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-slate-900">Where management judgment is needed</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">A compact roll-up of legal risk, approvals, execution, collections and work-in-progress across active matters.</p></div><div className="rounded-2xl bg-[#0b493b] px-4 py-3 text-white"><p className="text-[9px] font-black uppercase tracking-[.15em] text-white/50">Attention matters</p><p className="mt-1 text-2xl font-semibold">{s.attentionMatters}<span className="ml-1 text-sm text-white/45">/ {s.activeMatters}</span></p></div></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={<ShieldAlert className="h-4 w-4"/>} label="Critical / high" value={`${s.criticalItems} / ${s.highItems}`}/><Metric icon={<Gavel className="h-4 w-4"/>} label="Approvals waiting" value={String(s.pendingApprovals)}/><Metric icon={<Banknote className="h-4 w-4"/>} label="Outstanding" value={`XAF ${compact(s.outstandingXaf)}`}/><Metric icon={<Clock3 className="h-4 w-4"/>} label="Unbilled work" value={`${Math.round(s.unbilledMinutes/60)}h · XAF ${compact(s.unbilledValueXaf)}`}/><Metric icon={<AlertTriangle className="h-4 w-4"/>} label="Evidence / comms" value={`${s.unresolvedClaims} / ${s.communicationReview}`}/><Metric icon={<ArrowRight className="h-4 w-4"/>} label="Execution blocks" value={String(s.executionBlocks)}/></div>
  <div className="mt-5 grid gap-2 lg:grid-cols-2">{pulse.attention.slice(0,8).map((item,index)=><Link key={`${item.matterId}-${item.kind}-${index}`} href={`/matters/${item.matterId}`} className="group flex items-start justify-between gap-3 rounded-2xl border border-slate-200 bg-[#fafbf9] p-4 transition hover:border-[#0b493b]/25"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase tracking-[.1em] ${item.severity==="critical"?"bg-red-50 text-red-700":item.severity==="high"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500"}`}>{item.severity}</span><span className="text-[9px] font-black uppercase tracking-[.1em] text-slate-400">{item.kind}</span></div><p className="mt-2 text-sm font-bold text-slate-800">{item.label}</p><p className="mt-1 text-xs text-slate-500">{item.clientName} · {item.matterTitle}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.detail}</p></div><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-slate-300 transition group-hover:text-[#0b493b]"/></Link>)}</div>
  {!pulse.attention.length?<p className="mt-5 rounded-2xl bg-[#f4f8f6] p-4 text-sm font-semibold text-[#0b493b]">No current management exception is being raised by the governed firm record.</p>:null}
 </section>
}
function compact(value:number){return Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(Math.round(value||0))}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl bg-[#f8faf8] p-4"><div className="flex items-center gap-2 text-[#0b493b]">{icon}<p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-500">{label}</p></div><p className="mt-2 text-sm font-bold text-slate-800">{value}</p></div>}
