"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, Clock3, Copy, Loader2, MailPlus, RefreshCw, ShieldCheck, UserPlus, UsersRound, XCircle } from "lucide-react";

type Invitation={id:string;email:string;role_key:string;status:string;expires_at:string;accepted_at?:string|null;created_at:string};
type ApiResponse={success:boolean;invitations?:Invitation[];invitation?:Invitation;inviteUrl?:string;error?:string};
const roles=[
 ["partner","Partner","Firm governance, approvals and matter authority"],
 ["lawyer","Lawyer","Matter execution, drafting and client work"],
 ["paralegal","Paralegal","File operations, evidence and deadlines"],
 ["intern","Intern","Supervised research and drafting"],
 ["administrator","Administrator","Firm operations and access support"],
 ["finance","Finance","Billing, collections and reconciliation"],
 ["clerk","Clerk","Registry, filing and operational support"],
 ["knowledge_manager","Knowledge manager","Sources, precedent and institutional memory"],
] as const;

export default function FirmAccessPanel(){
 const[invitations,setInvitations]=useState<Invitation[]>([]);const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState<string|null>(null);const[submitting,setSubmitting]=useState(false);const[email,setEmail]=useState("");const[roleKey,setRoleKey]=useState("lawyer");const[lifetimeHours,setLifetimeHours]=useState("168");const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[latestInviteUrl,setLatestInviteUrl]=useState<string|null>(null);const[copied,setCopied]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/firm/invitations",{cache:"no-store",credentials:"include"});const p=await r.json() as ApiResponse;if(!r.ok||!p.success)throw new Error(p.error||"Unable to load firm invitations.");setInvitations(p.invitations??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load firm invitations.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const selectedRole=useMemo(()=>roles.find(([key])=>key===roleKey),[roleKey]);
 const pendingCount=invitations.filter(i=>i.status==="pending").length;const acceptedCount=invitations.filter(i=>i.status==="accepted").length;
 async function createInvitation(targetEmail:string,targetRole:string,hours:number){const r=await fetch("/api/firm/invitations",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:targetEmail,roleKey:targetRole,lifetimeHours:hours})});const p=await r.json() as ApiResponse;if(!r.ok||!p.success)throw new Error(p.error||"Unable to create invitation.");return p}
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubmitting(true);setError(null);setMessage(null);setLatestInviteUrl(null);try{const p=await createInvitation(email,roleKey,Number(lifetimeHours)||168);setLatestInviteUrl(p.inviteUrl??null);setMessage(`Invitation created for ${p.invitation?.email??email}.`);setEmail("");await load()}catch(err){setError(err instanceof Error?err.message:"Unable to create invitation.")}finally{setSubmitting(false)}}
 async function revoke(id:string){setBusyId(id);setError(null);try{const r=await fetch("/api/firm/invitations",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({invitationId:id})});const p=await r.json() as ApiResponse;if(!r.ok||!p.success)throw new Error(p.error||"Unable to revoke invitation.");setMessage("Pending invitation revoked.");await load()}catch(err){setError(err instanceof Error?err.message:"Unable to revoke invitation.")}finally{setBusyId(null)}}
 async function refresh(invitation:Invitation){setBusyId(invitation.id);setError(null);setLatestInviteUrl(null);try{const p=await createInvitation(invitation.email,invitation.role_key,168);setLatestInviteUrl(p.inviteUrl??null);setMessage(`Fresh invitation created for ${invitation.email}.`);await load()}catch(err){setError(err instanceof Error?err.message:"Unable to refresh invitation.")}finally{setBusyId(null)}}
 async function copy(){if(!latestInviteUrl)return;await navigator.clipboard.writeText(latestInviteUrl);setCopied(true);window.setTimeout(()=>setCopied(false),1500)}
 return <section id="firm-access" className="rounded-[1.8rem] border border-slate-200 bg-white p-5 shadow-[0_14px_40px_rgba(15,23,42,.045)] md:p-6">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-3xl"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#edf4f0] p-2.5 text-[#0b493b]"><UsersRound className="h-5 w-5"/></div><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0f5b49]">Firm establishment</p><h2 className="text-xl font-semibold tracking-tight text-slate-950">Identity first. Authority second. Workspace last.</h2></div></div><p className="mt-3 text-sm leading-6 text-slate-500">Roles become authority only through accepted firm membership. Matter access, ethical walls and server-side permissions remain authoritative.</p></div><div className="grid grid-cols-2 gap-2"><Metric value={pendingCount} label="Pending" icon={<Clock3 className="h-3.5 w-3.5"/>}/><Metric value={acceptedCount} label="Accepted" icon={<Check className="h-3.5 w-3.5"/>}/></div></div>
  <div className="mt-6 grid gap-5 xl:grid-cols-[.82fr_1.18fr]">
   <form onSubmit={invite} className="rounded-[1.4rem] border border-slate-200 bg-[#fbfcfb] p-5"><div className="flex items-center gap-2"><MailPlus className="h-4 w-4 text-[#0b493b]"/><h3 className="text-sm font-bold">Invite a firm member</h3></div><div className="mt-4 space-y-4"><Field label="Email address"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="member@firm.com" className="input"/></Field><Field label="Firm role"><select value={roleKey} onChange={e=>setRoleKey(e.target.value)} className="input font-semibold">{roles.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><div className="rounded-xl border border-emerald-100 bg-emerald-50/60 p-3.5"><div className="flex gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-700"/><div><p className="text-xs font-bold text-emerald-900">{selectedRole?.[1]}</p><p className="mt-1 text-xs leading-5 text-emerald-800/75">{selectedRole?.[2]}. Final authority remains membership and matter governed.</p></div></div></div><Field label="Invitation expiry"><select value={lifetimeHours} onChange={e=>setLifetimeHours(e.target.value)} className="input"><option value="24">24 hours</option><option value="72">3 days</option><option value="168">7 days</option><option value="336">14 days</option><option value="720">30 days</option></select></Field></div><button disabled={submitting||!email.trim()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#082b22] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{submitting?<Loader2 className="h-4 w-4 animate-spin"/>:<UserPlus className="h-4 w-4"/>}{submitting?"Creating invitation…":"Create governed invitation"}</button>{latestInviteUrl?<div className="mt-4 rounded-xl border border-amber-100 bg-amber-50 p-3"><p className="text-[9px] font-black uppercase tracking-[.13em] text-amber-700">Invitation link</p><div className="mt-2 flex gap-2"><input readOnly value={latestInviteUrl} className="min-w-0 flex-1 rounded-lg border border-amber-200 bg-white px-3 py-2 text-xs"/><button type="button" onClick={()=>void copy()} className="inline-flex items-center gap-1.5 rounded-lg bg-amber-900 px-3 py-2 text-xs font-bold text-white">{copied?<Check className="h-3.5 w-3.5"/>:<Copy className="h-3.5 w-3.5"/>}{copied?"Copied":"Copy"}</button></div></div>:null}</form>
   <div className="rounded-[1.4rem] border border-slate-200 p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.17em] text-slate-400">Invitation ledger</p><h3 className="mt-1 text-base font-bold">Access lifecycle</h3></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-500"><RefreshCw className={`h-3.5 w-3.5 ${loading?"animate-spin":""}`}/>Refresh</button></div>{error?<div className="mt-4 flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700"><AlertTriangle className="h-4 w-4 shrink-0"/>{error}</div>:null}{message?<div className="mt-4 rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">{message}</div>:null}<div className="mt-4 space-y-2">{loading?<div className="grid min-h-40 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#0b493b]"/></div>:invitations.length===0?<div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-5 text-center text-sm text-slate-500">No invitations issued yet.</div>:invitations.map(i=><Row key={i.id} invitation={i} busy={busyId===i.id} revoke={revoke} refresh={refresh}/>)}</div></div>
  </div><style jsx>{`.input{margin-top:.5rem;width:100%;border:1px solid #e2e8f0;border-radius:.75rem;background:white;padding:.75rem .875rem;font-size:.875rem;outline:none}.input:focus{border-color:#7da797}`}</style>
 </section>
}
function Row({invitation,busy,revoke,refresh}:{invitation:Invitation;busy:boolean;revoke:(id:string)=>Promise<void>;refresh:(i:Invitation)=>Promise<void>}){const pending=invitation.status==="pending";const tone=invitation.status==="accepted"?"bg-emerald-50 text-emerald-700":pending?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500";return <div className="flex flex-col gap-3 rounded-xl border border-slate-100 px-3.5 py-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-bold">{invitation.email}</p><span className={`rounded-full px-2 py-0.5 text-[8px] font-black uppercase tracking-[.1em] ${tone}`}>{invitation.status}</span></div><p className="mt-1 text-[10px] text-slate-400">{label(invitation.role_key)} · expires {dateLabel(invitation.expires_at)}</p></div><div className="flex gap-2">{pending?<button disabled={busy} onClick={()=>void refresh(invitation)} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-[10px] font-bold"><RefreshCw className={`h-3 w-3 ${busy?"animate-spin":""}`}/>Refresh</button>:null}{pending?<button disabled={busy} onClick={()=>void revoke(invitation.id)} className="inline-flex items-center gap-1 rounded-lg border border-red-100 px-2.5 py-1.5 text-[10px] font-bold text-red-600"><XCircle className="h-3 w-3"/>Revoke</button>:null}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-[9px] font-black uppercase tracking-[.14em] text-slate-500">{label}</span>{children}</label>}
function Metric({value,label,icon}:{value:number;label:string;icon:React.ReactNode}){return <div className="min-w-24 rounded-xl border border-slate-200 bg-[#fbfcfb] px-3 py-2.5"><span className="text-[#0b493b]">{icon}</span><p className="mt-2 text-lg font-semibold">{value}</p><p className="text-[8px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p></div>}
function label(key:string){return roles.find(([value])=>value===key)?.[1]??key.replaceAll("_"," ")}
function dateLabel(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}
