"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, ClipboardCheck, FileText, Mic, ShieldCheck, Sparkles } from "lucide-react";

type Policy={call_recording_enabled?:boolean;transcription_enabled?:boolean;walk_in_enabled?:boolean;ai_extraction_enabled?:boolean};
type FormDef={id:string;name:string;description?:string|null;module:string;status:string};

export default function IntakeLaunchpad(){
 const[policy,setPolicy]=useState<Policy|null>(null);const[forms,setForms]=useState<FormDef[]>([]);const[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/interactions",{cache:"no-store",credentials:"include"}).then(r=>r.json()),fetch("/api/forms",{cache:"no-store",credentials:"include"}).then(r=>r.json())]).then(([i,f])=>{if(i.success)setPolicy(i.policy||null);if(f.success)setForms(f.forms||[])}).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load intake tools."))},[]);
 const intakeForms=useMemo(()=>forms.filter(f=>f.status==="published"&&["intake","client","client_intake","kyc","engagement"].some(key=>f.module.toLowerCase().includes(key))).slice(0,4),[forms]);
 return <section className="mx-auto mt-5 max-w-[1760px] px-4 md:px-8"><div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
  <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#0f5b49]">Master intake · consultation capture</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">Record the first conversation properly.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Walk-in, office meeting or phone consultation can create a governed interaction with explicit consent, real microphone audio and transcription when the firm policy allows it.</p></div><div className="flex gap-2"><Status label="Recording" enabled={Boolean(policy?.call_recording_enabled)}/><Status label="Transcription" enabled={Boolean(policy?.transcription_enabled)}/></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/interactions" className="group flex items-center gap-3 rounded-2xl bg-[#082b22] p-4 text-white"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Mic className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="text-sm font-bold">Capture consultation</p><p className="mt-1 text-xs text-white/50">Notes + actual microphone audio</p></div><ArrowRight className="h-4 w-4 opacity-50 transition group-hover:translate-x-0.5"/></Link><Link href="/studio/operations" className="group flex items-center gap-3 rounded-2xl border border-slate-200 bg-[#fbfcfb] p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf4f0] text-[#0f5b49]"><ShieldCheck className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="text-sm font-bold">Interaction policy</p><p className="mt-1 text-xs text-slate-500">Recording, consent, transcription and AI</p></div><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5"/></Link></div>{!policy?.call_recording_enabled||!policy?.transcription_enabled?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900">A disabled policy is shown here immediately. Enable it in Firm Studio → Privacy, interaction & AI, save once, then return to intake.</div>:<div className="mt-4 rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-xs leading-5 text-emerald-900"><Sparkles className="mr-1.5 inline h-3.5 w-3.5"/>Recording and transcription are enabled for this firm. Participant consent is still required before audio is stored.</div>}</div>
  <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#0f5b49]">Firm-controlled forms</p><h2 className="mt-1 text-xl font-semibold text-slate-950">Start a structured intake record</h2></div><ClipboardCheck className="h-5 w-5 text-[#0f5b49]"/></div><div className="mt-4 space-y-2">{intakeForms.map(form=><Link key={form.id} href={`/forms/${form.id}`} className="group flex items-center gap-3 rounded-xl border border-slate-100 p-3 hover:bg-[#f4f8f6]"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><FileText className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{form.name}</p><p className="mt-0.5 truncate text-[11px] text-slate-400">{form.description||form.module}</p></div><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5"/></Link>)}{intakeForms.length===0&&<div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">No published intake form is available yet. Publish one in Firm Studio.</div>}</div><Link href="/forms" className="mt-4 inline-flex items-center gap-1.5 text-xs font-bold text-[#0f5b49]">Open all controlled forms <ArrowRight className="h-3.5 w-3.5"/></Link>{message&&<p className="mt-3 text-xs text-amber-700">{message}</p>}</div>
 </div></section>
}
function Status({label,enabled}:{label:string;enabled:boolean}){return <span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-[.1em] ${enabled?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{label}: {enabled?"on":"off"}</span>}
