"use client";
import { useState } from "react";

type Mode="execution"|"outcome";
export default function MatterOperatingActions({matterId}:{matterId:string}){
 const[mode,setMode]=useState<Mode|null>(null);const[text,setText]=useState("");const[detail,setDetail]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState<string|null>(null);
 async function save(){if(!mode||!text.trim())return;setBusy(true);setNotice(null);const payload=mode==="execution"?{action:"create_execution",title:text.trim(),actionType:"professional_action",executionMode:"human_assisted"}:{action:"record_outcome",title:text.trim(),resultSummary:detail.trim()||text.trim(),reusableLesson:detail.trim()||null};
  try{const res=await fetch(`/api/matters/${matterId}/operating`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||"Unable to save.");setMode(null);setText("");setDetail("");setNotice(mode==="execution"?"Execution action added to the governed matter chain.":"Outcome added for closure and institutional learning.");window.location.reload();}catch(error){setNotice(error instanceof Error?error.message:"Unable to save.");}finally{setBusy(false);}}
 return <section className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#0f5b49]">Execution & outcome</p><p className="mt-1 text-sm font-semibold text-slate-800">Turn professional judgment into governed action, then preserve what the firm learned.</p></div><div className="flex gap-2"><button onClick={()=>{setMode("execution");setText("");setDetail("");setNotice(null)}} className="rounded-xl bg-[#0b493b] px-3.5 py-2 text-xs font-bold text-white">Plan execution</button><button onClick={()=>{setMode("outcome");setText("");setDetail("");setNotice(null)}} className="rounded-xl border border-[#0b493b]/20 bg-[#f4f8f6] px-3.5 py-2 text-xs font-bold text-[#0b493b]">Record outcome</button></div></div>
  {mode?<div className="mt-4 grid gap-3 rounded-2xl bg-slate-50 p-4"><input value={text} onChange={e=>setText(e.target.value)} placeholder={mode==="execution"?"Action to execute (file, send, sign, obtain, pay, follow up…)":"Outcome title"} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#0b493b]"/>{mode==="outcome"?<textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Result, client impact and reusable lesson" className="min-h-24 rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-[#0b493b]"/>:null}<div className="flex gap-2"><button disabled={busy||!text.trim()} onClick={save} className="rounded-xl bg-[#0b493b] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{busy?"Saving…":"Save to matter chain"}</button><button onClick={()=>setMode(null)} className="px-3 py-2 text-xs font-bold text-slate-500">Cancel</button></div></div>:null}
  {notice?<p className="mt-3 text-xs font-semibold text-slate-600">{notice}</p>:null}
 </section>
}
