"use client";
import { useCallback,useEffect,useState } from "react";
import { Archive, CheckCircle2, LockKeyhole } from "lucide-react";

type Payload={success:boolean;error?:string;matter?:{status:string};review?:any;openTaskCount?:number;documentsArchived?:boolean;clientNotified?:boolean;latestReconciliation?:any};
export default function MatterClosurePanel({matterId}:{matterId:string}){
 const [data,setData]=useState<Payload|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const [form,setForm]=useState({outcomeSummary:"",clientOutcome:"",lessonsLearned:"",financialReconciled:false,obligationsResolved:false,documentsArchived:false,clientNotified:false,knowledgeReviewed:false});
 const load=useCallback(async()=>{const r=await fetch(`/api/matters/${matterId}/closure`,{cache:"no-store"});const d=await r.json();setData(d);if(d.review)setForm({outcomeSummary:d.review.outcome_summary||"",clientOutcome:d.review.client_outcome||"",lessonsLearned:d.review.lessons_learned||"",financialReconciled:Boolean(d.review.financial_reconciled),obligationsResolved:Boolean(d.review.obligations_resolved),documentsArchived:Boolean(d.review.documents_archived),clientNotified:Boolean(d.review.client_notified),knowledgeReviewed:Boolean(d.review.knowledge_reviewed)});if(!d.success)setMsg(d.error||"Unable to load closure")},[matterId]);
 useEffect(()=>{void load()},[load]);
 async function post(action:string){setBusy(true);setMsg("");try{const r=await fetch(`/api/matters/${matterId}/closure`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...form})});const d=await r.json();if(!r.ok||!d.success)throw new Error((d.failures||[]).join(" ")||d.error||"Closure action failed");setMsg(action==="approveClose"?"Matter formally closed.":"Closure review saved.");await load();}catch(e){setMsg(e instanceof Error?e.message:"Closure action failed")}finally{setBusy(false)}}
 const checks=[['financialReconciled','Finance reconciled'],['obligationsResolved','Obligations resolved'],['documentsArchived','Documents archived / filed'],['clientNotified','Client notified'],['knowledgeReviewed','Knowledge & lessons reviewed']] as const;
 return <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex items-start gap-3"><Archive className="mt-1 h-5 w-5 text-[#0f5b49]"/><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#0f5b49]">Closure & institutional memory</p><h2 className="mt-2 text-2xl font-semibold text-slate-950">Close only after the matter is genuinely complete</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Closure checks finance, obligations, documents, client notification and knowledge capture before the matter is locked as closed.</p></div></div>{msg&&<div className="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600">{msg}</div>}<div className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-3"><textarea value={form.outcomeSummary} onChange={e=>setForm({...form,outcomeSummary:e.target.value})} placeholder="Outcome summary" className="min-h-24 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/><textarea value={form.clientOutcome} onChange={e=>setForm({...form,clientOutcome:e.target.value})} placeholder="Client outcome in plain language" className="min-h-20 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/><textarea value={form.lessonsLearned} onChange={e=>setForm({...form,lessonsLearned:e.target.value})} placeholder="Lessons learned / institutional memory" className="min-h-24 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div><div className="rounded-2xl border border-slate-100 p-4"><p className="text-sm font-semibold text-slate-950">Closure controls</p><div className="mt-3 space-y-2">{checks.map(([key,label])=><label key={key} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-3 py-2.5 text-sm"><span>{label}</span><input type="checkbox" checked={form[key]} onChange={e=>setForm({...form,[key]:e.target.checked})}/></label>)}</div><div className="mt-3 text-xs text-slate-500">Open tasks detected: {data?.openTaskCount??0}</div><div className="mt-1 text-xs text-slate-500">Latest reconciliation: {data?.latestReconciliation?.status||"none"}</div></div></div><div className="mt-5 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void post("save")} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold"><CheckCircle2 className="h-4 w-4"/>Save closure review</button><button disabled={busy||data?.matter?.status==="Closed"} onClick={()=>void post("approveClose")} className="inline-flex items-center gap-2 rounded-xl bg-[#083126] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><LockKeyhole className="h-4 w-4"/>{data?.matter?.status==="Closed"?"Matter closed":"Approve & close matter"}</button></div></section>;
}
