"use client";
import { useState } from "react";

type Claim={id:string;claim_type:string;statement:string;verification_status:string};
type Communication={id:string;channel:string;body_text:string|null;processing_status:string;instruction_candidate:boolean;evidence_candidate:boolean};
type Pack={id:string;system_label:string;version:string};
type Knowledge={id:string;title:string;summary:string};
type Outcome={id:string;title:string;knowledge_status:string};

export default function MatterIntelligencePanel({matterId,claims,communications,jurisdictionPacks,knowledge,outcomes}:{matterId:string;claims:Claim[];communications:Communication[];jurisdictionPacks:Pack[];knowledge:Knowledge[];outcomes:Outcome[]}){
 const[mode,setMode]=useState<"claim"|"communication"|null>(null);const[text,setText]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState<string|null>(null);
 async function post(payload:Record<string,unknown>){setBusy(true);setNotice(null);try{const res=await fetch(`/api/matters/${matterId}/intelligence`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||"Unable to save.");setText("");setMode(null);setNotice("Matter intelligence updated.");window.location.reload();}catch(error){setNotice(error instanceof Error?error.message:"Unable to save.");}finally{setBusy(false);}}
 const reviewComms=communications.filter(x=>x.processing_status==="review_required");
 const promotable=outcomes.filter(x=>x.knowledge_status==="approved_internal");
 return <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#0f5b49]">Legal intelligence & institutional memory</p><h2 className="mt-1 text-xl font-semibold text-slate-900">Verified reasoning, jurisdiction and reusable firm knowledge</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">Material propositions remain reviewable and source-linked. Reviewed communications can become governed instructions/evidence, while approved outcomes become firm knowledge.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setMode("claim")} className="rounded-xl bg-[#0b493b] px-3.5 py-2 text-xs font-bold text-white">Record proposition</button><button onClick={()=>setMode("communication")} className="rounded-xl border border-[#0b493b]/20 bg-[#f4f8f6] px-3.5 py-2 text-xs font-bold text-[#0b493b]">Capture communication</button>{!jurisdictionPacks.length?<button disabled={busy} onClick={()=>post({action:"refresh_jurisdiction_pack"})} className="rounded-xl border border-amber-300 bg-amber-50 px-3.5 py-2 text-xs font-bold text-amber-800 disabled:opacity-40">Review jurisdiction sources</button>:null}</div></div>
  <div className="mt-5 grid gap-3 lg:grid-cols-4"><Metric label="Verified claims" value={claims.filter(x=>["verified","corroborated"].includes(x.verification_status)).length}/><Metric label="Needs review" value={reviewComms.length}/><Metric label="Jurisdiction packs" value={jurisdictionPacks.length}/><Metric label="Firm knowledge" value={knowledge.length}/></div>
  {mode?<div className="mt-4 rounded-2xl bg-slate-50 p-4"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={mode==="claim"?"Fact, issue, legal proposition, authority or recommendation to verify":"Email, WhatsApp, call or meeting note to place into the Matter record"} className="min-h-24 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-[#0b493b]"/><div className="mt-3 flex gap-2"><button disabled={busy||!text.trim()} onClick={()=>post(mode==="claim"?{action:"record_claim",claimType:"fact",statement:text}:{action:"record_communication",channel:"other",direction:"inbound",bodyText:text,instructionCandidate:true,evidenceCandidate:true})} className="rounded-xl bg-[#0b493b] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{busy?"Saving…":"Add to governed record"}</button><button onClick={()=>setMode(null)} className="px-3 py-2 text-xs font-bold text-slate-500">Cancel</button></div></div>:null}
  <div className="mt-5 grid gap-4 xl:grid-cols-2">
   <div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-black uppercase tracking-[.12em] text-slate-500">Claims needing judgment</p><div className="mt-3 space-y-2">{claims.filter(x=>x.verification_status==="unverified").slice(0,4).map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-700">{x.claim_type}</p><p className="mt-1 text-xs leading-5 text-slate-600">{x.statement}</p><div className="mt-2 flex gap-2"><button onClick={()=>post({action:"verify_claim",id:x.id,status:"verified"})} className="text-[10px] font-black uppercase tracking-[.1em] text-[#0b493b]">Verify</button><button onClick={()=>post({action:"verify_claim",id:x.id,status:"disputed"})} className="text-[10px] font-black uppercase tracking-[.1em] text-amber-700">Dispute</button></div></div>)}{!claims.some(x=>x.verification_status==="unverified")?<Empty text="No unverified legal/factual propositions."/>:null}</div></div>
   <div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-black uppercase tracking-[.12em] text-slate-500">Communication review</p><div className="mt-3 space-y-2">{reviewComms.slice(0,4).map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-700">{x.channel}</p><p className="mt-1 line-clamp-3 text-xs leading-5 text-slate-600">{x.body_text}</p><p className="mt-1 text-[10px] text-slate-400">{x.instruction_candidate?"Instruction candidate":""}{x.instruction_candidate&&x.evidence_candidate?" · ":""}{x.evidence_candidate?"Evidence candidate":""}</p><div className="mt-2 flex gap-2"><button onClick={()=>post({action:"review_communication",id:x.id,status:"promoted"})} className="text-[10px] font-black uppercase tracking-[.1em] text-[#0b493b]">Promote to governed record</button><button onClick={()=>post({action:"review_communication",id:x.id,status:"ignored"})} className="text-[10px] font-black uppercase tracking-[.1em] text-slate-500">Ignore</button></div></div>)}{!reviewComms.length?<Empty text="No communication items waiting for review."/>:null}</div></div>
  </div>
  {jurisdictionPacks.length?<div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-bold text-slate-700">Jurisdiction coverage</p><p className="mt-1 text-xs leading-5 text-slate-500">{jurisdictionPacks.map(p=>`${p.system_label} (${p.version})`).join(" · ")}. Pack activation is based on the firm’s ready legal-source corpus and professional review, not generated law.</p></div>:null}
  {promotable.length?<div className="mt-4 rounded-2xl border border-[#0b493b]/15 bg-[#f4f8f6] p-4"><p className="text-xs font-bold text-[#0b493b]">Institutional memory</p><div className="mt-2 flex flex-wrap gap-2">{promotable.map(o=><button key={o.id} onClick={()=>post({action:"promote_outcome",outcomeId:o.id})} className="rounded-xl bg-white px-3 py-2 text-xs font-semibold text-slate-700 shadow-sm">Promote “{o.title}” to firm knowledge</button>)}</div></div>:null}
  {notice?<p className="mt-3 text-xs font-semibold text-slate-600">{notice}</p>:null}
 </section>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-[#f8faf8] p-4"><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">{text}</p>}
