"use client";
import { useCallback, useEffect, useState } from "react";

type Mode="execution"|"outcome";
type Execution={id:string;title:string;status:string;execution_mode:string;target_system?:string|null;external_reference?:string|null;evidence_reference?:string|null};
type Outcome={id:string;title:string;result_summary:string;knowledge_status:string;reusable_lesson?:string|null;precedent_candidate?:boolean};

export default function MatterOperatingActions({matterId}:{matterId:string}){
 const[mode,setMode]=useState<Mode|null>(null);const[text,setText]=useState("");const[detail,setDetail]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState<string|null>(null);const[executions,setExecutions]=useState<Execution[]>([]);const[outcomes,setOutcomes]=useState<Outcome[]>([]);const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setLoadError(null);try{const res=await fetch(`/api/matters/${matterId}/operating`,{cache:"no-store",credentials:"include"});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||"Unable to load matter operating records.");setExecutions(data.executions??[]);setOutcomes(data.outcomes??[]);}catch(error){setExecutions([]);setOutcomes([]);setLoadError(error instanceof Error?error.message:"Unable to load matter operating records.");}finally{setLoading(false);}},[matterId]);
 useEffect(()=>{void load()},[load]);
 async function post(payload:Record<string,unknown>){setBusy(true);setNotice(null);try{const res=await fetch(`/api/matters/${matterId}/operating`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||"Unable to save.");await load();return true;}catch(error){setNotice(error instanceof Error?error.message:"Unable to save.");return false;}finally{setBusy(false);}}
 async function save(){if(!mode||!text.trim())return;const ok=await post(mode==="execution"?{action:"create_execution",title:text.trim(),actionType:"professional_action",executionMode:"human_assisted"}:{action:"record_outcome",title:text.trim(),resultSummary:detail.trim()||text.trim(),reusableLesson:detail.trim()||null});if(ok){setMode(null);setText("");setDetail("");setNotice(mode==="execution"?"Execution action added to the governed matter chain.":"Outcome added for closure and institutional learning.");}}
 async function advanceExecution(id:string,status:string){const ok=await post({action:"advance_execution",id,status});if(ok)setNotice(`Execution moved to ${status.replaceAll("_"," ")}.`)}
 async function reviewOutcome(id:string,knowledgeStatus:string){const ok=await post({action:"review_outcome",id,knowledgeStatus});if(ok)setNotice(`Knowledge status changed to ${knowledgeStatus.replaceAll("_"," ")}.`)}
 return <section className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#0f5b49]">Execution & outcome</p><p className="mt-1 text-sm font-semibold text-slate-800">Turn professional judgment into governed action, then preserve what the firm learned.</p></div><div className="flex gap-2"><button disabled={busy||loading||Boolean(loadError)} onClick={()=>{setMode("execution");setText("");setDetail("");setNotice(null)}} className="rounded-xl bg-[#0b493b] px-3.5 py-2 text-xs font-bold text-white">Plan execution</button><button disabled={busy||loading||Boolean(loadError)} onClick={()=>{setMode("outcome");setText("");setDetail("");setNotice(null)}} className="rounded-xl border border-[#0b493b]/20 bg-[#f4f8f6] px-3.5 py-2 text-xs font-bold text-[#0b493b]">Record outcome</button></div></div>
  {mode?<div className="mt-4 grid gap-3 rounded-2xl bg-slate-50 p-4"><input value={text} onChange={e=>setText(e.target.value)} placeholder={mode==="execution"?"Action to execute (file, send, sign, obtain, pay, follow up…)":"Outcome title"} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#0b493b]"/>{mode==="outcome"?<textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Result, client impact and reusable lesson" className="min-h-24 rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-[#0b493b]"/>:null}<div className="flex gap-2"><button disabled={busy||!text.trim()} onClick={save} className="rounded-xl bg-[#0b493b] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{busy?"Saving…":"Save to matter chain"}</button><button onClick={()=>setMode(null)} className="px-3 py-2 text-xs font-bold text-slate-500">Cancel</button></div></div>:null}
  {loadError?<div role="alert" className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><p>{loadError}</p><button type="button" onClick={()=>void load()} className="mt-2 font-semibold underline">Retry loading matter records</button></div>:null}
  {loading?<p role="status" className="mt-4 text-sm text-slate-500">Loading governed matter records…</p>:null}
  {!loading&&!loadError?<div className="mt-5 grid gap-4 xl:grid-cols-2">
   <div><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.15em] text-slate-500">Open execution</p><span className="text-xs font-bold text-slate-400">{executions.length}</span></div><div className="mt-2 space-y-2">{executions.slice(0,6).map(item=><div key={item.id} className="rounded-2xl border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold text-slate-800">{item.title}</p><p className="mt-1 text-[11px] text-slate-500">{item.execution_mode.replaceAll("_"," ")} · {item.status.replaceAll("_"," ")}</p></div><div className="flex flex-wrap gap-1.5">{nextExecutionActions(item.status).map(next=><button disabled={busy} key={next} onClick={()=>advanceExecution(item.id,next)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-bold text-[#0b493b] disabled:opacity-40">{next.replaceAll("_"," ")}</button>)}</div></div></div>)}{!executions.length?<Empty text="No governed execution action yet."/>:null}</div></div>
   <div><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.15em] text-slate-500">Outcome & knowledge</p><span className="text-xs font-bold text-slate-400">{outcomes.length}</span></div><div className="mt-2 space-y-2">{outcomes.slice(0,6).map(item=><div key={item.id} className="rounded-2xl border border-slate-200 p-3"><p className="text-sm font-semibold text-slate-800">{item.title}</p><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-slate-500">{item.result_summary}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><span className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-400">{item.knowledge_status.replaceAll("_"," ")}</span><div className="flex flex-wrap gap-1.5">{nextKnowledgeActions(item.knowledge_status).map(next=><button disabled={busy} key={next} onClick={()=>reviewOutcome(item.id,next)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-bold text-[#0b493b] disabled:opacity-40">{next.replaceAll("_"," ")}</button>)}</div></div></div>)}{!outcomes.length?<Empty text="No outcome captured for institutional learning yet."/>:null}</div></div>
  </div>:null}
  {notice?<p className="mt-3 text-xs font-semibold text-slate-600">{notice}</p>:null}
 </section>
}
function nextExecutionActions(status:string){switch(status){case"planned":return["ready","cancelled"];case"ready":return["awaiting_approval","in_progress"];case"awaiting_approval":return["in_progress","cancelled"];case"in_progress":return["submitted","failed"];case"submitted":return["acknowledged","failed"];case"acknowledged":return["completed","failed"];case"failed":return["ready","cancelled"];default:return[]}}
function nextKnowledgeActions(status:string){switch(status){case"draft":return["reviewed","restricted","not_reusable"];case"reviewed":return["approved_internal","restricted","not_reusable"];default:return[]}}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-slate-200 p-4 text-xs text-slate-400">{text}</div>}
