"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Bot,CheckCircle2,Copy,ExternalLink,MessageSquareText,Send,Share2,ShieldCheck,Sparkles,UserRound} from "lucide-react";
type Lawyer={id:string;full_name:string;role?:string|null};
type Matter={id:string;title:string;client_name:string;case_reference?:string|null};
type Thread={id:string;matter_id?:string|null;title:string;description?:string|null;thread_type:string;status:string};
type Message={id:string;thread_id:string;body:string;message_type:string;created_by?:string|null;created_at:string;metadata?:Record<string,unknown>};
type Payload={success:boolean;error?:string;threads?:Thread[];messages?:Message[];lawyers?:Lawyer[];matters?:Matter[]};
type Review={id:string;reviewer_label?:string|null;reviewer_email?:string|null;access_scope:string;allow_comment:boolean;allow_ai_review:boolean;expires_at:string;revoked_at?:string|null};
export default function ThreadPage({params}:{params:Promise<{threadId:string}>}){
 const[id,setId]=useState("");const[data,setData]=useState<Payload>({success:true});const[body,setBody]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[selected,setSelected]=useState<string[]>([]);const[reviews,setReviews]=useState<Review[]>([]);const[shareUrl,setShareUrl]=useState("");
 useEffect(()=>{void params.then(x=>setId(x.threadId))},[params]);
 async function load(){if(!id)return;try{const [r,rr]=await Promise.all([fetch("/api/workroom",{cache:"no-store",credentials:"include"}),fetch("/api/workroom/external-reviews?threadId="+encodeURIComponent(id),{cache:"no-store",credentials:"include"})]);const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load conversation.");setData(p);if(rr.ok){const rp=await rr.json();if(rp.success)setReviews(rp.reviews||[])}}catch(e){setNotice(e instanceof Error?e.message:"Unable to load conversation.")}}
 useEffect(()=>{void load()},[id]);
 const thread=(data.threads??[]).find(x=>x.id===id);const messages=(data.messages??[]).filter(x=>x.thread_id===id);const lawyers=useMemo(()=>new Map((data.lawyers??[]).map(x=>[x.id,x])),[data.lawyers]);const matter=thread?.matter_id?(data.matters??[]).find(x=>x.id===thread.matter_id):null;
 async function send(e:FormEvent){e.preventDefault();if(!body.trim())return;setBusy(true);setNotice("");try{const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"send_message",threadId:id,body,messageType:"message"})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to send message.");setBody("");await load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to send message.")}finally{setBusy(false)}}
 async function aiReview(){const instruction=window.prompt("What should TSIDKENU AI review?","Flag unresolved issues, missing evidence, contradictions, approvals needed and next actions.");if(!instruction)return;setBusy(true);setNotice("Running governed AI review…");try{const r=await fetch("/api/workroom",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"ai_review",threadId:id,instruction})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"AI review failed.");await load();setNotice("AI review added. It is visibly marked as unapproved AI output until a lawyer adopts it.")}catch(e){setNotice(e instanceof Error?e.message:"AI review failed.")}finally{setBusy(false)}}
 async function createShare(){const reviewerLabel=window.prompt("Reviewer name or label","External reviewer")||"External reviewer";const reviewerEmail=window.prompt("Reviewer email (optional)","")||"";const allowAiReview=window.confirm("Allow this reviewer to request an AI review? The firm must still authorize and run it.");setBusy(true);setNotice("");try{const r=await fetch("/api/workroom/external-reviews",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({threadId:id,reviewerLabel,reviewerEmail,allowComment:true,allowAiReview,expiresInDays:7,selectedMessageIds:selected,title:thread?.title})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to create review link.");setShareUrl(p.shareUrl);await navigator.clipboard?.writeText(p.shareUrl).catch(()=>{});await load();setNotice(selected.length?`Secure link created for ${selected.length} selected message(s) and copied.`:"Secure review link created for this conversation and copied.")}catch(e){setNotice(e instanceof Error?e.message:"Unable to create review link.")}finally{setBusy(false)}}
 async function revokeReview(reviewId:string){setBusy(true);try{const r=await fetch("/api/workroom/external-reviews",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"revoke",id:reviewId})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Revoke failed.");await load();setNotice("External review link revoked.")}catch(e){setNotice(e instanceof Error?e.message:"Revoke failed.")}finally{setBusy(false)}}
 if(!thread)return <main className="min-h-screen bg-[#eef2ef] p-6"><Link href="/workroom">Back to Workroom</Link><p className="mt-4 text-sm text-slate-500">{notice||"Loading conversation…"}</p></main>;
 return <main className="min-h-screen bg-[#e9eeeb] text-slate-900"><div className="mx-auto grid min-h-screen max-w-[1750px] lg:grid-cols-[280px_minmax(0,1fr)_320px]">
  <aside className="hidden border-r border-white/10 bg-[#062f27] p-5 text-white lg:block"><Link href="/workroom" className="inline-flex items-center gap-2 text-xs font-bold text-white/70"><ArrowLeft className="h-4 w-4"/>Workroom</Link><div className="mt-8"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#d8bb79]">Conversation</p><h1 className="mt-2 text-2xl font-semibold leading-tight">{thread.title}</h1>{thread.description&&<p className="mt-3 text-xs leading-6 text-white/55">{thread.description}</p>}</div>{matter&&<Link href={"/matters/"+matter.id} className="mt-6 block rounded-xl border border-white/10 bg-white/[.05] p-3"><p className="text-[9px] font-black uppercase tracking-[.14em] text-white/35">Matter</p><p className="mt-2 text-xs font-bold">{matter.case_reference||"Case"}</p><p className="mt-1 text-xs text-white/50">{matter.client_name} · {matter.title}</p></Link>}<div className="mt-6 space-y-2"><button disabled={busy} onClick={()=>void aiReview()} className="flex w-full items-center gap-2 rounded-xl bg-white px-3 py-2.5 text-left text-xs font-bold text-[#062f27]"><Sparkles className="h-4 w-4"/>AI review</button><button disabled={busy} onClick={()=>void createShare()} className="flex w-full items-center gap-2 rounded-xl border border-white/15 px-3 py-2.5 text-left text-xs font-bold"><Share2 className="h-4 w-4"/>External review link</button></div><div className="mt-6 rounded-xl bg-black/10 p-3 text-[11px] leading-5 text-white/45"><ShieldCheck className="mb-2 h-4 w-4 text-[#d8bb79]"/>AI analysis, external comments and lawyer-approved decisions remain visibly distinct.</div></aside>
  <section className="min-w-0 bg-[#f7f9f7]"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 px-4 py-4 backdrop-blur md:px-6"><div className="flex items-center gap-3"><Link href="/workroom" className="rounded-xl border border-slate-200 p-2 lg:hidden"><ArrowLeft className="h-4 w-4"/></Link><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{thread.title}</p><p className="mt-0.5 text-[10px] uppercase tracking-[.13em] text-slate-400">{thread.thread_type.replaceAll("_"," ")} · {messages.length} messages</p></div><button onClick={()=>void aiReview()} className="hidden rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold md:inline-flex">AI review</button><button onClick={()=>void createShare()} className="rounded-xl bg-[#082b22] px-3 py-2 text-xs font-bold text-white">Share review</button></div></header>
   <div className="mx-auto max-w-4xl px-3 py-5 sm:px-6">{notice&&<div className="mb-4 rounded-xl border border-slate-200 bg-white p-3 text-sm">{notice}</div>}{shareUrl&&<div className="mb-4 flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 p-3"><ExternalLink className="h-4 w-4 text-emerald-700"/><input readOnly value={shareUrl} className="min-w-0 flex-1 bg-transparent text-xs text-emerald-900 outline-none"/><button onClick={()=>navigator.clipboard?.writeText(shareUrl)} className="rounded-lg bg-white p-2"><Copy className="h-3.5 w-3.5"/></button></div>}
    <div className="space-y-2">{messages.map(m=>{const isAi=m.message_type==="ai_review";const author=m.created_by?lawyers.get(m.created_by)?.full_name||"Firm member":"Firm member";const checked=selected.includes(m.id);return <article key={m.id} className={"group rounded-2xl border p-4 shadow-sm "+(isAi?"border-violet-200 bg-violet-50/70":"border-slate-200 bg-white")}><div className="flex items-start gap-3"><div className={"grid h-9 w-9 shrink-0 place-items-center rounded-xl "+(isAi?"bg-violet-100 text-violet-700":"bg-[#edf4f0] text-[#0f5b49]")}>{isAi?<Bot className="h-4 w-4"/>:<UserRound className="h-4 w-4"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold">{isAi?"TSIDKENU AI review":author}</p>{isAi&&<span className="rounded-full bg-violet-100 px-2 py-0.5 text-[9px] font-black uppercase text-violet-700">unapproved AI output</span>}<span className="text-[10px] text-slate-400">{new Date(m.created_at).toLocaleString()}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{m.body}</p>{isAi&&<p className="mt-3 text-[10px] text-violet-600">Provider: {String(m.metadata?.provider||"governed route")} · Model: {String(m.metadata?.model||"configured model")}</p>}</div><label className="opacity-50 transition group-hover:opacity-100"><input type="checkbox" checked={checked} onChange={()=>setSelected(checked?selected.filter(x=>x!==m.id):[...selected,m.id])} aria-label="Select for external review"/></label></div></article>})}{!messages.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><MessageSquareText className="mx-auto h-6 w-6 text-slate-400"/><p className="mt-3 text-sm text-slate-500">Start the conversation.</p></div>}</div>
    <form onSubmit={send} className="sticky bottom-0 mt-5 rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_-10px_40px_rgba(15,23,42,.06)]"><textarea required value={body} onChange={e=>setBody(e.target.value)} className="min-h-20 w-full resize-none bg-transparent p-2 text-sm outline-none" placeholder="Message the team, record a decision context, or hand off work…"/><div className="flex items-center justify-between border-t border-slate-100 pt-2"><p className="text-[10px] text-slate-400">{selected.length?selected.length+" selected for scoped external sharing":"Select messages to share only those externally"}</p><button disabled={busy||!body.trim()} className="inline-flex items-center gap-2 rounded-xl bg-[#082b22] px-4 py-2.5 text-xs font-bold text-white"><Send className="h-3.5 w-3.5"/>Send</button></div></form>
   </div>
  </section>
  <aside className="hidden border-l border-slate-200 bg-white p-5 lg:block"><p className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Review & governance</p><div className="mt-4 rounded-xl bg-[#f4f8f6] p-4"><CheckCircle2 className="h-4 w-4 text-[#0f5b49]"/><p className="mt-3 text-sm font-semibold">External access</p><p className="mt-1 text-xs leading-5 text-slate-500">Links expire, can be revoked, and expose only this thread or specifically selected messages.</p></div><div className="mt-5 space-y-2">{reviews.map(r=><div key={r.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold">{r.reviewer_label||"External reviewer"}</p><p className="mt-1 text-[10px] text-slate-400">{r.access_scope.replaceAll("_"," ")} · expires {new Date(r.expires_at).toLocaleDateString()}</p></div><span className={"rounded-full px-2 py-0.5 text-[8px] font-black uppercase "+(r.revoked_at?"bg-slate-100 text-slate-500":"bg-emerald-50 text-emerald-700")}>{r.revoked_at?"revoked":"active"}</span></div>{!r.revoked_at&&<button onClick={()=>void revokeReview(r.id)} className="mt-3 text-[10px] font-bold text-red-600">Revoke access</button>}</div>)}{!reviews.length&&<p className="text-xs text-slate-400">No external review links yet.</p>}</div><div className="mt-6 rounded-xl border border-violet-100 bg-violet-50 p-4"><Bot className="h-4 w-4 text-violet-700"/><p className="mt-3 text-sm font-semibold">AI is advisory</p><p className="mt-1 text-xs leading-5 text-slate-500">A generated review remains visibly unapproved until the firm uses it in a human decision, task or approved document.</p></div></aside>
 </div></main>
}
