"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,Cpu,RefreshCw,ShieldCheck,TriangleAlert} from "lucide-react";
type Provider={provider:string;configured:boolean;recentRuns:number;recentSucceeded:number;lastRun?:{status:string;model:string;latency_ms?:number|null;error_code?:string|null;created_at:string}|null};
type Payload={success:boolean;error?:string;profile?:Record<string,unknown>|null;policy?:Record<string,unknown>|null;providers?:Provider[];recentRuns?:Array<Record<string,unknown>>};
export default function AiControlPage(){
 const[data,setData]=useState<Payload>({success:true});const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
 async function load(){try{const r=await fetch("/api/ai/health",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load AI health.");setData(p)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load AI health.")}}
 useEffect(()=>{void load()},[]);
 async function test(provider:string){setBusy(provider);setMessage("");try{const r=await fetch("/api/ai/health",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider})});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"AI test failed.");setMessage(provider+" returned usable output via "+p.model+" in "+p.latencyMs+" ms.");await load()}catch(e){setMessage(e instanceof Error?e.message:"AI test failed.")}finally{setBusy("")}}
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-7"><div className="mx-auto max-w-[1500px] space-y-5">
  <div className="flex items-center justify-between gap-3"><Link href="/system" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>System</Link><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-9"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">Governed AI control</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Know which AI route is configured, permitted and actually working.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">A provider is not treated as healthy merely because credentials exist. Run a real completion and inspect the same audit ledger used by TSIDKENU legal work.</p></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
  <section className="grid gap-4 md:grid-cols-3">{(data.providers??[]).map(p=><article key={p.provider} className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-[#edf4f0] p-2.5 text-[#0f5b49]"><Cpu className="h-5 w-5"/></div>{p.configured?<span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-black text-emerald-700">CONFIGURED</span>:<span className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-black text-slate-500">NOT CONFIGURED</span>}</div><h2 className="mt-4 text-xl font-semibold capitalize">{p.provider}</h2><p className="mt-1 text-xs text-slate-500">{p.recentSucceeded}/{p.recentRuns} recent audited runs succeeded</p>{p.lastRun&&<div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-500"><p className="font-semibold text-slate-700">{p.lastRun.model}</p><p className="mt-1">{p.lastRun.status}{p.lastRun.latency_ms?" · "+p.lastRun.latency_ms+" ms":""}</p>{p.lastRun.error_code&&<p className="mt-1 text-red-600">{p.lastRun.error_code}</p>}</div>}<button disabled={!p.configured||busy===p.provider} onClick={()=>void test(p.provider)} className="mt-4 w-full rounded-xl bg-[#082b22] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">{busy===p.provider?"Testing real completion…":"Run real completion test"}</button></article>)}</section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-lg font-semibold">Firm AI route</h2></div><pre className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-5 text-slate-100">{JSON.stringify(data.profile??{},null,2)}</pre></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-lg font-semibold">Firm AI policy</h2></div><pre className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-5 text-slate-100">{JSON.stringify(data.policy??{},null,2)}</pre></div></section>
  <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><TriangleAlert className="mr-1 inline h-4 w-4"/>Highly confidential matters still follow firm privacy policy. A successful cloud-provider test does not override a case that requires local/private AI.</div>
 </div></main>
}
