import { NextResponse } from "next/server";
import { resolveRequestScope } from "@/lib/request-scope";
import { assertFirmPermission } from "@/lib/authorization";
import { createServerSupabaseClient } from "@/lib/supabase-server";

const types = new Set(["matter_type","jurisdiction","court_authority","practice_area","procedure_track","document_type","hearing_type","filing_type","fee_model","risk_level","confidentiality_level","closure_outcome","interaction_type"]);
function keyOf(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80)}

export async function GET(request:Request){
 try{const scope=await resolveRequestScope(request);if(!scope.firmId)throw new Error("Authenticated firm context is required.");const supabase=createServerSupabaseClient();if(!supabase)throw new Error("Supabase server configuration is required.");const result=await supabase.from("firm_legal_parameters").select("id,parameter_type,parameter_key,label_en,label_fr,description,sort_order,active,configuration,updated_at").eq("firm_id",scope.firmId).order("parameter_type").order("sort_order").order("label_en");if(result.error)throw new Error(result.error.message);return NextResponse.json({success:true,parameters:result.data??[]});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:"Unable to load legal parameters."},{status:403})}
}

export async function POST(request:Request){
 try{const scope=await resolveRequestScope(request);await assertFirmPermission({scope,permission:"manageFirm"});if(!scope.firmId||!scope.actorLawyerId)throw new Error("Authenticated firm context is required.");const body=await request.json();const parameterType=String(body.parameterType??"");if(!types.has(parameterType))return NextResponse.json({success:false,error:"Unsupported legal parameter type."},{status:400});const labelEn=String(body.labelEn??"").trim();if(!labelEn)return NextResponse.json({success:false,error:"English label is required."},{status:400});const supabase=createServerSupabaseClient();if(!supabase)throw new Error("Supabase server configuration is required.");const result=await supabase.from("firm_legal_parameters").insert({firm_id:scope.firmId,parameter_type:parameterType,parameter_key:keyOf(String(body.parameterKey||labelEn)),label_en:labelEn,label_fr:String(body.labelFr??"").trim()||null,description:String(body.description??"").trim()||null,sort_order:Number.isFinite(Number(body.sortOrder))?Number(body.sortOrder):100,active:body.active!==false,configuration:body.configuration&&typeof body.configuration==="object"?body.configuration:{},created_by:scope.actorLawyerId,updated_by:scope.actorLawyerId}).select("*").single();if(result.error)throw new Error(result.error.message);return NextResponse.json({success:true,parameter:result.data},{status:201});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:"Unable to create legal parameter."},{status:403})}
}

export async function PATCH(request:Request){
 try{const scope=await resolveRequestScope(request);await assertFirmPermission({scope,permission:"manageFirm"});if(!scope.firmId||!scope.actorLawyerId)throw new Error("Authenticated firm context is required.");const body=await request.json();const id=String(body.id??"").trim();if(!id)return NextResponse.json({success:false,error:"Parameter ID is required."},{status:400});const supabase=createServerSupabaseClient();if(!supabase)throw new Error("Supabase server configuration is required.");const update:Record<string,unknown>={updated_by:scope.actorLawyerId,updated_at:new Date().toISOString()};if("labelEn" in body)update.label_en=String(body.labelEn).trim();if("labelFr" in body)update.label_fr=String(body.labelFr).trim()||null;if("description" in body)update.description=String(body.description).trim()||null;if("sortOrder" in body)update.sort_order=Number(body.sortOrder)||100;if("active" in body)update.active=Boolean(body.active);if("configuration" in body&&body.configuration&&typeof body.configuration==="object")update.configuration=body.configuration;const result=await supabase.from("firm_legal_parameters").update(update).eq("id",id).eq("firm_id",scope.firmId).select("*").single();if(result.error)throw new Error(result.error.message);return NextResponse.json({success:true,parameter:result.data});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:"Unable to update legal parameter."},{status:403})}
}

export async function DELETE(request:Request){
 try{const scope=await resolveRequestScope(request);await assertFirmPermission({scope,permission:"manageFirm"});if(!scope.firmId)throw new Error("Authenticated firm context is required.");const body=await request.json();const id=String(body.id??"").trim();if(!id)return NextResponse.json({success:false,error:"Parameter ID is required."},{status:400});const supabase=createServerSupabaseClient();if(!supabase)throw new Error("Supabase server configuration is required.");const result=await supabase.from("firm_legal_parameters").update({active:false,updated_at:new Date().toISOString()}).eq("id",id).eq("firm_id",scope.firmId).select("id,active").single();if(result.error)throw new Error(result.error.message);return NextResponse.json({success:true,parameter:result.data});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:"Unable to deactivate legal parameter."},{status:403})}
}
