"use client";

import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { ArrowLeft,BookOpenCheck,Landmark,Plus,Save,Settings2,ShieldCheck } from "lucide-react";

type Parameter={id:string;parameter_type:string;parameter_key:string;label_en:string;label_fr?:string|null;description?:string|null;sort_order:number;active:boolean;configuration?:Record<string,unknown>};
const field="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";
const categories=[
 ["matter_type","Matter types"],["jurisdiction","Jurisdictions"],["court_authority","Courts & authorities"],["practice_area","Practice areas"],["procedure_track","Procedure tracks"],["document_type","Document types"],["hearing_type","Hearing types"],["filing_type","Filing types"],["fee_model","Fee models"],["risk_level","Risk levels"],["confidentiality_level","Confidentiality"],["closure_outcome","Closure outcomes"],["interaction_type","Interaction types"]
] as const;

export default function LegalParametersPage(){
 const [parameters,setParameters]=useState<Parameter[]>([]);const [category,setCategory]=useState("matter_type");const [labelEn,setLabelEn]=useState("");const [labelFr,setLabelFr]=useState("");const [description,setDescription]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/firm/legal-parameters",{cache:"no-store"});const p=await r.json();if(!p.success)throw new Error(p.error);setParameters(p.parameters??[])}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 const visible=useMemo(()=>parameters.filter(p=>p.parameter_type===category),[parameters,category]);
 async function add(){if(!labelEn.trim())return;setBusy(true);setMessage("");try{const r=await fetch("/api/firm/legal-parameters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({parameterType:category,labelEn,labelFr,description})});const p=await r.json();if(!p.success)throw new Error(p.error);setLabelEn("");setLabelFr("");setDescription("");setMessage("Legal parameter added.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to add parameter.")}finally{setBusy(false)}}
 async function patch(id:string,changes:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch("/api/firm/legal-parameters",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...changes})});const p=await r.json();if(!p.success)throw new Error(p.error);await load();setMessage("Legal configuration updated.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to update parameter.")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc_0%,#edf3f1_100%)] p-4 text-slate-800 md:p-6 xl:p-8"><div className="mx-auto max-w-[1600px] space-y-5">
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white shadow-xl md:p-8"><Link href="/studio" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-white/60"><ArrowLeft className="h-4 w-4"/>Firm Studio</Link><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-white/50">Legal configuration</p><h1 className="mt-2 text-4xl font-semibold">The firm controls its legal taxonomy.</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">Matter designations, jurisdictions, courts, procedure tracks and document classifications are editable here rather than hard-coded. Changes remain firm-governed and reusable across matters.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-xs text-white/70"><ShieldCheck className="mr-2 inline h-4 w-4"/>Daily users select clear options; governors manage the complexity here.</div></div></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  <section className="grid gap-5 xl:grid-cols-[330px_1fr]">
   <aside className="rounded-[1.6rem] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3 px-2 py-2"><Settings2 className="h-5 w-5 text-emerald-800"/><h2 className="font-semibold text-slate-950">Parameter groups</h2></div><div className="mt-2 space-y-1">{categories.map(([key,label])=><button key={key} onClick={()=>setCategory(key)} className={`w-full rounded-xl px-3 py-2.5 text-left text-sm font-medium ${category===key?"bg-emerald-950 text-white":"text-slate-600 hover:bg-slate-50"}`}>{label}<span className={`ml-2 rounded-full px-2 py-0.5 text-[10px] ${category===key?"bg-white/10":"bg-slate-100"}`}>{parameters.filter(p=>p.parameter_type===key&&p.active).length}</span></button>)}</div></aside>
   <div className="space-y-5">
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Plus className="h-5 w-5 text-emerald-800"/><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Add option</p><h2 className="text-xl font-semibold text-slate-950">{categories.find(c=>c[0]===category)?.[1]}</h2></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className={field} value={labelEn} onChange={e=>setLabelEn(e.target.value)} placeholder="English label"/><input className={field} value={labelFr} onChange={e=>setLabelFr(e.target.value)} placeholder="Libellé français"/></div><textarea className={`${field} mt-3 min-h-24`} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description / when this option should be used (optional)"/><button onClick={add} disabled={busy||!labelEn.trim()} className="mt-3 rounded-2xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Add parameter</button></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><BookOpenCheck className="h-5 w-5 text-emerald-800"/><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Controlled list</p><h2 className="text-xl font-semibold text-slate-950">Active firm options</h2></div></div><div className="mt-4 space-y-3">{visible.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No options in this group yet.</p>:visible.map(p=><ParameterRow key={p.id} parameter={p} busy={busy} save={patch}/>)}</div></div>
    <div className="rounded-[1.6rem] border border-emerald-100 bg-emerald-50 p-5"><div className="flex gap-3"><Landmark className="mt-0.5 h-5 w-5 text-emerald-800"/><div><h3 className="font-semibold text-emerald-950">Procedure Guide integration</h3><p className="mt-1 text-sm leading-6 text-emerald-900/70">These parameters are designed to drive matter classification, Law Bank filtering, procedural checklists and compliance rules so staff do not re-enter the same legal context in multiple modules.</p></div></div></div>
   </div>
  </section>
 </div></main>
}
function ParameterRow({parameter,busy,save}:{parameter:Parameter;busy:boolean;save:(id:string,changes:Record<string,unknown>)=>Promise<void>}){const [en,setEn]=useState(parameter.label_en);const [fr,setFr]=useState(parameter.label_fr??"");const [desc,setDesc]=useState(parameter.description??"");return <div className={`rounded-3xl border p-4 ${parameter.active?"border-slate-100":"border-dashed border-slate-200 opacity-60"}`}><div className="grid gap-3 lg:grid-cols-[1fr_1fr_1.4fr_auto]"><input className={field} value={en} onChange={e=>setEn(e.target.value)}/><input className={field} value={fr} onChange={e=>setFr(e.target.value)} placeholder="French"/><input className={field} value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Description"/><div className="flex gap-2"><button disabled={busy} onClick={()=>save(parameter.id,{labelEn:en,labelFr:fr,description:desc,active:true})} className="inline-flex items-center justify-center rounded-xl bg-slate-900 px-3 text-white disabled:opacity-50"><Save className="h-4 w-4"/></button><button disabled={busy} onClick={()=>save(parameter.id,{active:!parameter.active})} className="rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-600">{parameter.active?"Disable":"Enable"}</button></div></div><p className="mt-2 text-[10px] uppercase tracking-[0.12em] text-slate-400">{parameter.parameter_key}</p></div>}
