"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ClipboardCheck } from "lucide-react";

type Field={id?:string;key:string;type:string;labelEn?:string;labelFr?:string;required?:boolean;placeholderEn?:string;placeholderFr?:string;options?:string[];helpEn?:string;helpFr?:string};
type RuntimeForm={id:string;name:string;description?:string|null;module:string;status:string;schema?:{fields?:Field[]}};
const inputClass="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";

export default function DynamicFirmForm({params}:{params:Promise<{formId:string}>}){
  const [formId,setFormId]=useState("");const [form,setForm]=useState<RuntimeForm|null>(null);const [values,setValues]=useState<Record<string,unknown>>({});const [message,setMessage]=useState("");const [submitted,setSubmitted]=useState(false);const [busy,setBusy]=useState(false);
  useEffect(()=>{void params.then(({formId})=>setFormId(formId));},[params]);
  useEffect(()=>{if(!formId)return;fetch(`/api/forms/${formId}/submissions`,{cache:"no-store"}).then(r=>r.json()).then(data=>{if(!data.success)throw new Error(data.error||"Unable to load form");setForm(data.form);}).catch(error=>setMessage(error instanceof Error?error.message:"Unable to load form"));},[formId]);
  function setValue(key:string,value:unknown){setValues(current=>({...current,[key]:value}));}
  async function submit(event:FormEvent){event.preventDefault();if(!form)return;setBusy(true);setMessage("");try{const response=await fetch(`/api/forms/${form.id}/submissions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data:values})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.validationErrors?.join(" ")||result.error||"Submission failed");setSubmitted(true);setMessage("Submission recorded in the firm operating system.");}catch(error){setMessage(error instanceof Error?error.message:"Submission failed");}finally{setBusy(false);}}
  if(!form)return <main className="min-h-screen bg-slate-50 p-6 text-slate-600">{message||"Loading form…"}</main>;
  const fields=Array.isArray(form.schema?.fields)?form.schema.fields:[];
  return <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc,#edf3f1)] px-4 py-6 md:px-6"><div className="mx-auto max-w-3xl space-y-5"><header className="rounded-[2rem] bg-[#083126] p-6 text-white shadow-lg"><Link href="/workspace" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-white/60"><ArrowLeft className="h-4 w-4"/>Command workspace</Link><div className="mt-5 flex items-start gap-3"><div className="rounded-2xl bg-white/10 p-3"><ClipboardCheck className="h-5 w-5"/></div><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-white/50">{form.module} · controlled form</p><h1 className="mt-1 text-3xl font-semibold">{form.name}</h1><p className="mt-2 text-sm leading-6 text-white/70">{form.description||"Firm-controlled structured record."}</p></div></div></header>
    {message?<div className={`rounded-xl border px-4 py-3 text-sm ${submitted?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{message}</div>:null}
    {submitted?<div className="rounded-[1.6rem] border border-emerald-200 bg-white p-8 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-emerald-700"/><h2 className="mt-4 text-xl font-semibold text-slate-950">Recorded</h2><p className="mt-2 text-sm text-slate-600">The structured submission is now part of the firm's governed record.</p><button onClick={()=>{setSubmitted(false);setValues({});setMessage("");}} className="mt-5 rounded-xl bg-[#083126] px-4 py-2 text-sm font-bold text-white">Start another</button></div>:<form onSubmit={submit} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div className="space-y-5">{fields.map(field=><FieldInput key={field.id||field.key} field={field} value={values[field.key]} onChange={value=>setValue(field.key,value)}/>)}</div>{fields.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">This form has no fields yet. Return to Firm Studio to configure it.</p>:null}<button disabled={busy||fields.length===0} className="mt-6 w-full rounded-xl bg-[#083126] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Submitting…":"Submit controlled record"}</button></form>}
  </div></main>;
}

function FieldInput({field,value,onChange}:{field:Field;value:unknown;onChange:(value:unknown)=>void}){const label=field.labelEn||field.key;const fr=field.labelFr;const placeholder=[field.placeholderEn,field.placeholderFr].filter(Boolean).join(" / ");return <label className="block"><span className="text-sm font-semibold text-slate-900">{label}{field.required?" *":""}</span>{fr?<span className="ml-2 text-xs text-slate-400">/ {fr}</span>:null}{field.type==="textarea"?<textarea required={field.required} value={String(value??"")} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={`${inputClass} min-h-28`}/>:field.type==="select"?<select required={field.required} value={String(value??"")} onChange={e=>onChange(e.target.value)} className={inputClass}><option value="">Select / Choisir</option>{(field.options||[]).map(option=><option key={option} value={option}>{option}</option>)}</select>:field.type==="checkbox"?<div className="mt-2 flex items-center gap-2"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/><span className="text-sm text-slate-500">{placeholder||label}</span></div>:field.type==="file"?<input required={field.required} type="file" disabled className={inputClass} title="Managed upload activation follows storage provider configuration"/>:<input required={field.required} value={String(value??"")} onChange={e=>onChange(e.target.value)} type={field.type==="email"?"email":field.type==="number"?"number":field.type==="date"?"date":field.type==="datetime"?"datetime-local":"text"} placeholder={placeholder} className={inputClass}/>} {field.helpEn||field.helpFr?<p className="mt-1 text-xs text-slate-400">{[field.helpEn,field.helpFr].filter(Boolean).join(" / ")}</p>:null}</label>}
