"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, FileSearch, ShieldAlert, UserCheck } from "lucide-react";

type Review={id:string;legal_name:string;subject_type:string;risk_rating:string;risk_reason?:string|null;pep_status:string;sanctions_status:string;adverse_media_status:string;status:string;created_at:string};
type Payload={success:boolean;error?:string;prospect?:{id:string;prospect_name:string;status:string};reviews?:Review[];evidence?:Array<Record<string,unknown>>};
const inputClass="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";

export default function KycWorkspace({params}:{params:Promise<{prospectId:string}>}){
 const [prospectId,setProspectId]=useState("");const [data,setData]=useState<Payload|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{void params.then(v=>setProspectId(v.prospectId));},[params]);
 const load=useCallback(async()=>{if(!prospectId)return;const r=await fetch(`/api/intake/${prospectId}/kyc`,{cache:"no-store"});const d=await r.json();setData(d);if(!d.success)setMessage(d.error||"Unable to load KYC");},[prospectId]);useEffect(()=>{void load();},[load]);
 async function createReview(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const f=new FormData(event.currentTarget);try{const r=await fetch(`/api/intake/${prospectId}/kyc`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create_review",legalName:f.get("legalName"),subjectType:f.get("subjectType"),nationalityOrCountry:f.get("country"),registrationNumber:f.get("registration"),taxIdentifier:f.get("tax"),address:f.get("address"),sourceOfFunds:f.get("sourceOfFunds"),riskRating:f.get("riskRating"),riskReason:f.get("riskReason")})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"Unable to create KYC review");event.currentTarget.reset();setMessage("KYC review created.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Unable to create KYC review");}finally{setBusy(false);}}
 async function decide(reviewId:string,status:string){setBusy(true);setMessage("");try{const r=await fetch(`/api/intake/${prospectId}/kyc`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({reviewId,status})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"Unable to update KYC");setMessage(`KYC moved to ${status}.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Unable to update KYC");}finally{setBusy(false);}}
 if(!data)return <main className="min-h-screen bg-slate-50 p-6 text-slate-600">Loading KYC workspace…</main>;
 return <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc,#edf3f1)] px-4 py-6 md:px-6"><div className="mx-auto max-w-6xl space-y-5"><header className="rounded-[2rem] bg-[#083126] p-6 text-white"><Link href="/intake" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-white/60"><ArrowLeft className="h-4 w-4"/>Governed intake</Link><div className="mt-5 flex items-start gap-3"><div className="rounded-2xl bg-white/10 p-3"><UserCheck className="h-6 w-6"/></div><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-white/50">Know your client · risk screening</p><h1 className="mt-1 text-3xl font-semibold">{data.prospect?.prospect_name||"Prospect KYC"}</h1><p className="mt-2 text-sm text-white/70">Identity, ownership, source-of-funds and screening evidence before engagement and matter opening.</p></div></div></header>
 {message?<div className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>:null}
 <div className="grid gap-5 xl:grid-cols-[0.85fr_1.15fr]"><form onSubmit={createReview} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><FileSearch className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-xl font-semibold text-slate-950">Open KYC review</h2></div><div className="mt-5 space-y-3"><input name="legalName" required defaultValue={data.prospect?.prospect_name||""} className={inputClass} placeholder="Legal name"/><select name="subjectType" className={inputClass}><option value="individual">Individual</option><option value="company">Company</option><option value="association">Association</option><option value="public_body">Public body</option><option value="other">Other</option></select><div className="grid gap-3 sm:grid-cols-2"><input name="country" className={inputClass} placeholder="Nationality / country"/><input name="registration" className={inputClass} placeholder="Registration number"/><input name="tax" className={inputClass} placeholder="Tax identifier"/><select name="riskRating" className={inputClass}><option value="low">Low risk</option><option value="medium">Medium risk</option><option value="high">High risk</option><option value="prohibited">Prohibited</option></select></div><textarea name="address" className={`${inputClass} min-h-20`} placeholder="Registered / residential address"/><textarea name="sourceOfFunds" className={`${inputClass} min-h-20`} placeholder="Source of funds"/><textarea name="riskReason" className={`${inputClass} min-h-20`} placeholder="Initial risk rationale"/></div><button disabled={busy} className="mt-4 w-full rounded-xl bg-[#083126] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Saving…":"Create KYC review"}</button></form>
 <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-xl font-semibold text-slate-950">Review history & decision gate</h2></div><div className="mt-5 space-y-4">{(data.reviews||[]).length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No KYC review exists yet.</p>:(data.reviews||[]).map(review=><article key={review.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-slate-950">{review.legal_name}</p><p className="mt-1 text-xs uppercase tracking-[0.12em] text-slate-400">{review.subject_type} · {review.risk_rating} risk</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase text-slate-600">{review.status}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Screen label="PEP" value={review.pep_status}/><Screen label="Sanctions" value={review.sanctions_status}/><Screen label="Adverse media" value={review.adverse_media_status}/></div>{review.risk_reason?<p className="mt-3 text-sm text-slate-600">{review.risk_reason}</p>:null}<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void decide(review.id,"under_review")} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Under review</button><button disabled={busy} onClick={()=>void decide(review.id,"enhanced_due_diligence")} className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">Enhanced due diligence</button><button disabled={busy} onClick={()=>void decide(review.id,"cleared")} className="inline-flex items-center gap-1 rounded-xl bg-emerald-700 px-3 py-2 text-xs font-bold text-white"><BadgeCheck className="h-3.5 w-3.5"/>Clear KYC</button><button disabled={busy} onClick={()=>void decide(review.id,"rejected")} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Reject</button></div></article>)}</div></section></div>
 </div></main>;
}
function Screen({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-700">{value.replaceAll("_"," ")}</p></div>}
