"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { ArrowLeft,BrainCircuit,Check,GitBranch,MessageSquareText,Mic,Plus,ShieldCheck,Stethoscope,X } from "lucide-react";

type Extraction={id:string;extraction_type:string;summary:string;detail:Record<string,unknown>;status:string;confidence?:number|null;created_at:string};
type Interaction={id:string;subject?:string|null;interaction_type:string;raw_note?:string|null;transcript_text?:string|null;confidentiality_level:string;ai_analysis_status:string;verification_status:string;client_cycle_stage?:string;substantive_advice_detected?:boolean;consultation_status?:string;consultation_fee_xaf?:number|null;consent_recording?:boolean|null;recording_storage_ref?:string|null;transcript_status?:string};
type Party={id:string;display_name:string;phone?:string|null;email?:string|null;client_status:string};
type Matter={id:string;title:string;client_name?:string|null;status:string;confidentiality_level?:string|null};
type Lawyer={id:string;full_name:string;role?:string|null};
type Payload={success:boolean;error?:string;interaction?:Interaction;extractions?:Extraction[];party?:Party|null;matter?:Matter|null;lawyers?:Lawyer[]};
const field="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";
const types=["fact","changed_fact","contradiction","instruction","commitment","deadline","document","person","organisation","risk","research_question","task","payment","conflict_name","client_update"];

export default function InteractionReviewPage({params}:{params:Promise<{interactionId:string}>}){
 const [id,setId]=useState("");const [data,setData]=useState<Payload>({success:true,extractions:[]});const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [type,setType]=useState("fact");const [summary,setSummary]=useState("");const [consultationFee,setConsultationFee]=useState("");const [recording,setRecording]=useState<File|null>(null);
 useEffect(()=>{void params.then(p=>setId(p.interactionId))},[params]);
 async function load(interactionId=id){if(!interactionId)return;const r=await fetch(`/api/interactions/${interactionId}`,{cache:"no-store"});const p:Payload=await r.json();if(!p.success)throw new Error(p.error||"Unable to load interaction.");setData(p)}
 useEffect(()=>{if(id)void load(id).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load."))},[id]);
 async function act(payload:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch(`/api/interactions/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json();if(!p.success)throw new Error(p.error||"Action failed.");await load();return p}catch(e){setMessage(e instanceof Error?e.message:"Action failed.");return null}finally{setBusy(false)}}
 async function analyse(){setBusy(true);setMessage("");try{const r=await fetch(`/api/interactions/${id}/analyze`,{method:"POST"});const p=await r.json();if(!p.success)throw new Error(p.error||"Analysis failed.");await load();setMessage(`${p.suggestionCount} structured suggestion(s) generated for human review.`)}catch(e){setMessage(e instanceof Error?e.message:"Analysis failed.")}finally{setBusy(false)}}
 async function add(){if(!summary.trim())return;const p=await act({action:"add_extraction",extractionType:type,summary});if(p){setSummary("");setMessage("Observation added for review.")}}
 async function review(extraction:Extraction,decision:"confirmed"|"edited"|"rejected"){const p=await act({action:"review_extraction",extractionId:extraction.id,decision,summary:extraction.summary,materialize:decision!=="rejected"});if(p)setMessage(decision==="rejected"?"Suggestion rejected.":"Confirmed information converted into governed matter work where applicable.")}
 async function convertConsultation(status:"scheduled"|"paid"|"waived"){const p=await act({action:"convert_consultation",consultationStatus:status,consultationFeeXaf:consultationFee?Number(consultationFee):null,reason:"Interaction moved beyond preliminary intake into substantive legal consultation."});if(p)setMessage("Consultation control activated. Substantive advice is now tracked separately from preliminary intake.")}
 async function uploadRecording(){if(!recording)return;setBusy(true);setMessage("");try{const form=new FormData();form.append("file",recording);form.append("transcribe","true");const r=await fetch(`/api/interactions/${id}/recording`,{method:"POST",body:form});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Recording upload failed.");setRecording(null);await load();setMessage("Authorized recording stored. Transcription will run only when the firm policy and configured transcription service permit it.")}catch(e){setMessage(e instanceof Error?e.message:"Recording upload failed.")}finally{setBusy(false)}}
 const interaction=data.interaction;const extractions=data.extractions??[];
 return <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc_0%,#edf3f1_100%)] p-4 text-slate-800 md:p-6 xl:p-8"><div className="mx-auto max-w-[1500px] space-y-5">
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white shadow-xl md:p-8"><Link href="/interactions" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-white/60"><ArrowLeft className="h-4 w-4"/>Interaction desk</Link><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-white/50">Interaction intelligence</p><h1 className="mt-2 text-4xl font-semibold">Review before it becomes legal truth.</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-white/70">Raw conversation or notes stay separate from AI suggestions. Authorised humans confirm facts, tasks, deadlines and commitments before TSIDKENU materialises them into matter work.</p></div><button onClick={analyse} disabled={busy||!interaction||!(interaction.raw_note?.trim()||interaction.transcript_text?.trim())} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-bold text-emerald-950 disabled:opacity-40"><BrainCircuit className="h-4 w-4"/>{busy?"Working…":"Analyse interaction"}</button></div></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
  {!interaction?<div className="rounded-3xl border border-slate-200 bg-white p-8">Loading interaction…</div>:<div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]">
   <section className="space-y-5">
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><MessageSquareText className="h-5 w-5 text-emerald-800"/><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Original interaction</p><h2 className="text-xl font-semibold text-slate-950">{interaction.subject||interaction.interaction_type.replaceAll("_"," ")}</h2></div></div><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-xs font-bold uppercase text-slate-400">Person</dt><dd className="mt-1">{data.party?.display_name||"Unmatched"}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Matter</dt><dd className="mt-1">{data.matter?.title||"Not linked"}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Client cycle</dt><dd className="mt-1">{(interaction.client_cycle_stage||"enquiry").replaceAll("_"," ")}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Confidentiality</dt><dd className="mt-1">{interaction.confidentiality_level.replaceAll("_"," ")}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">AI status</dt><dd className="mt-1">{interaction.ai_analysis_status.replaceAll("_"," ")}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Raw note</dt><dd className="mt-1 whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 leading-6">{interaction.raw_note||"No typed/dictated note."}</dd></div>{interaction.transcript_text&&<div><dt className="text-xs font-bold uppercase text-slate-400">Transcript</dt><dd className="mt-1 max-h-72 overflow-auto whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 leading-6">{interaction.transcript_text}</dd></div>}</dl><div className="mt-4 rounded-2xl bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldCheck className="mr-2 inline h-4 w-4"/>Original record and transcription are sources, not automatically confirmed case facts.</div></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Stethoscope className="h-5 w-5 text-emerald-800"/><h2 className="text-lg font-semibold text-slate-950">Consultation control</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">When a conversation moves beyond reception/intake into substantive legal advice, convert it instead of silently giving an untracked consultation.</p><input type="number" min="0" className={`${field} mt-4`} value={consultationFee} onChange={e=>setConsultationFee(e.target.value)} placeholder="Consultation fee XAF (optional)"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void convertConsultation("scheduled")} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Schedule consultation</button><button disabled={busy} onClick={()=>void convertConsultation("paid")} className="rounded-xl bg-emerald-950 px-3 py-2 text-xs font-bold text-white">Mark paid consultation</button><button disabled={busy} onClick={()=>void convertConsultation("waived")} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Waive fee</button></div><p className="mt-3 text-xs text-slate-500">Current: {(interaction.consultation_status||"not_required").replaceAll("_"," ")}{interaction.consultation_fee_xaf?` · ${new Intl.NumberFormat("fr-CM").format(interaction.consultation_fee_xaf)} XAF`:""}</p></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Mic className="h-5 w-5 text-emerald-800"/><h2 className="text-lg font-semibold text-slate-950">Authorized recording</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">Upload an existing authorized recording only when firm policy allows recording and consent has been positively recorded. Highly confidential matters remain protected.</p><input type="file" accept="audio/*,video/*" className={`${field} mt-4`} onChange={e=>setRecording(e.target.files?.[0]||null)}/><button disabled={busy||!recording} onClick={()=>void uploadRecording()} className="mt-3 rounded-xl bg-emerald-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-40">Store recording + request transcription</button><p className="mt-3 text-xs text-slate-500">Consent: {interaction.consent_recording===true?"recorded":interaction.consent_recording===false?"declined":"not recorded"} · Transcript: {(interaction.transcript_status||"not requested").replaceAll("_"," ")}</p></div>
    <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Plus className="h-5 w-5 text-emerald-800"/><h2 className="text-lg font-semibold text-slate-950">Add human observation</h2></div><select className={`${field} mt-4`} value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t} value={t}>{t.replaceAll("_"," ")}</option>)}</select><textarea className={`${field} mt-3 min-h-24`} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="What was learned / promised / requested?"/><button onClick={add} disabled={busy||!summary.trim()} className="mt-3 rounded-2xl bg-emerald-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Add for review</button></div>
   </section>
   <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><GitBranch className="h-5 w-5 text-emerald-800"/><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Suggestions & confirmed information</p><h2 className="text-xl font-semibold text-slate-950">Convert only what should become work</h2></div></div><div className="mt-5 space-y-3">{extractions.length===0?<p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No structured suggestions yet. Use governed AI analysis or add a human observation.</p>:extractions.map(ex=><div key={ex.id} className="rounded-3xl border border-slate-100 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase text-slate-500">{ex.extraction_type.replaceAll("_"," ")}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${["confirmed","edited"].includes(ex.status)?"bg-emerald-100 text-emerald-800":ex.status==="rejected"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-900"}`}>{ex.status}</span></div><p className="mt-3 text-sm font-semibold leading-6 text-slate-900">{ex.summary}</p></div>{ex.status==="suggested"&&<div className="flex gap-2"><button disabled={busy} onClick={()=>review(ex,"confirmed")} className="rounded-xl bg-emerald-950 p-2 text-white" title="Confirm"><Check className="h-4 w-4"/></button><button disabled={busy} onClick={()=>review(ex,"rejected")} className="rounded-xl border border-slate-200 p-2 text-slate-600" title="Reject"><X className="h-4 w-4"/></button></div>}</div></div>)}</div></section>
  </div>}
 </div></main>
}
