"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,FileCheck2,FileUp,Receipt,ScanLine} from "lucide-react";
type Expense={id:string;matter_id?:string|null;category:string;supplier_name?:string|null;description:string;amount_xaf:number;reference?:string|null;expense_date:string;receipt_file_name?:string|null};
type Matter={id:string;title:string;client_name:string};
type ReceiptRow={id:string;expense_id:string;file_name:string;evidence_type:string;supplier_name?:string|null;receipt_number?:string|null;amount_xaf?:number|null;issued_at?:string|null;extraction_status:string;signed_url?:string|null;extracted_data?:Record<string,unknown>};
export default function ReceiptDesk(){
 const[expenses,setExpenses]=useState<Expense[]>([]);const[matters,setMatters]=useState<Matter[]>([]);const[receipts,setReceipts]=useState<ReceiptRow[]>([]);const[selected,setSelected]=useState("");const[file,setFile]=useState<File|null>(null);const[type,setType]=useState("receipt");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 async function load(){const [b,r]=await Promise.all([fetch("/api/business",{cache:"no-store",credentials:"include"}),fetch("/api/business/receipts",{cache:"no-store",credentials:"include"})]);const bp=await b.json(),rp=await r.json();if(!b.ok||!bp.success)throw new Error(bp.error||"Unable to load expenses.");if(!r.ok||!rp.success)throw new Error(rp.error||"Unable to load receipts.");setExpenses(bp.expenses||[]);setMatters(bp.matters||[]);setReceipts(rp.receipts||[])}
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:"Unable to load receipt desk."))},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!selected||!file)return;setBusy(true);setMessage("");try{const body=new FormData();body.append("expenseId",selected);body.append("evidenceType",type);body.append("file",file);const r=await fetch("/api/business/receipts",{method:"POST",credentials:"include",body});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Receipt upload failed.");setFile(null);await load();setMessage(p.extractionStatus==="completed"?"Receipt stored and evidence fields extracted for review.":"Receipt stored. Automatic extraction was not completed; the evidence remains preserved.")}catch(e){setMessage(e instanceof Error?e.message:"Receipt upload failed.")}finally{setBusy(false)}}
 const matterMap=new Map(matters.map(x=>[x.id,x]));const expenseMap=new Map(expenses.map(x=>[x.id,x]));
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-7"><div className="mx-auto max-w-[1500px] space-y-5">
  <div className="flex items-center justify-between gap-3"><Link href="/business" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Business & Office</Link><span className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-slate-500">{receipts.length} evidence file(s)</span></div>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-9"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">Receipt & Evidence Desk</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Every office and case expense can carry its proof.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Attach receipts, invoices, tax evidence, registrations or payment proof. The original stays in the private vault; supported files are extracted into proposed evidence fields without automatically approving the accounting entry.</p></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
  <form onSubmit={submit} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><ScanLine className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-xl font-semibold">Attach evidence</h2></div><div className="mt-5 grid gap-3 lg:grid-cols-[1.3fr_.6fr_1fr_auto]"><select required className="rounded-xl border border-slate-200 px-3 py-3 text-sm" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select expense</option>{expenses.map(x=><option key={x.id} value={x.id}>{new Date(x.expense_date).toLocaleDateString()} — {x.description} — {Number(x.amount_xaf).toLocaleString()} XAF</option>)}</select><select className="rounded-xl border border-slate-200 px-3 py-3 text-sm" value={type} onChange={e=>setType(e.target.value)}><option value="receipt">Receipt</option><option value="invoice">Invoice</option><option value="registration">Registration</option><option value="tax">Tax proof</option><option value="payment_proof">Payment proof</option><option value="other">Other</option></select><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-slate-300 px-3 py-3 text-sm"><FileUp className="h-4 w-4"/><span className="truncate">{file?.name||"Choose evidence file"}</span><input className="sr-only" type="file" accept="image/*,.pdf,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={busy||!selected||!file} className="rounded-xl bg-[#082b22] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Processing…":"Store & extract"}</button></div></form>
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{receipts.map(r=>{const e=expenseMap.get(r.expense_id);const m=e?.matter_id?matterMap.get(e.matter_id):null;return <article key={r.id} className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-[#edf4f0] p-2.5 text-[#0f5b49]"><Receipt className="h-5 w-5"/></div><span className={"rounded-full px-2.5 py-1 text-[9px] font-black uppercase "+(r.extraction_status==="completed"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700")}>{r.extraction_status}</span></div><p className="mt-4 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">{r.evidence_type.replaceAll("_"," ")}</p><h3 className="mt-1 font-semibold">{r.file_name}</h3><div className="mt-3 space-y-1 text-xs text-slate-500"><p>{r.supplier_name||e?.supplier_name||"Supplier not extracted"}</p><p>{r.receipt_number||e?.reference||"No receipt number"} · {Number(r.amount_xaf??e?.amount_xaf??0).toLocaleString()} XAF</p>{m&&<p>{m.client_name} — {m.title}</p>}</div><div className="mt-4 flex gap-2">{r.signed_url&&<a href={r.signed_url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Open evidence</a>}{e&&<Link href="/business" className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold">Expense register</Link>}</div></article>})}{!receipts.length&&<div className="md:col-span-2 xl:col-span-3 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><FileCheck2 className="mx-auto h-7 w-7 text-slate-400"/><p className="mt-3 text-sm text-slate-500">No receipt evidence stored yet.</p></div>}</section>
 </div></main>
}
