"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BriefcaseBusiness,FileText,FolderSearch2,Search,UserRound} from "lucide-react";
type Case={id:string;title:string;clientName:string;matterType:string;status:string;physicalFileId:string;leadLawyer:string};
type Client={id:string;display_name:string;phone?:string|null;email?:string|null;client_status:string};
type Doc={id:string;matter_id:string;title:string;document_type?:string|null;version_label?:string|null;status?:string|null;case?:Case|null};
type FileResult={id:string;matter_id:string;kind:string;file_code?:string|null;file_label?:string|null;label?:string|null;reference_code?:string|null;location?:string|null;case?:Case|null};
type Payload={success:boolean;error?:string;cases?:Case[];clients?:Client[];documents?:Doc[];files?:FileResult[]};
export default function SearchPage(){
 const[q,setQ]=useState("");const[data,setData]=useState<Payload|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 async function submit(e:FormEvent){e.preventDefault();if(q.trim().length<2)return;setBusy(true);setMessage("");try{const r=await fetch("/api/search?q="+encodeURIComponent(q.trim()),{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Search failed.");setData(p)}catch(e){setMessage(e instanceof Error?e.message:"Search failed.")}finally{setBusy(false)}}
 const count=(data?.cases?.length||0)+(data?.clients?.length||0)+(data?.documents?.length||0)+(data?.files?.length||0);
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-7"><div className="mx-auto max-w-[1600px] space-y-5">
  <Link href="/workspace" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Workspace</Link>
  <section className="rounded-[2rem] bg-[#082b22] p-6 text-white md:p-9"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">Firm Search</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Find the legal record by what you actually remember.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Search case reference, client name, lawyer, phone, email, document title, file code or reference.</p><form onSubmit={submit} className="mt-6 flex max-w-4xl gap-2 rounded-2xl bg-white p-2"><Search className="ml-2 mt-2.5 h-5 w-5 text-slate-400"/><input autoFocus className="min-w-0 flex-1 px-2 text-sm text-slate-900 outline-none" value={q} onChange={e=>setQ(e.target.value)} placeholder="e.g. EDA/LIT/2026, client name, 6xx…, document reference"/><button disabled={busy||q.trim().length<2} className="rounded-xl bg-[#0b493b] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Searching…":"Search"}</button></form></section>
  {message&&<div className="rounded-xl border border-red-200 bg-white p-4 text-sm text-red-700">{message}</div>}
  {data&&<div className="grid gap-5 xl:grid-cols-2">
   <ResultSection icon={BriefcaseBusiness} title={"Cases ("+(data.cases?.length||0)+")"}>{(data.cases??[]).map(x=><Link key={x.id} href={"/matters/"+x.id} className="block rounded-xl border border-slate-100 p-4 hover:border-[#7da797]"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.13em] text-[#0f5b49]">{x.physicalFileId}</p><p className="mt-1 font-semibold">{x.title}</p><p className="mt-1 text-xs text-slate-500">{x.clientName} · {x.matterType}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black uppercase">{x.status}</span></div></Link>)}</ResultSection>
   <ResultSection icon={UserRound} title={"Clients & contacts ("+(data.clients?.length||0)+")"}>{(data.clients??[]).map(x=><div key={x.id} className="rounded-xl border border-slate-100 p-4"><p className="font-semibold">{x.display_name}</p><p className="mt-1 text-xs text-slate-500">{[x.phone,x.email,x.client_status].filter(Boolean).join(" · ")}</p></div>)}</ResultSection>
   <ResultSection icon={FileText} title={"Documents ("+(data.documents?.length||0)+")"}>{(data.documents??[]).map(x=><Link key={x.id} href={x.matter_id?"/matters/"+x.matter_id:"#"} className="block rounded-xl border border-slate-100 p-4"><p className="font-semibold">{x.title}</p><p className="mt-1 text-xs text-slate-500">{x.document_type||"Document"} · {x.version_label||"current"}{x.case?" · "+x.case.physicalFileId:""}</p></Link>)}</ResultSection>
   <ResultSection icon={FolderSearch2} title={"Files & references ("+(data.files?.length||0)+")"}>{(data.files??[]).map(x=><Link key={x.kind+x.id} href={x.matter_id?"/matters/"+x.matter_id:"#"} className="block rounded-xl border border-slate-100 p-4"><p className="font-semibold">{x.file_code||x.reference_code||x.label||x.file_label||"File"}</p><p className="mt-1 text-xs text-slate-500">{x.kind}{x.case?" · "+x.case.physicalFileId:""}{x.location?" · "+x.location:""}</p></Link>)}</ResultSection>
  </div>}
  {data&&count===0&&<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">No matching firm records.</div>}
 </div></main>
}
function ResultSection({icon:Icon,title,children}:{icon:typeof Search;title:string;children:React.ReactNode}){return <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#edf4f0] p-2.5 text-[#0f5b49]"><Icon className="h-4 w-4"/></div><h2 className="text-lg font-semibold">{title}</h2></div><div className="mt-4 space-y-2">{children}</div></section>}
