create index if not exists idx_parties_created_by on public.parties(created_by) where created_by is not null;
create index if not exists idx_parties_updated_by on public.parties(updated_by) where updated_by is not null;
create index if not exists idx_matter_parties_firm on public.matter_parties(firm_id);
create index if not exists idx_matter_parties_party on public.matter_parties(party_id);
create index if not exists idx_legal_interactions_party on public.legal_interactions(primary_party_id) where primary_party_id is not null;
create index if not exists idx_legal_interactions_prospect on public.legal_interactions(prospect_id) where prospect_id is not null;
create index if not exists idx_legal_interactions_assigned on public.legal_interactions(assigned_to) where assigned_to is not null;
create index if not exists idx_legal_interactions_created on public.legal_interactions(created_by) where created_by is not null;
create index if not exists idx_legal_interactions_reviewed on public.legal_interactions(reviewed_by) where reviewed_by is not null;
create index if not exists idx_interaction_extractions_firm on public.interaction_extractions(firm_id);
create index if not exists idx_interaction_extractions_confirmed on public.interaction_extractions(confirmed_by) where confirmed_by is not null;
create index if not exists idx_commitments_firm_status_due on public.matter_commitments(firm_id,status,due_at);
create index if not exists idx_commitments_matter on public.matter_commitments(matter_id) where matter_id is not null;
create index if not exists idx_commitments_interaction on public.matter_commitments(interaction_id) where interaction_id is not null;
create index if not exists idx_commitments_party on public.matter_commitments(party_id) where party_id is not null;
create index if not exists idx_commitments_owner on public.matter_commitments(owner_lawyer_id) where owner_lawyer_id is not null;
create index if not exists idx_commitments_created on public.matter_commitments(created_by) where created_by is not null;
create index if not exists idx_digitisation_batches_firm_status on public.digitisation_batches(firm_id,status,created_at desc);
create index if not exists idx_digitisation_batches_matter on public.digitisation_batches(matter_id) where matter_id is not null;
create index if not exists idx_digitisation_batches_created on public.digitisation_batches(created_by) where created_by is not null;
create index if not exists idx_digitisation_batches_approved on public.digitisation_batches(approved_by) where approved_by is not null;
create index if not exists idx_digitisation_items_matter on public.digitisation_items(matter_id) where matter_id is not null;
create index if not exists idx_digitisation_items_party on public.digitisation_items(party_id) where party_id is not null;
create index if not exists idx_digitisation_items_reviewed on public.digitisation_items(reviewed_by) where reviewed_by is not null;
create index if not exists idx_digitisation_items_duplicate on public.digitisation_items(duplicate_of_document_id) where duplicate_of_document_id is not null;
create index if not exists idx_ai_activity_firm_created on public.ai_activity_ledger(firm_id,created_at desc);
create index if not exists idx_ai_activity_matter on public.ai_activity_ledger(matter_id) where matter_id is not null;
create index if not exists idx_ai_activity_interaction on public.ai_activity_ledger(interaction_id) where interaction_id is not null;
create index if not exists idx_ai_activity_actor on public.ai_activity_ledger(actor_lawyer_id) where actor_lawyer_id is not null;
create index if not exists idx_interaction_policy_updated on public.firm_interaction_policies(updated_by) where updated_by is not null;
create index if not exists idx_ai_policy_updated on public.firm_ai_policies(updated_by) where updated_by is not null;
create index if not exists idx_legal_parameter_created on public.firm_legal_parameters(created_by) where created_by is not null;
create index if not exists idx_legal_parameter_updated on public.firm_legal_parameters(updated_by) where updated_by is not null;
