"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BadgeCheck,BrainCircuit,FileCheck2,FileSearch,FileUp,ReceiptText,ScanLine,ShieldCheck,TriangleAlert} from "lucide-react";

type Intake={id:string;matter_id?:string|null;supplier_id?:string|null;supplier_bill_id?:string|null;expense_id?:string|null;original_name:string;document_kind:string;counterparty_name?:string|null;document_number?:string|null;currency?:string|null;amount?:number|null;tax_amount?:number|null;document_date?:string|null;due_date?:string|null;description?:string|null;extraction_confidence?:number|null;warnings?:string[];review_status:string;proposed_action:string;signed_url?:string|null};
type Supplier={id:string;name:string;category?:string|null};
type Matter={id:string;title:string;client_name:string;case_reference?:string|null};
type Bill={id:string;source_intake_id?:string|null;description:string;total_amount:number;currency:string;status:string;due_at?:string|null};
type Payload={success:boolean;error?:string;items?:Intake[];suppliers?:Supplier[];matters?:Matter[];bills?:Bill[]};
const field="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-[#7da797]";
const money=(n:number|null|undefined,currency="XAF")=>new Intl.NumberFormat("fr-CM",{maximumFractionDigits:0}).format(Number(n||0))+" "+currency;

export default function DocumentIntakePage(){
 const[data,setData]=useState<Payload>({success:true});const[file,setFile]=useState<File|null>(null);const[matterId,setMatterId]=useState("");const[sourceKind,setSourceKind]=useState("upload");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[selectedSupplier,setSelectedSupplier]=useState<Record<string,string>>({});
 async function load(){const r=await fetch("/api/business/documents",{cache:"no-store",credentials:"include"});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Unable to load document intake.");setData(p)}
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:"Unable to load document intake."))},[]);
 async function upload(e:FormEvent){e.preventDefault();if(!file)return;setBusy(true);setMessage("");try{const form=new FormData();form.append("file",file);form.append("matterId",matterId);form.append("sourceKind",sourceKind);const r=await fetch("/api/business/documents",{method:"POST",credentials:"include",body:form});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Document intake failed.");setFile(null);setMatterId("");await load();setMessage("Original preserved. AI extraction is ready for human review before anything is posted.")}catch(e){setMessage(e instanceof Error?e.message:"Document intake failed.")}finally{setBusy(false)}}
 async function action(id:string,action:string,item:Intake){setBusy(true);setMessage("");try{const supplierId=selectedSupplier[id]||item.supplier_id||null;const body:any={id,action,supplierId};if(action==="approve_bill"){body.totalAmount=item.amount??0;body.currency=item.currency||"XAF";body.taxAmount=item.tax_amount??0;body.billNumber=item.document_number||"";body.description=item.description||item.original_name;body.issuedAt=item.document_date||null;body.dueAt=item.due_date||null}if(action==="post_expense"){body.amountXaf=item.currency==="XAF"||!item.currency?item.amount??0:0;body.description=item.description||item.original_name;body.category=item.matter_id?"case":"office"}const r=await fetch("/api/business/documents",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok||!p.success)throw new Error(p.error||"Review action failed.");await load();setMessage(action==="approve_bill"?"Supplier bill approved and obligation created.":action==="post_expense"?"Evidence posted to expense and finance ledger.":"Document rejected.")}catch(e){setMessage(e instanceof Error?e.message:"Review action failed.")}finally{setBusy(false)}}
 const items=data.items??[];const queue=items.filter(x=>!["posted","rejected"].includes(x.review_status));const posted=items.filter(x=>x.review_status==="posted");const bills=data.bills??[];
 const matterMap=useMemo(()=>new Map((data.matters??[]).map(x=>[x.id,x])),[data.matters]);
 return <main className="min-h-screen bg-[#eef2ef] p-4 text-slate-900 md:p-7"><div className="mx-auto max-w-[1750px] space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/business" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Business & Office</Link><div className="flex gap-2"><Link href="/business/operations" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">Suppliers & obligations</Link><Link href="/finance" className="rounded-xl bg-[#082b22] px-4 py-2.5 text-sm font-bold text-white">Finance control</Link></div></div>
  <section className="overflow-hidden rounded-[2rem] bg-[#082b22] text-white"><div className="grid xl:grid-cols-[1fr_460px]"><div className="p-6 md:p-9"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d8bb79]">Intelligent document intake</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Scan it. Understand it. Verify it. Then post it.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Upload a phone photo, scan, PDF or office document. TSIDKENU preserves the original, extracts supported fields, classifies the document and proposes the next action. AI never silently approves accounting.</p></div><div className="grid grid-cols-2 gap-px bg-white/10"><Metric label="Review queue" value={String(queue.length)}/><Metric label="Posted" value={String(posted.length)}/><Metric label="Supplier bills" value={String(bills.length)}/><Metric label="AI-assisted" value={String(items.filter(x=>Number(x.extraction_confidence||0)>0).length)}/></div></div></section>
  {message&&<div className="rounded-2xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
  <form onSubmit={upload} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><ScanLine className="h-5 w-5 text-[#0f5b49]"/><div><h2 className="text-xl font-semibold">Capture evidence</h2><p className="text-xs text-slate-500">Photos and scans are treated as evidence first, data second.</p></div></div><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_.75fr_.6fr_auto]"><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-slate-300 px-3 py-3 text-sm"><FileUp className="h-4 w-4"/><span className="truncate">{file?.name||"Choose photo, scan, PDF or document"}</span><input className="sr-only" type="file" accept="image/*,.pdf,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><select className={field} value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">Firm / office document</option>{(data.matters??[]).map(x=><option key={x.id} value={x.id}>{x.case_reference||"CASE"} · {x.client_name} · {x.title}</option>)}</select><select className={field} value={sourceKind} onChange={e=>setSourceKind(e.target.value)}><option value="upload">Upload</option><option value="mobile_scan">Mobile scan</option><option value="email">Email</option><option value="external_api">External API</option><option value="workroom">Workroom</option></select><button disabled={busy||!file} className="rounded-xl bg-[#082b22] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Reading…":"Store & analyze"}</button></div></form>
  <section className="space-y-3"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Human review queue</p><h2 className="text-2xl font-semibold">AI proposals awaiting a decision</h2></div><ShieldCheck className="h-5 w-5 text-[#0f5b49]"/></div>
   <div className="grid gap-4 xl:grid-cols-2">{queue.map(item=><article key={item.id} className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-[#edf4f0] p-2.5 text-[#0f5b49]"><FileSearch className="h-5 w-5"/></div><div><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#0f5b49]">{item.document_kind.replaceAll("_"," ")}</p><h3 className="font-semibold">{item.original_name}</h3><p className="mt-1 text-xs text-slate-500">{item.matter_id?(matterMap.get(item.matter_id)?.case_reference||"Matter")+" · ":"Firm"}{item.counterparty_name||"Counterparty not extracted"}</p></div></div><span className={"rounded-full px-2.5 py-1 text-[9px] font-black uppercase "+(Number(item.extraction_confidence||0)>=.78?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700")}>{Math.round(Number(item.extraction_confidence||0)*100)}% extraction</span></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-4"><Datum label="Number" value={item.document_number||"—"}/><Datum label="Amount" value={item.amount!=null?money(item.amount,item.currency||""):"—"}/><Datum label="Document date" value={item.document_date||"—"}/><Datum label="Due" value={item.due_date||"—"}/></div>
    {item.description&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm leading-6 text-slate-600">{item.description}</p>}
    {(item.warnings??[]).length>0&&<div className="mt-3 flex gap-2 rounded-xl border border-amber-100 bg-amber-50 p-3 text-xs text-amber-800"><TriangleAlert className="mt-0.5 h-4 w-4 shrink-0"/><span>{(item.warnings??[]).join(" · ")}</span></div>}
    <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto_auto]"><select className={field} value={selectedSupplier[item.id]||item.supplier_id||""} onChange={e=>setSelectedSupplier({...selectedSupplier,[item.id]:e.target.value})}><option value="">No supplier linked yet</option>{(data.suppliers??[]).map(s=><option key={s.id} value={s.id}>{s.name}{s.category?" · "+s.category:""}</option>)}</select>{item.signed_url&&<a href={item.signed_url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 px-4 py-3 text-center text-xs font-bold">Open original</a>}<button disabled={busy||!item.amount} onClick={()=>void action(item.id,item.document_kind==="invoice"?"approve_bill":"post_expense",item)} className="rounded-xl bg-[#0b493b] px-4 py-3 text-xs font-bold text-white">{item.document_kind==="invoice"?"Approve as supplier bill":"Approve & post expense"}</button><button disabled={busy} onClick={()=>void action(item.id,"reject",item)} className="rounded-xl border border-red-200 px-4 py-3 text-xs font-bold text-red-700">Reject</button></div>
   </article>)}{!queue.length&&<div className="xl:col-span-2 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><BadgeCheck className="mx-auto h-7 w-7 text-emerald-600"/><p className="mt-3 text-sm text-slate-500">No documents waiting for review.</p></div>}</div>
  </section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><ReceiptText className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-lg font-semibold">Approved supplier bills</h2></div><div className="mt-4 space-y-2">{bills.slice(0,12).map(b=><div key={b.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="text-sm font-semibold">{b.description}</p><p className="mt-1 text-[11px] text-slate-500">{b.status}{b.due_at?" · due "+b.due_at:""}</p></div><p className="text-sm font-bold">{money(b.total_amount,b.currency)}</p></div>)}{!bills.length&&<p className="text-sm text-slate-500">No supplier bills approved yet.</p>}</div></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><BrainCircuit className="h-5 w-5 text-[#0f5b49]"/><h2 className="text-lg font-semibold">What the AI is allowed to do</h2></div><div className="mt-4 space-y-3 text-sm text-slate-600"><Rule title="Extract" text="Read visible fields and classify the document."/><Rule title="Suggest" text="Propose supplier bill, expense, matter attachment or archive."/><Rule title="Flag" text="Expose uncertainty and low-confidence fields."/><Rule title="Never silently post" text="A human approval is required before financial posting."/></div></div></section>
 </div></main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-white/[.045] p-5"><p className="text-[9px] font-black uppercase tracking-[.13em] text-white/40">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>}
function Datum({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 truncate text-xs font-semibold">{value}</p></div>}
function Rule({title,text}:{title:string;text:string}){return <div className="flex gap-3"><FileCheck2 className="mt-0.5 h-4 w-4 shrink-0 text-[#0f5b49]"/><div><p className="font-semibold text-slate-800">{title}</p><p className="mt-0.5 text-xs leading-5 text-slate-500">{text}</p></div></div>}
