"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bot, Copy, FileText, Search, Sparkles } from "lucide-react";

type Template={id:string;title:string;practice_area:string;jurisdiction:string;language:string;template_body:string;preserved_form_note?:string|null};
type Matter={id:string;title:string;client_name?:string|null;matter_type?:string|null;jurisdiction?:string|null};
type Generation={id:string;title:string;output_text:string;generated_at:string};
type Payload={success:boolean;error?:string;templates?:Template[];matters?:Matter[];generations?:Generation[]};
const field="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-700/40 focus:ring-4 focus:ring-emerald-900/5";
export default function DocumentBankPage(){
 const [data,setData]=useState<Payload>({success:true,templates:[],matters:[],generations:[]}); const[loading,setLoading]=useState(true);const[q,setQ]=useState("");const[selected,setSelected]=useState<Template|null>(null);const[matterId,setMatterId]=useState("");const[context,setContext]=useState("");const[mode,setMode]=useState("standard");const[message,setMessage]=useState("");const[working,setWorking]=useState(false);const[output,setOutput]=useState("");
 async function load(){const r=await fetch("/api/document-bank",{cache:"no-store"});const p=await r.json();if(!p.success)throw new Error(p.error);setData(p);if(!selected&&p.templates?.length)setSelected(p.templates[0]);}
 useEffect(()=>{void load().catch(e=>setMessage(e.message)).finally(()=>setLoading(false));},[]);
 const templates=useMemo(()=> (data.templates??[]).filter(t=>`${t.title} ${t.practice_area} ${t.jurisdiction}`.toLowerCase().includes(q.toLowerCase())),[data.templates,q]);
 async function adapt(){if(!selected)return;setWorking(true);setMessage("");try{const r=await fetch("/api/document-bank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({templateId:selected.id,matterId:matterId||null,contextNote:context,userMode:mode})});const p=await r.json();if(!p.success)throw new Error(p.error);setOutput(p.generation.output_text);setMessage(`Working draft generated via ${p.ai.provider}. Lawyer review required.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to adapt precedent.");}finally{setWorking(false)}}
 if(loading)return <main className="min-h-screen bg-[#eef2ef] p-6">Loading Document Bank…</main>;
 return <main className="min-h-screen bg-[#eef2ef] p-3 text-slate-800 sm:p-5 lg:p-7"><div className="mx-auto max-w-[1700px] space-y-5">
 <section className="rounded-[1.8rem] bg-[#07372d] p-6 text-white sm:p-8"><Link href="/workspace" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-white/55"><ArrowLeft className="h-4 w-4"/>Workspace</Link><p className="mt-6 text-[10px] font-black uppercase tracking-[.22em] text-[#d7bd84]">Document & precedent bank</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Start from institutional memory, not a blank page.</h1><p className="mt-4 max-w-4xl text-sm leading-7 text-white/65">Approved firm precedents stay reusable. Copy them directly or create a governed AI-assisted working draft from matter context. Missing facts remain explicit instead of being invented.</p></section>
 {message&&<div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
 <div className="grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]">
  <aside className="rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 rounded-2xl border border-slate-200 px-3"><Search className="h-4 w-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search precedent, practice or jurisdiction" className="w-full py-3 text-sm outline-none"/></div><div className="mt-3 max-h-[72vh] space-y-2 overflow-auto">{templates.map(t=><button key={t.id} onClick={()=>{setSelected(t);setOutput("")}} className={`w-full rounded-2xl border p-4 text-left ${selected?.id===t.id?"border-emerald-700 bg-emerald-50":"border-slate-100 hover:border-slate-200"}`}><p className="text-sm font-bold text-slate-950">{t.title}</p><p className="mt-2 text-xs text-slate-500">{t.practice_area} • {t.jurisdiction} • {t.language}</p></button>)}</div></aside>
  <section className="space-y-5">{selected&&<><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-400">Approved precedent</p><h2 className="mt-2 text-2xl font-semibold text-slate-950">{selected.title}</h2><p className="mt-2 text-sm text-slate-500">{selected.practice_area} • {selected.jurisdiction} • {selected.language}</p></div><button onClick={()=>void navigator.clipboard.writeText(selected.template_body)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold"><Copy className="h-4 w-4"/>Copy base</button></div>{selected.preserved_form_note&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">Preservation rule: {selected.preserved_form_note}</div>}<pre className="mt-5 max-h-[520px] overflow-auto whitespace-pre-wrap rounded-2xl bg-slate-950 p-5 text-sm leading-7 text-slate-100">{selected.template_body}</pre></div>
  <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-emerald-800"/><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">AI-assisted adaptation</p><h2 className="text-xl font-semibold text-slate-950">Adapt to a real matter, under firm AI policy</h2></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><select className={field} value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">No matter selected</option>{(data.matters??[]).map(m=><option key={m.id} value={m.id}>{m.title}{m.client_name?` — ${m.client_name}`:""}</option>)}</select><select className={field} value={mode} onChange={e=>setMode(e.target.value)}><option value="standard">Standard</option><option value="high_accuracy">High accuracy</option><option value="private">Private</option><option value="local">Local</option></select></div><textarea className={`${field} mt-3 min-h-32`} value={context} onChange={e=>setContext(e.target.value)} placeholder="Matter-specific facts, requested changes, missing clauses, tone, language, procedural posture…"/><button onClick={adapt} disabled={working||(!matterId&&!context.trim())} className="mt-3 inline-flex items-center gap-2 rounded-2xl bg-[#07372d] px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><Bot className="h-4 w-4"/>{working?"Adapting…":"Create working draft"}</button></div>
  {output&&<div className="rounded-[1.5rem] border border-emerald-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold text-slate-950">Working draft</h2><button onClick={()=>void navigator.clipboard.writeText(output)} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><Copy className="h-4 w-4"/>Copy</button></div><pre className="mt-4 whitespace-pre-wrap rounded-2xl bg-[#f8faf9] p-5 text-sm leading-7 text-slate-800">{output}</pre></div>}</>}</section>
 </div></div></main>}
